### ISSUE TITLE
bootstrap css not applied

### ISSUE THREAD

**Issue by HoplaGeiss** [kaliber5/ember-bootstrap#1]
Hello I am completly new to ember.js

I followed the installation guide. However the css is not applied. Do I need to do an import in my scss files ?

for now I just have 
```
var EmberApp = require('ember-cli/lib/broccoli/ember-app');

var app = new EmberApp({
  'ember-bootstrap': {
    'importBootstrapTheme': true,
    'importBootstrapCSS': true,
    'importBootstrapFont': true
  }
});

```

**Comment by simonihmig** [comment]
It should work without any special settings. At least in a normal setup without Sass this works out of the box.

When using Sass I would recommend to set importBootstrapCSS to false anyway, and to import the sass version of the bootstrap styles (bower install --save twitter-bootstrap-sass) into your app.scss, so you can easily customize the bootstrap styles by setting sass variables etc.

**Comment by HoplaGeiss** [comment]
Thanks, my bad. With the correct gem it worked.
