### ISSUE TITLE
Builds invalid syntax for Edge if IE11 is not included in build targets

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#1027]
If Ember Bootstrap is used in a project that does _not_ have IE11 as a build target, an invalid build for Edge is generated.

The `default-decrorator` util uses object rest spread syntax: https://github.com/kaliber5/ember-bootstrap/blob/2ee7cc6527c3d79fa34eaefe7923e0a2be397ffe/addon/utils/default-decorator.js#L13

The feature is not supported by Microsoft Edge. But even if Edge is listed as an explicit build target it's not transpiled by babel.

I thought this is caused by not using the `object-rest-spread` babel transform. I added it in #1026 as [described in ember-cli-babel docs](https://github.com/babel/ember-cli-babel#options). But using that feature branch doesn't fix the issue.

## Steps to reproduce

1. `ember new test-app`
2. `cd test-app`
3. Add Microsoft Edge as build target as [described in Ember Guides](https://guides.emberjs.com/release/configuring-ember/build-targets/) and remove IE11 even for CI and production builds.
4. Run `ember serve` and verify that it works in Microsoft Edge.
5. `ember install ember-bootstrap`
6. Run `ember serve` and open the app in Microsoft Edge again.

You will now see a syntax error in console (and a white page). The error message is not that helpful:

> Expected identifier, string or number

But the stack trace points directly to the object rest spread syntax usage in `default-decorator` util.

I also tested adding the `object-rest-spread` transform to the consuming app itself. But also that doesn't resolve the issue.

If you don't want to follow all steps manually apply these patches to a newly created app:

```patch
diff --git a/config/targets.js b/config/targets.js
index 8ffae36..73ec651 100644
--- a/config/targets.js
+++ b/config/targets.js
@@ -2,6 +2,7 @@
 
 const browsers = [
   'last 1 Chrome versions',
+  'last 1 Edge versions',
   'last 1 Firefox versions',
   'last 1 Safari versions'
 ];
```

```patch
diff --git a/ember-cli-build.js b/ember-cli-build.js
index d690a25..8e5ae91 100644
--- a/ember-cli-build.js
+++ b/ember-cli-build.js
@@ -4,7 +4,13 @@ const EmberApp = require('ember-cli/lib/broccoli/ember-app');
 
 module.exports = function(defaults) {
   let app = new EmberApp(defaults, {
-    // Add options here
+    babel: {
+      plugins: ['transform-object-rest-spread']
+    },
+    'ember-bootstrap': {
+      'bootstrapVersion': 4,
+      'importBootstrapCSS': true
+    }
   });
 
   // Use `app.import` to add additional libraries to the generated
```

```patch
diff --git a/package.json b/package.json
index f41e1b6..761b480 100644
--- a/package.json
+++ b/package.json
@@ -22,8 +22,11 @@
     "@glimmer/component": "^1.0.0",
     "@glimmer/tracking": "^1.0.0",
     "babel-eslint": "^10.0.3",
+    "babel-plugin-transform-object-rest-spread": "^6.26.0",
+    "bootstrap": "^4.3.1",
     "broccoli-asset-rev": "^3.0.0",
     "ember-auto-import": "^1.5.3",
+    "ember-bootstrap": "jelhan/ember-bootstrap#add-babel-plugin-transform-object-rest-spread",
     "ember-cli": "~3.16.0",
     "ember-cli-app-version": "^3.2.0",
     "ember-cli-babel": "^7.17.2",
```

**Comment by simonihmig** [comment]
@jelhan What version of Edge are you using? 

My understanding is:
* `@babel/preset-env` should automatically use `babel-plugin-transform-object-rest-spread` if required
* last version of Edge is 80, which is already Chromium based, so natively supports object spread: https://caniuse.com/#search=object%20spread
* if you are testing it with e.g. Edge 18 (the last "original" Edge version), that would explain the broken build. If so, please test with something like `Edge >= 18` in your `targets.js` 

*IMHO it's a bit unfortunate that versions 80 and 79 are considered the latest versions of Edge in the caniuse database, although those versions have ~0% usage. For specifically this reason we had to update `targets.js` in one of our apps to `Edge >= 17` instead of last 2 versions.*

**Comment by jelhan** [comment]
> if you are testing it with e.g. Edge 18 (the last "original" Edge version), that would explain the broken build. If so, please test with something like `Edge >= 18` in your `targets.js`

Thanks a lot. I wasn't aware of this issue.
