### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#1033]
* add ESLint config
* run `eslint --fix` automatically pre-commit using `husky` and `lint-staged`

**Comment by jelhan** [comment]
I take this one. Have an automated script to set it up. 🤣

**Comment by jelhan** [comment]
Only talking about using Prettier for JavaScript aren't we? Haven't used it yet for Handlebars / Glimmer templates but heard that it's not that stable yet. Would love to test it out but not sure if this is the best repository to start with. Or do you have good experience with it?

**Comment by simonihmig** [comment]
> Only talking about using Prettier for JavaScript aren't we?

Yes.

**Comment by jelhan** [comment]
> automatically pre-commit using `husky` and `lint-staged`

I'm not convinced by this one:

- Running ESLint and prettier is an expensive task. `yarn lint:js --fix` needs 10 seconds on my machine for this repo.
- Running prettier in a pre-commit hook is not needed for my setup. I have configured my editor (VS Code) to fix linting errors when a file is saved. This is very cheap (read: performant) as it's only run against one file and not all.

I think my setup is a very common one. I would suggest that we don't add the precommit hook but document in `CONTRIBUTING.md` how one could configure the local development environment to run prettier automatically? We can list both options: Do it in editor on save or as a local pre-commit hook.

**Comment by jelhan** [comment]
Oh haven't read carefully enough. `lint-staged` would also only run the linting against the files which will be committed. So there wouldn't be a noticeable performance impact except for commits touching a lot of files. Such commits doesn't happen that often.

Still not seeing a need for it as I expect most developers to have their editors configured to fix linting issues on safe. But it would help with onboarding new developers for sure.

**Comment by jelhan** [comment]
Added husky and lint-staged to #1038. Directly noticed that it's slower even if touching only a few files. Committing a change to only one file takes 1.5 seconds with husky + lint-staged. It's only a few milliseconds without it. It's basically adding a waiting step that wasn't there before. To be honest I don't like it. But I can live with it if you prefer to have it in.

**Comment by simonihmig** [comment]
> Still not seeing a need for it as I expect most developers to have their editors configured to fix linting issues on safe. But it would help with onboarding new developers for sure.

I do remember the times where I got failing builds for some silly prettier linting issues when contributing to other codebases that had prettier set up, but I was not yet a regular prettier user (and did not have my IDE set up to auto-fix). So that was annoying for me. I am not sure we can assume everybody is already using prettier, so that *might* help. Given that you don't commit that often, and 1-2 secs is not that terrible, I would *slightly* prefer it. But have not really strong feelings...

**Comment by jelhan** [comment]
> I do remember the times where I got failing builds for some silly prettier linting issues when contributing to other codebases that had prettier set up, but I was not yet a regular prettier user (and did not have my IDE set up to auto-fix). So that was annoying for me. I am not sure we can assume everybody is already using prettier, so that _might_ help.

I fear the setup in #1038 would already annoy developers before they commit if not used to prettier. Prettier is integrated as ESLint plugin. Code not formatted as prettier expects is treated as a linting error. Many editors show such linting errors. Developers used to linting but not used to Prettier may try to fix by hand before committing...

Maybe documentation is key to make it easier for new developers? Will add a chapter to `CONTRIBUTING.md`.

**Comment by simonihmig** [comment]
Closed by #1038
