### ISSUE TITLE
Setup release-it

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#1034]
Including generating Changelog. ~This also means getting rid of our historical `gulp` setup, see #952~

**Comment by jelhan** [comment]
We can use rwjblue's setup script as a starting point: https://github.com/rwjblue/create-rwjblue-release-it-setup

**Comment by jelhan** [comment]
> This also means getting rid of our historical `gulp` setup, see #952

The gulp script currently provides two tasks:

1. Generate the changelog.
2. Build and publish the docs app.

The first one could be replaced by `release-it-lerna-changelog`. This is done in #410 

The seconds one should not be done as part of `release-it` in my opinion. It's better handled by CI in my opinion. It does not only speed up the release cause maintainer does not need to wait until the app is build and uploaded. It could also be used to publish on each merge into `master` as soon as we have versioned docs app. One example addon that uses this strategy is ember-file-upload: https://github.com/adopted-ember-addons/ember-file-upload/blob/4469a3e36f64167940bac65978b57d1bbd936d1c/.travis.yml#L53-L56

**Comment by simonihmig** [comment]
I agree with all you said. Let's keep the docs publishing a separate thing.

**Comment by simonihmig** [comment]
Closed by #1040
