### ISSUE TITLE
Migrate to one way controls

### ISSUE THREAD

**Issue by offirgolan** [kaliber5/ember-bootstrap#104]
I believe that all current input controls should eventually be converted to one-way controls. 

See here: https://github.com/DockYard/ember-one-way-controls

Not only will it be a step in the right direction, but it will also provide some much needed functionality as well as better control on input values.

**Comment by simonihmig** [comment]
Thanks @offirgolan for bringing this up. This also came to my mind recently, but good to have this tracked here... 

Maybe one should completely decouple `bs-form-element` at some time from the used control and make "Custom Controls" as mentioned here http://kaliber5.github.io/ember-bootstrap/api/classes/Components.FormElement.html the default way of using this!?

One could also make an "addon addon" (like those for the validation support) for replacing the default controls with those one-way controls...

**Comment by offirgolan** [comment]
@simonihmig I think that would be good. I would still make sure that form composability with this addon will be as simple as it currently is.

**Comment by simonihmig** [comment]
Closed in favor of #158
