### ISSUE TITLE
SyntaxError when running in fastboot

### ISSUE THREAD

**Issue by wmlele** [kaliber5/ember-bootstrap#1083]
Line 18 of `utils/cp/listen-to.js` is causing my build to fail in FastBoot/Prember:

(output from production build with uglify disabled)
```
/tmp/broccoli-20295StWYlerKPrNu/out-799-srihash_assets/assets/vendor-b8e5906bbd4863cecc2d81d5d03c91e0.js:137519
        return this[dependentKey] ?? defaultValue;
                                   ^

SyntaxError: Unexpected token '?'
    at new Script (vm.js:88:7)
    at VMSandbox.eval (/storage/workspaces/leaf/leaf-mjolnir/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /storage/workspaces/leaf/leaf-mjolnir/node_modules/fastboot/src/ember-app.js:190:15
```
works in browser though.

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^4.0.0-rc.1 -> 4.0.0-rc.1
ember-cli: ~3.18.0 -> 3.18.0
bootstrap: ^4.5.0 -> 4.5.0
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by jelhan** [comment]
What node version are you running and how is your `config/target.js`? Seems like your node version does not support nullish coalescing operator (`??`) and it isn't transpiled by babel.

My first guess is that you don't support IE11 and only latest Edge version (based on Chromium). In that case all target browser would support nullish coalescing operator. But you are using a node version < 14, which does not support nullish coalescing operator.

I don't have much experience with FastBoot but it seems like you should add the node version under which FastBoot runs to `config/target.js`.

**Comment by wmlele** [comment]
Yep, that be it, thanks for explaining.

**Comment by jelhan** [comment]
I think we need to extend the Ember docs for all the edge cases you might face when dropping IE11 support.
