### ISSUE TITLE
Q: value missing?

### ISSUE THREAD

**Issue by basz** [kaliber5/ember-bootstrap#1089]
Why is value not defined (but documented) here?

https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form/element.js#L274

**Comment by jelhan** [comment]
What do you mean by "_not defined_"? The property is defined here: https://github.com/kaliber5/ember-bootstrap/blob/235a2433ccee5defce136b8ee9099cde97268e2e/addon/components/bs-form/element.js#L858

**Comment by basz** [comment]
right... thx... seeing some issues element value not being updated, so that's why i'm looking at sources

**Comment by jelhan** [comment]
Actually it seems to be unnecessary complicated. This could be simplified as soon as the component is rewritten as a Glimmer Component to something like this:

```js
get value() {
  return this.args.hasOwnProperty('value') ? this.args.value : this.model[this.property];
}
set value(value) {
  if (this.args.hasOwnProperty('value')) {
    this.args.value = value;
  } else {
    this.model[this.property] = value;
  }
}
```

**Comment by jelhan** [comment]
@simonihmig Just noticed that this two-way binding is not supported anymore after refactoring `<BsForm::Element>` to `@glimmer/component`. `this.args` and all it's values is immutable for glimmer components. We should consider dropping that feature in v4. What do you think?

**Comment by basz** [comment]
I use this.value inside the my custom controls to receive values. And use this.onChange(value) to send values back.

DDAU. So yes, I think we should drop that feature.

**Comment by simonihmig** [comment]
Closing this, as we agreed to land #1097!
