### ISSUE TITLE
how to set radio control initial option?

### ISSUE THREAD

**Issue by mwasilewski** [kaliber5/ember-bootstrap#1099]
Hi, I cannot find it anywhere in documentation, how to set initial checked option in radio?
 
in js I have:

```
  radio = null

  init() {
    super.init(...arguments)
    this.radioOptions = [{ label: 'Admin' }, { label: 'Manager' }, { label: 'Client' }];
  }
```
 
in hbs:

```
<BsForm @formLayout="vertical" @model={{this}} @onSubmit={{action "submit"}} as |form|>

  <form.element @controlType="radio" @label="Role" @property="role" @options={{radioOptions}} @optionLabelPath="label"/>

  <BsButton @defaultText="Submit" @type="primary" type="submit" />

</BsForm>
```
 
tied to set radio property in different ways but seems not working. 
 
---

Output from `ember bootstrap:info`:

```
ember-bootstrap: ^3.1.3 -> 3.1.3
```

**Comment by jelhan** [comment]
The currently selected radio option depends on the value of `@property` of `@model`. So in your case it's `this.role`. If the value is not present in `@options` no option is shown as selected.

**Comment by mwasilewski** [comment]
Hi, I did try that and seems not work. 
Here is minimal repo, only ember and ember bootstrap. 
https://github.com/mwasilewski/1099
 
There is only application controller and template and one form:
https://github.com/mwasilewski/1099/blob/master/app/controllers/application.js
https://github.com/mwasilewski/1099/tree/master/app/templates
 
I tried like that:

```
radio = "Admin"
init() {
  super.init(...arguments)
  this.radioOptions = [{ label: 'Admin' }, { label: 'Manager' }, { label: 'Client' }];
}
```

```
radio = { label: 'Admin' }
init() {
  super.init(...arguments)
  this.radioOptions = [{ label: 'Admin' }, { label: 'Manager' }, { label: 'Client' }];
}
```

```
init() {
  super.init(...arguments)
  this.radioOptions = [{ label: 'Admin' }, { label: 'Manager' }, { label: 'Client' }];
  this.radio = 'Admin';
}
```

```
init() {
  super.init(...arguments)
  this.radioOptions = [{ label: 'Admin' }, { label: 'Manager' }, { label: 'Client' }];
  this.radio = { label: 'Admin' };
}
```

**Comment by jelhan** [comment]
Ember Bootstrap is not doing a deep equal. If you are dealing with objects it must be a reference to the same object.

```js
let radioOptions = [{ label: 'Admin' }, { label: 'Manager' }, { label: 'Client' }];
radioOptions.includes({ label: 'Admin' }); // false
radioOptions.includes(this.radioOptions[0]); // true
```

**Comment by mwasilewski** [comment]
That was that! Thank you for quick response!
