### ISSUE TITLE
Text area to auto resize as user types

### ISSUE THREAD

**Issue by kuatsure** [kaliber5/ember-bootstrap#110]
we have a need for a feature that expands the textarea as the user types. For that right now we don't use ember bootstrap textarea components and just use the normal textarea helper with this addon as well https://github.com/tim-evans/ember-autoresize. For consistency sake, we'd love to continue using components created by your addon, would there be any way to have this functionality built in?

**Comment by simonihmig** [comment]
The purpose of the textarea and input components of ember-bootstrap is just to add the required class names for the default bootstrap CSS styling. Apart from that it does not add any functionality. So there is really no need to use the ember-bootstrap components. Just create your own textarea component (or override `bs-textarea`), inherit from the ember-autoresize component and add the required class name: `classNames: ['form-control'].

You could even just apply the class in the template like this:
```
{{textarea class="form-control" autoresize=true rows=2}}
```
But you would have to do this everywhere you use it then...

**Comment by kuatsure** [comment]
still learning ember ... how would you override `bs-textarea`?

**Comment by simonihmig** [comment]
```
ember generate component bs-textarea
```

This will generate a new component in your app tree under the name of bs-textarea, and thus override or "hide" the component implementation of ember-bootstrap. Import the textarea component from ember-autoresize, extend from it and add the `classNames` Property.

Hope that helps!

**Comment by kuatsure** [comment]
@simonihmig awesome, thanks for the help :)

**Comment by Redsandro** [comment]
@kuatsure what method did you end up going with?

All that needs to be added is a single `autoresize=true` attribute, but I believe there is no super simple way to do that. Am I wrong?

E.g.:

```
{{#bs-form formLayout="vertical" model=email as |form|}}
	{{#form.element controlType="textarea" property="textEdit" as |el|}}
		{{el.control autoresize=true}}
	{{/form.element}}
{{/bs-form}}
```

It looks like I cannot simply create a new `bs-textarea` (anymore) because I believe there are some necessary bindings and events now (2019): https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-form/element/control/textarea.js

**Comment by kuatsure** [comment]
@Redsandro 	a blast from the past this is ... lol ... it was over a couple iterations ( with support for ie9 & ie11 ) but we ended up going with a combination solution that used the below:

**Comment by Redsandro** [comment]
@kuatsure yet so simple! Thank you for looking it up. This is a lot more lightweight than `ember-autoresize`. I'm tempted to say it's still relevant today.
