### ISSUE TITLE
Dual bootstrap support chapter in contributing docs is outdated

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#1124]
`CONTRIBUTING.md` does not reflect the changes to dual bootstrap support yet. Especially it still mentions the bootstrap version specific trees, which have been dropped in #992. On the other side it does not discuss the build macros introduced in #992 and follow-up merge requests.

**Comment by simonihmig** [comment]
Good catch! PRs welcome! 😜
