### ISSUE TITLE
Add dropup support for bs-dropdown

### ISSUE THREAD

**Issue by damoberg** [kaliber5/ember-bootstrap#114]
In the Bootstrap [documentation for button dropdowns](http://getbootstrap.com/components/#dropdowns) there is a possibility to make the dropdown to "dropup" by adding a `.dropup` class to the parent element.

I cannot se that this is supported right now in bs-dropdown. Perhaps there is a workaround?

**Comment by simonihmig** [comment]
You are right, it seems I have overlooked this functionality, this is missing.
I will add this as time permits, hopefully within the next few days!
