### ISSUE TITLE
Compatibility with other addons that expect bootstrap JS?

### ISSUE THREAD

**Issue by duro** [kaliber5/ember-bootstrap#115]
I am using `ember-models-table` which has a peer dependency on the Bootstrap JS. Since it's components were not implemented with `ember-bootstrap` in mind, it seems that the drop-downs, etc that it implements do not work.

Is `ember-bootstrap` compatible with also loading the bootstrap JS files in as a vendor script? Before I spend much time on this, or perhaps they are already loaded, and I am troubleshooting the wrong thing, could you let me know?

**Comment by simonihmig** [comment]
`ember-bootstrap` does not load any external JS. You should be able to import `bootstrap.js? from your `ember-cli-build.js`. However you have to take care that ember-bootstrap and bootstrap.js does not interfere on the same elements. Bootstrap.js looks for certain data attributes to automatically apply the JS functionality to them, so as long as the ember-bootstrap generated element do not have those data attributes, everything should (not tested!) be fine. 

However in your with those dropdowns, ember-bootstrap does in fact add the `data-toggle` attribute, which would probably trigger bootstrap.js: https://github.com/twbs/bootstrap/blob/master/js/dropdown.js#L17

Honestly I do not remember why ember-bootstrap does this, the data attribute should not be needed. I will try to remove it if that does not break anything...
