### ISSUE TITLE
DEPRECATION: The use of the private `{{-in-element}}`

### ISSUE THREAD

**Issue by sergchernata** [kaliber5/ember-bootstrap#1162]
> DEPRECATION: The use of the private `{{-in-element}}` is deprecated, please refactor to the public `{{in-element}}`. ('ember-bootstrap/templates/components/bs-modal.hbs' @ L1:C0)  [deprecation id: glimmer.private-in-element]

This deprecation is shown for several elements such as `ember-popper.hbs`, `ember-popper-targeting-parent.hbs`, `bs-modal-simple.hbs` and `bs-modal.hbs`.

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^3.1.4 -> 3.1.4
ember-cli: ^3.20.0 -> 3.20.0
bootstrap: ^4.5.0 -> 4.5.0
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
```

**Comment by jelhan** [comment]
I think this is fixed in the latest release candidate for v4. I don't think we have the bandwidth to backport that fixes to v3.

**Comment by simonihmig** [comment]
Agree. It's "just" a deprecation after all, so should still be working. The upcoming v4 release will have that fixed.
