### ISSUE TITLE
Form validation example is broken in dummy app

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#117]
cd324d165de0654ddcb62ef597110d053093fc1c has removed `ember-bootstrap-validations` and `ember-validations` from `devDependencies`. Therefore form validation example in dummy app is broken.

**Comment by simonihmig** [comment]
You are right about this. However the dummy app was never meant as something as a supported feature for other users, more a playground for myself when developing new features.

However I plan to transform the dummy app into a demo app, that will be published on the github page. So the dummy app is expected to me replaced, hopefully soon. So I will probably not care about this issue for the time being...
