### ISSUE TITLE
BsButton and async actions

### ISSUE THREAD

**Issue by basz** [kaliber5/ember-bootstrap#1184]
I've been refactoring some actions toward async handling and noticed that suddenly exception throw from code deep inside the action isn't handled any more.

After a long time, I came to realize that it is the BsButton component that supports promises and therefor swallows the exception.

I would like to propose to do one of two things

1. Place a big warning in the documentation that exceptions are handled only with a @rejectedText="Oups!?".

or

2a. Add options to rethrow exceptions.
or
2b Rethrow exception when @rejectedText={{falsy}}

**Comment by jelhan** [comment]
Can you please provide a reproduction? I can recall that we had some errors like this when introducing the state support on `<BsButton>`. But I thought we have fixed all of them.

**Comment by jelhan** [comment]
Closing this due to missing feedback. Please feel free to reopen / comment if you still face this issue.
