### ISSUE TITLE
Autocomplete and tags functionality

### ISSUE THREAD

**Issue by dipeshpp** [kaliber5/ember-bootstrap#119]
Is it possible to implement autocomplete (ideally with input tags) functionality with ember-bootstrap? If so, could you please provide an example? If not, could you suggest some alternatives?

**Comment by villander** [comment]
@dipeshpp you can create a component in your app named `bs-input-tags` that extend `bs-input` from `ember-bootstrap` 

// app/components/bs-input-tags.js
```javascript
import BsInputTags  from 'ember-bootstrap/components/bs-accordion-item';
export default BsInputTags.extend({
    // your stuff here
  }
});
```

I think too that `autocomplete and tags` is a feature of a plugin to bootstrap. This repo is a bootstrap in ember way.

You can create a addon with these feature using bootstrap, pluggable with any project ember with use bootstrap as dependency

**Comment by simonihmig** [comment]
As @villander said, autocomplete is not an out-of-the-box feature of bootstrap, and as such it won't be implemented here. I think [typeahead.js](https://twitter.github.io/typeahead.js/) is the solution from Twitter that you were thinking of. 

It seems there are a couple of addons that deal with this: https://emberobserver.com/?query=typeahead. I cannot recommend anyone thought, as I have not used them...
