### ISSUE TITLE
DEPRECATION: Extending from ember-bootstrap component classes is not supported

### ISSUE THREAD

**Issue by maxwondercorn** [kaliber5/ember-bootstrap#1191]
Converting from v3 to v4 and I see this deprecation warning where  `BSForm` components are used.  The `BSForm`'s are used in route templates with <form.element>'s for inputs.  I'm not extending the component class. 

Unfortunately there isn't enough information in the stack dump to figure out what might be triggering the warning

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^4.0.0 -> 4.0.0
ember-cli: ~3.16.0 -> 3.16.2
bootstrap: ^4.5.2 -> 4.5.2
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
whitelist: undefined

```

**Comment by jelhan** [comment]
Are you using ember-bootstrap-changeset-validations or another plugin for Ember Bootstrap?

**Comment by maxwondercorn** [comment]
Yes I am using ember-bootstrap-cp-validations

**Comment by simonihmig** [comment]
Just released a new version that should fix this: https://github.com/offirgolan/ember-bootstrap-cp-validations/releases/tag/v2.0.0
