### ISSUE TITLE
Version 4.0.1 and ember-popper @id problem, bootstrap 3 less and bootstrap 4 sass

### ISSUE THREAD

**Issue by martinbarilik** [kaliber5/ember-bootstrap#1200]
I am doing step by step according to 

[https://bushbaby.nl/emberjs-sass-bootstrap/][1]

  [1]: https://bushbaby.nl/emberjs-sass-bootstrap/

but i am ending up with error

    martinko5mb@debian:~/Projects/XXX$ ember install ember-bootstrap
    WARNING: Node v12.18.3 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
    WARNING: Ember CLI is using the global npm, but your npm version has not yet been verified to work with the current Ember CLI release.
    npm: Installed ember-bootstrap
    installing ember-bootstrap
    Installing for Bootstrap 4 using preprocessor sass
      uninstall bower package bootstrap-sass
      install package bootstrap
    WARNING: Ember CLI is using the global npm, but your npm version has not yet been verified to work with the current Ember CLI release.
    npm: Installed bootstrap@^4.3.1
    Added import statement to app/styles/app.scss
    Added ember-bootstrap configuration to ember-cli-build.js
    Installed addon package.
    martinko5mb@debian:~/Projects/XXX$ ember s
    WARNING: Node v12.18.3 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
    Could not start watchman
    Visit https://ember-cli.com/user-guide/#watchman for more info.
    Template Compiler Error (broccoli-persistent-filter:TemplateCompiler) in ember-popper/templates/components/ember-popper-targeting-parent.hbs
    
    Assertion Failed: '@id' is not a valid path. ('ember-popper/templates/components/ember-popper-targeting-parent.hbs' @ L10:C12) 
   
    
    Stack Trace and Error Report: /tmp/error.dump.4d09eefb1bc452f18a3bd776af5c84b0.log

And the error.dump.4d09eefb1bc452f18a3bd776af5c84b0.log looks like:

    =================================================================================
    ENV Summary:
    
      TIME: Mon Aug 24 2020 14:36:17 GMT+0200 (Central European Summer Time)
      TITLE: ember
      ARGV:
      - /usr/bin/node
      - /usr/bin/ember
      - s
      EXEC_PATH: /usr/bin/node
      TMPDIR: /tmp
      SHELL: /bin/bash
      PATH:
      - /home/martinko5mb/.ebcli-virtual-env/executables
      - /home/martinko5mb/.pyenv/versions/3.7.2/bin
      - /home/martinko5mb/.rvm/gems/ruby-2.7.0/bin
      - /home/martinko5mb/.rvm/gems/ruby-2.7.0@global/bin
      - /home/martinko5mb/.rvm/rubies/ruby-2.7.0/bin
      - /usr/local/bin
      - /usr/bin
      - /bin
      - /usr/local/games
      - /usr/games
      - /home/martinko5mb/.rvm/bin
      - /home/martinko5mb/.rvm/bin
      - /home/martinko5mb/.rvm/bin
      PLATFORM: linux x64
      FREEMEM: 170614784
      TOTALMEM: 16747925504
      UPTIME: 24726
      LOADAVG: 1.99853515625,1.36474609375,1.068359375
      CPUS:
      - AMD Ryzen 5 2600 Six-Core Processor - 1686
      - AMD Ryzen 5 2600 Six-Core Processor - 2341
      - AMD Ryzen 5 2600 Six-Core Processor - 3788
      - AMD Ryzen 5 2600 Six-Core Processor - 3432
      - AMD Ryzen 5 2600 Six-Core Processor - 3782
      - AMD Ryzen 5 2600 Six-Core Processor - 3045
      - AMD Ryzen 5 2600 Six-Core Processor - 1839
      - AMD Ryzen 5 2600 Six-Core Processor - 2269
      - AMD Ryzen 5 2600 Six-Core Processor - 3784
      - AMD Ryzen 5 2600 Six-Core Processor - 3124
      - AMD Ryzen 5 2600 Six-Core Processor - 3782
      - AMD Ryzen 5 2600 Six-Core Processor - 3777
      ENDIANNESS: LE
      VERSIONS:
      - ares: 1.16.0
      - brotli: 1.0.7
      - cldr: 37.0
      - http_parser: 2.9.3
      - icu: 67.1
      - llhttp: 2.0.4
      - modules: 72
      - napi: 6
      - nghttp2: 1.41.0
      - node: 12.18.3
      - openssl: 1.1.1g
      - tz: 2019c
      - unicode: 13.0
      - uv: 1.38.0
      - v8: 7.8.279.23-node.39
      - zlib: 1.2.11
    
    ERROR Summary:
    
      - broccoliBuilderErrorStack: Error: Assertion Failed: '@id' is not a valid path. ('ember-popper/templates/components/ember-popper-targeting-parent.hbs' @ L10:C12) 
        at new EmberError (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:6939:25)
        at /home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:7187:13
        at PathExpression (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:15381:54)
        at visitNode (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3197:39)
        at visitKey (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3237:23)
        at visitNode (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3212:17)
        at visitKey (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3237:23)
        at visitNode (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3212:17)
        at visitArray (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3254:22)
        at visitKey (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3235:13)
      - code: [undefined]
      - codeFrame: Assertion Failed: '@id' is not a valid path. ('ember-popper/templates/components/ember-popper-targeting-parent.hbs' @ L10:C12) 
      - errorMessage: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:TemplateCompiler` plugin. 💥
    Assertion Failed: '@id' is not a valid path. ('ember-popper/templates/components/ember-popper-targeting-parent.hbs' @ L10:C12) 
      - errorType: Template Compiler Error
      - location:
        - column: [undefined]
        - file: ember-popper/templates/components/ember-popper-targeting-parent.hbs
        - line: [undefined]
        - treeDir: /home/martinko5mb/Projects/XXX/tmp/broccoli_persistent_filtertemplate_compiler-input_base_path-XzGXowua.tmp
      - message: Build Canceled: Broccoli Builder ran into an error with `broccoli-persistent-filter:TemplateCompiler` plugin. 💥
    Assertion Failed: '@id' is not a valid path. ('ember-popper/templates/components/ember-popper-targeting-parent.hbs' @ L10:C12) 
      - name: Error
      - nodeAnnotation: broccoli-persistent-filter:TemplateCompiler
      - nodeName: broccoli-persistent-filter:TemplateCompiler
      - originalErrorMessage: Assertion Failed: '@id' is not a valid path. ('ember-popper/templates/components/ember-popper-targeting-parent.hbs' @ L10:C12) 
      - stack: Error: Assertion Failed: '@id' is not a valid path. ('ember-popper/templates/components/ember-popper-targeting-parent.hbs' @ L10:C12) 
        at new EmberError (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:6939:25)
        at /home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:7187:13
        at PathExpression (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:15381:54)
        at visitNode (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3197:39)
        at visitKey (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3237:23)
        at visitNode (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3212:17)
        at visitKey (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3237:23)
        at visitNode (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3212:17)
        at visitArray (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3254:22)
        at visitKey (/home/martinko5mb/Projects/XXX/node_modules/ember-source/dist/ember-template-compiler.js:3235:13)
    
    =================================================================================

I am fairly new to the EmberJS, and trying to update the thing in existing project (currently at ember-cli 2.18 succesfuly) I use bootstrap on rails projects, which converted to sass in the past few years. That is why i am doing this.

package.json

    {
      "directories": {
        "test": "tests"
      },
      "scripts": {
        "build": "ember build",
        "lint:js": "eslint ./*.js app config lib server tests",
        "start": "ember serve",
        "test": "ember test"
      },
      "engines": {
        "node": "^4.5 || 6.* || >= 7.*"
      },
      "devDependencies": {
        "bootstrap": "^4.5.2",
        "broccoli-asset-rev": "^3.0.0",
        "broccoli-funnel": "^3.0.3",
        "broccoli-merge-trees": "^4.2.0",
        "ember-ajax": "^3.0.0",
        "ember-bootstrap": "^4.0.1",
        "ember-cli-app-version": "^3.0.0",
        "ember-cli-babel": "^6.6.0",
        "ember-cli-bootstrap-datepicker": "0.6.1",
        "ember-cli-dependency-checker": "^2.0.0",
        "ember-cli-deploy": "^1.0.0-beta.1",
        "ember-cli-deploy-build": "^2.0.0",
        "ember-cli-deploy-display-revisions": "1.0.1",
        "ember-cli-deploy-revision-data": "1.0.0",
        "ember-cli-deploy-s3": "^1.4.0",
        "ember-cli-deploy-s3-index": "^1.1.0",
        "ember-cli-deprecation-workflow": "1.0.1",
        "ember-cli-eslint": "4.2.3",
        "ember-cli-g-maps": "^0.5.14",
        "ember-cli-htmlbars": "^2.0.1",
        "ember-cli-htmlbars-inline-precompile": "^1.0.0",
        "ember-cli-inject-live-reload": "^1.4.1",
        "ember-cli-jshint": "^1.0.5",
        "ember-cli-moment-shim": "^3.7.1",
        "ember-cli-notifications": "^6.3.0",
        "ember-cli-qunit": "4.4.0",
        "ember-cli-release": "^0.2.9",
        "ember-cli-sass": "^10.0.1",
        "ember-cli-shims": "^1.2.0",
        "ember-cli-sri": "^2.1.0",
        "ember-cli-uglify": "^2.0.0",
        "ember-countdown": "1.0.0",
        "ember-data": "3.1.1",
        "ember-export-application-global": "^2.0.0",
        "ember-font-awesome": "3.1.1",
        "ember-load-initializers": "^1.0.0",
        "ember-math-helpers": "2.1.0",
        "ember-moment": "7.8.0",
        "ember-power-select": "2.3.5",
        "ember-resolver": "^4.0.0",
        "ember-source": "~2.18.0",
        "eslint-plugin-ember": "^5.0.0",
        "liquid-fire": "0.31.0",
        "loader.js": "^4.2.3",
        "sass": "^1.26.10"
      },
      "dependencies": {
        "bower": "^1.8.8",
        "ember-auto-import": "^1.5.3",
        "ember-cli": "~2.18.2",
        "ember-on-modifier": "^1.0.1",
        "geolib": "^3.3.1"
      },
      "main": "ember-cli-build.js",
    }

Anyway, what am i missing ?

**Comment by simonihmig** [comment]
> https://bushbaby.nl/emberjs-sass-bootstrap/

That "guide" seems quite confusing, as it does so much that is not necessary, like all of that manual Sass and broccoli setup. Installing ember-bootstrap together with Sass support is described here https://www.ember-bootstrap.com/getting-started/setup. So this should do it:

```bash
ember generate ember-bootstrap --preprocessor=sass
```
Better remove all the previous setup...

Regarding the actual error you see, it seems you are using Ember v2.18, which is very old and not supported anymore. For ember-bootstrap v4 you need Ember 3.16 as stated in the Readme. If you cannot upgrade, you have to use the latest 3.x version, which supported 2.18. However this is not maintained anymore!
