### ISSUE TITLE
Installing Ember Bootstrap throws in a newly generated ember app with Ember CLI 3.20.0

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#1201]
I just noticed that `ember install ember-bootstrap` in a newly generated Ember application with Ember CLI `3.20.0` throws:

```
$ ember install ember-bootstrap

🚧  Installing packages... This might take a couple of minutes.
Yarn: Installed ember-bootstrap
_1.MacrosConfig.astPlugins is not a function


Stack Trace and Error Report: /tmp/error.dump.00e2b30443199e52ab958e6038db1fd8.log
An error occurred in the constructor for ember-bootstrap at /home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/ember-bootstrap
```

```
ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - code: [undefined]
  - codeFrame: [undefined]
  - errorMessage: _1.MacrosConfig.astPlugins is not a function
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: _1.MacrosConfig.astPlugins is not a function
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: _1.MacrosConfig.astPlugins is not a function
    at Class.setupPreprocessorRegistry (/home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/@embroider/macros/src/ember-addon-main.js:73:58)
    at /home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/ember-cli-preprocess-registry/preprocessors.js:27:13
    at Array.forEach (<anonymous>)
    at setupRegistryForEachAddon (/home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/ember-cli-preprocess-registry/preprocessors.js:25:10)
    at Object.module.exports.setupRegistry (/home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/ember-cli-preprocess-registry/preprocessors.js:46:3)
    at Class.init (/home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/ember-cli/lib/models/addon.js:323:7)
    at Class.superWrapper [as init] (/home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/core-object/lib/assign-properties.js:34:20)
    at Class.init (/home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/ember-bootstrap/index.js:43:22)
    at Class.superWrapper [as init] (/home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/core-object/lib/assign-properties.js:34:20)
    at new CoreObject (/home/jelhan/tmp/test-ember-bootstrap-form-with-custom-control/node_modules/core-object/core-object.js:9:15)
```

Steps to reproduce:

1. `npx ember-cli@3.20.0 new test-project`
2. `cd test-project`
3. `ember install ember-bootstrap`

The error seems to be related to `@embroider/macros`. Used version of `@embroider/marcos` is `0.21.0`. It throws in this line: https://github.com/embroider-build/embroider/blob/6e8b52395ddade767cf36c9c3dc687dd92d6d531/packages/macros/src/ember-addon-main.ts#L76-L83 Please note that line numbers do not match with the error stack trace cause it's using TypeScript and the line numbers in the error stack trace refer to the compiled JavaScript.

All Ember Bootstrap does before is calling super on `init` hook: https://github.com/kaliber5/ember-bootstrap/blob/9fceefb1f8702eee2de6736f86e8a4ccac4f9681/index.js#L42-L43 So it might not be related to Ember Bootstrap at all but a general issue with `@embroider/macros.

It's working fine if installing Ember Bootstrap and running it's blueprints separetly: `yarn add -D ember-bootstrap && ember generate ember-bootstrap` instead of `ember install ember-bootstrap`.

Current Ember Bootstrap version when reporting is `4.0.1`. I have not tested with any other combination than `ember-cli@3.20.0` and `ember-bootstrap@4.0.1`.

**Comment by acorncom** [comment]
I saw the identical error with Ember CLI 3.18 and Ember Bootstrap 4.0.1 yesterday as well

**Comment by simonihmig** [comment]
Confirmed. That's pretty bad actually 😱

Will investigate, however this is difficult to debug, as it seems this only happens when installing indeed. So no chance to just put a `console.log` somewhere in `@embroider/macros`, as that does not exist yet in `node_modules` 😟

**Comment by jelhan** [comment]
> Will investigate, however this is difficult to debug, as it seems this only happens when installing indeed. So no chance to just put a `console.log` somewhere in `@embroider/macros`, as that does not exist yet in `node_modules` worried

It may work if you are using a monorepo setup. But haven't tested if the error could be reproduced in that setup.

**Comment by simonihmig** [comment]
That was a really tricky one. Reported my investigation here: https://github.com/embroider-build/embroider/issues/509

Seems we cannot really do something on this addon's side. Hope this gets resolved somehow.

In the meantime will keep this issue open, for visibility. The workaround for users running into this issue is as mentioned above to first install the addon with the native tools (`yarn add -D ember-bootstrap` or `npm install -D ember-bootstrap`), and then run the blueprint, either the one with default settings as `ember generate ember-bootstrap`, or any of the more advanced variants as explained in the [setup guide](https://www.ember-bootstrap.com/getting-started/setup).

**Comment by jelhan** [comment]
> The workaround for users running into this issue is as mentioned above to first install the addon with the native tools (`yarn add -D ember-bootstrap` or `npm install -D ember-bootstrap`), and then run the blueprint, either the one with default settings as `ember generate ember-bootstrap`, or any of the more advanced variants as explained in the [setup guide](https://www.ember-bootstrap.com/getting-started/setup).

Even easier: Run the install command twice. First run will fail but second run will pass (cause first run has modified the dependencies).

**Comment by simonihmig** [comment]
Closed by https://github.com/ef4/ember-auto-import/pull/308, can confirm this does not happen anymore with a fresh new app having the latest `ember-auto-import`.
