### ISSUE TITLE
Support staticComponents with Embroider

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#1206]
Currently we use string properties defined on a component class and the `{{component}}` helper to refer to other used components like here: https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form/element.js#L816, or even "worse" this: https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form/element.js#L797-L808.

This is done so we can override components from the caller side, so the actually used components are not hardcoded in the template. This pattern however makes it basically impossible to statically analyze component usage, therefore the more aggressive `staticComponents` of Embroider to tree-shake unused components would certainly not work currently.

We should support that in the future. Which AFAIU means getting rid of component strings defined on the class. Importing a component class and passing that to the component helper *should* work.

Related:
* https://github.com/emberjs/ember.js/issues/19099
* https://github.com/kaliber5/ember-bootstrap/pull/1125

**Comment by jelhan** [comment]
Fully agree that we should support tree-shaking through Embroider as soon as possible. Tree-shaking is especially import for addons such as Ember Bootstrap, which provide a huge set of components, form which applications may only use a small subset. It's basically a zero-config replacement for the `whitelist` option.

> This is done so we can override components from the caller side, so the actually used components are not hardcoded in the template.

I think we should reevaluate that one in general. It's a little bit odd that we add complexity to allow a caller to override the used components while declaring it as private at the same time.

I get that declaring them public would only make sense if we treat the arguments passed to them public as well. This would increase our API surface a lot and make refactoring the code even harder. So not a big fan of that one either.

On the other hand not supporting it at all limits use cases. Customization in a UI library build on top of Ember Bootstrap will be way harder. So it's also not optimal.

Maybe having this odd situation of making it possible but without official support is the best trade off we can make. But I felt that raising the question is needed.

> Importing a component class and passing that to the component helper _should_ work.

Maybe we can use that chance and also refactor to some kind of angle bracket component invocation. I think / hope that this works:

```hbs
{{#let (component this.myComponentClass) as |MyComponent|}}
  <MyComponent @myArgument={{this.foo}} data-test-some-attribute ...attributes />
{{/let}}
```

**Comment by simonihmig** [comment]
So, using part of my OSS friday today to work on this (after https://github.com/embroider-build/embroider/pull/521 has been merged, but still unreleased)...

> I get that declaring them public would only make sense if we treat the arguments passed to them public as well. 

Do you have specific cases in mind, where this would be an issue? Like most components that are accepted as args are also yielded back anyway, and such are public, including their (public) arguments. 

I was mainly worried that this API of accepting custom components could hinder development, so indeed saw that feature as a) something we need internally anyway in some cases and b) users can use it "at their own risk"

But I am open about making this API eventually public. 

One thing that we did learn here already due to the constraints of embroiders tree-shaking capability is that we `cannot` allow them to be passed as strings! So it must be like `<BsAccordion @itemComponent={{component "my-own-item"}}>` vs. `<BsAccordion @itemComponent="my-own-item">`. The latter works today, but breaks tree-shaking. The former works!

A helper to assert that in development would be nice. Things like that are discussed in more detail in https://github.com/embroider-build/embroider/issues/487, I highly recommend to look at this issue!

> Maybe we can use that chance and also refactor to some kind of angle bracket component invocation.

We already do that in some places, like https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-modal.hbs#L2-L20. Basically where we need to apply HTML attributes to dynamic components.

Mind though that `(component this.myComponentClass)` does *not* work with tree-shaking! Current Embroider build output

```
WARNING: ignoring dynamic component this.titleComponent in /private/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/embroider/9d4dc2/components/bs-accordion/item.hbs

```
