### ISSUE TITLE
Ember-Bootstrap breaks apps with Fastboot

### ISSUE THREAD

**Issue by lionelrudaz** [kaliber5/ember-bootstrap#1210]
Hi,

I ran into a problem today with my app when I tried to enable Fastboot. I got the following error:

```
App is being served by FastBoot
/var/folders/ks/srxf8nks29s4r69wvfk66s9r0000gn/T/broccoli-60500X849M01DZMlA/out-421-append_ember_auto_import_analyzer/assets/vendor.js:106338
        return this[dependentKey] ?? defaultValue;
                                   ^

SyntaxError: Unexpected token '?'
    at new Script (vm.js:88:7)
    at VMSandbox.eval (/Users/lionelrudaz/Sites/front-banane-tato/node_modules/fastboot/src/vm-sandbox.js:13:22)
    at /Users/lionelrudaz/Sites/front-banane-tato/node_modules/fastboot/src/ember-app.js:190:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/Users/lionelrudaz/Sites/front-banane-tato/node_modules/fastboot/src/ember-app.js:187:21)
    at EmberApp.retrieveSandboxedApp (/Users/lionelrudaz/Sites/front-banane-tato/node_modules/fastboot/src/ember-app.js:235:10)
    at new EmberApp (/Users/lionelrudaz/Sites/front-banane-tato/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/Users/lionelrudaz/Sites/front-banane-tato/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/lionelrudaz/Sites/front-banane-tato/node_modules/fastboot/src/index.js:52:10)
    at /Users/lionelrudaz/Sites/front-banane-tato/node_modules/ember-cli-fastboot/index.js:335:29
```

Ember Bootstrap is in version 4.0.1. Ember in 3.20.2.

I tried with a new app, installing package by package, and the app breaks right after the installation of Ember Bootstrap. 

Any ideas what can be the issue?

Let me know if you need more information.

**Comment by jelhan** [comment]
What node version are you using? Seems as if the nullish coalescing operator is not supported but is also not transpiled by babel. I'm not a Fastboot expert but I thought it's also using the normal Ember build output isn't it? In that case you may need to add your node version to `config/target.js`. But I would try to upgrade the node version instead. Shipping transpiled code to the browser just to support local node version seems to be odd.

**Comment by lionelrudaz** [comment]
Thanks for the answer. My node version is v12.18.3. I don't know much about Fastboot, so I'm relying a bit on all of you.

**Comment by jelhan** [comment]
> My node version is v12.18.3.

[Accordingly to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) nullish coalescing operator is only available in node 14. If you have a chance please try to upgrade and see if it's working. Otherwise try to add node 12 to your `config/target.js`.

**Comment by lionelrudaz** [comment]
Got it. Is it OK that the library doesn't support the current LTS version of Node?

**Comment by jelhan** [comment]
> Got it. Is it OK that the library doesn't support the current LTS version of Node?

It supports it. But it requires you to configure build targets correctly. Please find more details on the topic [in Ember CLI docs](https://cli.emberjs.com/release/advanced-use/build-targets/). If using Fastboot the node version under which it runs is a build target just as recent versions of Chrome, Firefox, Safari or IE11.

Does updating node version to 14.x or configuring `config/target.js` to include node 12 fixed your issue?

**Comment by jelhan** [comment]
This PR proposes to change `config/targets.js` to support the node version used to build when installing Fastboot: https://github.com/ember-fastboot/ember-cli-fastboot/pull/770 This might be what you are looking for.

**Comment by simonihmig** [comment]
I agree, that's the solution to add current node to your `targets.js`. This could happen with any addon that uses more modern JS features than your current node version supports, so not specific to ember-bootstrap. 

Here is an example we have in on of our apps:

```js
module.exports = {
  node: true,
  browsers: [
    'last 2 Chrome versions',
    'last 2 Firefox versions',
    'last 2 Safari versions',
    'Edge >= 17',
    'iOS >= 12.4',
    'last 2 ChromeAndroid versions',
  ],
};
```

Therefore closing this.
