### ISSUE TITLE
address a specific modal in acceptance tests

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#122]
I guess addressing specific modals in acceptance tests should be improved. If you have only one modal on your page `.modal` class could be used. But if there might be more than one, it gets really tricky.

Passing a `classNames` to `{{bs-modal}}` doesn't help cause this class is applied in place and not to modal element in wormhole container. A working approach is using a custom bs-modal block and setting `classNames` on a child element like `{{bs-modal-body}}` but this requires a lot of boilerplate code...

```hbs
// not addressable in testing
{{#bs-modal}}
  bar
{{/bs-modal}}

// addressable in testing
{{#bs-modal body=false}}
  {{#bs-modal-body classNames='custom-modal'}}
    bar
  {{/bs-modal-body}}
{{/bs-modal}}
```

**Comment by simonihmig** [comment]
What if you use the `id` for testing? The `bs-modal` component computes another id for the actual `.modal` element (the actual dialog inside the wormhole) which is just the own id with a `-modal` suffix. See https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-modal.js#L272-L274

```hsb
{{#bs-moda id="foo"l}}
  bar
{{/bs-modal}}
````

should give you a `<div class="modal" id="foo-modal">` element that you could target from your tests.

I have not tested this though, but it should hopefully behave like this...

**Comment by jelhan** [comment]
Yeah of course. So obvious. Sorry for disturbing.

**Comment by simonihmig** [comment]
Don't worry about it ;)
