### ISSUE TITLE
Deprecate @triggerElement="parentView" for Tooltips/Popovers

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#1220]
This relies on using Ember.Component's `parentView` here: https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-contextual-help.js#L252-L253

But this does not exist anymore for Glimmer components, so we should deprecate that asap. I hope it's not really used in the wild, I personally never did...

**Comment by jelhan** [comment]
Maybe I missed something but isn't `<BsTooltip @triggerElement="parentView">` the same as `<BsTooltip @triggerElement={{null}}>`?

**Comment by jelhan** [comment]
Oh I think I got it. `null` uses the parent element but `"parentView"` uses the element of the parent component.

So assuming this template:

```
<MyComponent>
  <button>
    <BsTooltip>
  </button>
</MyComponent>
```

If `@triggerElement={{null}}` the `<button>` will be used as the trigger element. If it's `@triggerElement="parentView"` it will be the element rendered by `<MyComponent>`. What will happen if `<MyComponent>` is a tagless component?

Nevertheless I'm fully agree that it should be deprecated.

**Comment by simonihmig** [comment]
> Oh I think I got it. null uses the parent element but "parentView" uses the element of the parent component.

Yeah. Doesn't make that much sense really, but was present since the very initial implementation I guess...

> What will happen if <MyComponent> is a tagless component?

💥
