### ISSUE TITLE
File using node 14 null coalescing operator breaks ember builds

### ISSUE THREAD

**Issue by DLiblik** [kaliber5/ember-bootstrap#1246]
Please see this line - this breaks the `ember-cli-terser` on node 12

https://github.com/kaliber5/ember-bootstrap/blob/master/addon/utils/cp/listen-to.js#L18

**Comment by jelhan** [comment]
Please include the error message you are facing. Are you using Fastboot?

**Comment by DLiblik** [comment]
We are and we have tracked it down to a dependency of `prember` on `fastboot@1.x` - it appears prember loads the last output of the broccoli tree which is not yet fully transpiled, so even using the babel `@babel/plugin-proposal-nullish-coalescing-operator` plug-in does not work.

We replaced the two components in this lib we were using and reverted to pure bootstrap to resolve this (since prember is not updating it seems), but you may wish to remove this single use of `??` to prevent the requirement to go to node 14+.

**Comment by DLiblik** [comment]
Further info: removing terser does not matter - it's prember's issue all the way.

**Comment by jelhan** [comment]
Are you sure that it's not the same issue as #1210?

**Comment by DLiblik** [comment]
Yes for sure - I did not investigate if fastboot 2 had fixed it or not.  Either way, to my knowledge that operator is the only thing standing between this project and full compatibility on node LTS (12) so it may be work the couple of keystrokes.  Certainly wound us around the axle for a while (to the point where we had to move off ember-bootstrap unfortunately as we cannot update node in our CI pipeline atm).

**Comment by jelhan** [comment]
> Either way, to my knowledge that operator is the only thing standing between this project and full compatibility on node LTS (12) so it may be worth the couple of keystrokes.

Babel should transpile the code to be compatible with the node version you are targeting. You may need to add it explicitly in your `config/target.js`. Please find more details on this one in #1210.

If adjusting the `config/target.js` does not fix the issue for you, please provide a reproduction.

**Comment by DLiblik** [comment]
Hi @jelhan, we did try that and it did not fix the issue.  At this point, we have dropped ember-bootstrap after having expended a fair amount of effort to try and work around this.  The effort to fix the source line of code above to not use `??` is a minute or two with no other impact, but I also recognize that this is only a stop-gap (hence us stepping back before the next one gets us even if this were to get changed).  We generally follow semantic versioning internally, and a change in a project like this one that creates a sudden dependency on a new version of node for us would be a breaking change (and it sure broke!) so at this point we are also a bit gun shy.

I recognize that this may not strike you as "the right way" from a purity of code perspective (sure, babel "should xyz" if we upgrade our CI pipeline, or downgrade our target browsers to trick the CI pipeline because fastboot "should" actually load the browser-packaged code but doesn't) but the reality is that we live in the space between "should" and "does" and right now we need "does" - this was a very unexpected side-effect for us.

**Comment by simonihmig** [comment]
@DLiblik could you please post your `config/target.js` here?

FWIW, I am using ember-bootstrap with both a real FastBoot server and prember, both under node 12, without any such problems, given the targets are correctly set up.

**Comment by DLiblik** [comment]
@simonihmig Sure thing - it's pretty tight - on purpose - but the targets here are, of course, browsers, not the CI pipeline itself.  FWIW, if we put a babel plugin to transform `??`, the output vendor.js is properly transformed, but fastboot's load of the module takes it from a broccoli output folder that is pre-transform and that's where the failure occurs.  That concerns us as well because it means the code being used by fastboot is not the same code being used in the target.  Of course it shouldn't matter, but, less variability makes for less risk.

Here's our `target.js`

```js
'use strict';

const browsers = [
  'last 1 Chrome versions',
  'last 1 Firefox versions',
  'last 1 Safari versions',
];

module.exports = {
  browsers,
};
```

**Comment by simonihmig** [comment]
Could you please try to tweak this as follows  (as suggested in https://github.com/kaliber5/ember-bootstrap/issues/1210#issuecomment-683972410), and see if it fixes the problem:

```diff
...

module.exports = {
+ node: true,
  browsers,
};
```

**Comment by DLiblik** [comment]
Hi @simonihmig yes that works.  We've pulled the module at this point, but good to know.  I looked at https://github.com/ember-fastboot/ember-cli-fastboot/pull/770 which describes putting that into `targets.js`, but where is that export prop of `targets.js` itself documented?  That would have been a nice tidbit of info to have...

**Comment by DLiblik** [comment]
Ah - right here - https://babeljs.io/docs/en/babel-preset-env#targetsnode - knowing to look at this however is where we certainly got stuck.

**Comment by simonihmig** [comment]
Good to hear it's working now!
