### ISSUE TITLE
bootstrap.js is included?

### ISSUE THREAD

**Issue by DDoSed** [kaliber5/ember-bootstrap#125]
Hello.
Please, tell me and specify in the doc wether bootstrap.js file included or not. And if not then how to inlude it better way? app.imort in ember-cli-build.js? 

And generally speaking its need to include that file?

I try to google how to check and what I find only confused me
```
typeof $().modal == 'function'
->false
typeof $().emulateTransitionEnd == 'function'
->true
```

Thanks.

**Comment by simonihmig** [comment]
No, bootstrap.js is not included, and it most cases it should not be. The primary intent of this addon is to provide native ember components that work without bootstrap.js. See the introduction at https://github.com/kaliber5/ember-bootstrap#ember-bootstrap.

You could however manually import bootstrap.js, exactly as you mentioned (`app.import` in `ember-cli-build.js`), however I cannot guarantee that everything will work together as expected.

**Comment by Caltor** [comment]
@simonihmig That explains why dropdowns don't work then. Could you make it an option (defaulted to off) to use bootstrap.js please? I'm not keen on using app.import as it creates a bower dependency.

**Comment by srvance** [comment]
> That explains why dropdowns don't work

@Caltor Can you explain what you mean by that? To the best of our knowledge, dropdowns should work. A code sample and the output of `ember bootstrap:info` would help.

**Comment by simonihmig** [comment]
I think @DDoSed assumed that dropdowns with same static markup, without using e-b's component for this, would just work, as it would in a normal server-rendered page with `bootstrap.js` included.

> Could you make it an option (defaulted to off) to use bootstrap.js please?

Sorry, but no. I don't want to support this, as it will create issues sooner than later. For example, `bootstrap.js` uses `setTimeout`, where in an Ember app you should use the run loop (with `Ember.run.later` instead). This *will* create issues, at least in acceptance tests, where the async test helpers do wait for pending run loops, but not `setTimeout`. Gone through this already... 

Afaik EmberCLI 2.15 will introduce the ability to directly `app.import` from `node_modules`, but there is also an addon for this, and you can still fall back to import it as a bower dependency.

But using `bootstrap.js` directly will still be at your own risk! ;)

**Comment by Caltor** [comment]
@simonihmig Yes you groked my meaning correctly. It's a while since I looked at this now but I was scratching my head for some time originally trying to figure out why bootstrap (non e-b) dropdowns weren't working.

Thanks for the consideration and explanation as to why you don't want to use bootstrap.js. Can I respectfully suggest that a section is added to http://www.ember-bootstrap.com/#/getting-started/assets explaining that bootstrap.js is not included please and maybe a brief reason why not. That page was/is the most logical place for me to look and there's no mention of it.

**Comment by simonihmig** [comment]
@Caltor yes, thanks for the suggestion, here is the tracking issue #330
