### ISSUE TITLE
Component DropdownButton gives subclassing deprecation

### ISSUE THREAD

**Issue by amauryt** [kaliber5/ember-bootstrap#1270]
The component `DropdownButton` directly extends from `Button` so it gives a deprecation with id `ember-bootstrap.subclassing#Button`. Perhaps it should set its `__ember-bootstrap_subclass` to true as does `FormElementLegend`?

Output from `ember bootstrap:info`:

```
ember-bootstrap: ^4.2.0 -> 4.2.0
ember-cli: ^3.16.1 -> 3.20.0
bootstrap: ^4.5.2 -> 4.5.2
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
blacklist: undefined
```

**Comment by simonihmig** [comment]
Hm, thanks for reporting!

Seems this was lost in the Glimmer refactoring: https://github.com/kaliber5/ember-bootstrap/commit/d209e281a3f52c63c62f1271c5e6f2e7270769a0#diff-c589e58a22ca7cf8ffd16fafe0533130

Wonder why this hasn't been catched in tests, which should make sure no deprecations are shown... 🤔
