### ISSUE TITLE
Can get event to fire on show.bs.dropdown

### ISSUE THREAD

**Issue by ianbale** [kaliber5/ember-bootstrap#128]
```
	{{#bs-dropdown class="insertQuestionDropdown"}}
		{{#bs-dropdown-button type="primary"}} Click me <span class="caret"></span>{{/bs-dropdown-button}}

		{{#bs-dropdown-menu class="scrollDropDown"}}

	          .... options here .....

		{{/bs-dropdown-menu}}

	{{/bs-dropdown}}
```

```
		Ember.run.scheduleOnce('afterRender',this,function()
		{
			$('.insertQuestionDropdown').on('show.bs.dropdown', function (e)
			{
			  Ember.Logger.log("showing dropdown!")
			});
		});
```

In the case above, I never get the "showing dropdown!" in the console. The dropdown has definitely been rendered when the event handler is setup. I've added debugging beforehand to confirm that the jQuery selector does return the enclosing DIV as expected. I've also confirmed that the enclosing DIV has the insertQuestionDropdown class. Everything looks like the examples on the bootstrap site.

Any ideas why this event is not firing?

**Comment by srvance** [comment]
Why do you think it should fire that event? It works using Ember actions, not DOM events, in the [DDAU](http://www.samselikoff.com/blog/data-down-actions-up/) pattern. What are you trying to accomplish? Can you put it in a [Twiddle](https://ember-twiddle.com)?

**Comment by simonihmig** [comment]
@srvance is right. Your are probably refering to the documentation of bootstrap.js, bootstrap's jQuery plugins. But ember-bootstrap is a _replacement_ for bootstrap.js' functionality, replacing the vanilla JS/jQuery with native ember components, so events etc. do not apply at all here. Have a look at the published API, when it is not listed there, it's not there! http://kaliber5.github.io/ember-bootstrap/api/
