### ISSUE TITLE
Conflict with ember-bootstrap-changeset-validations

### ISSUE THREAD

**Issue by BnitoBzh** [kaliber5/ember-bootstrap#1280]
Since ember-source@3.21.2 an assertion has been added on property decorated with `@dependentKeyCompat` if it has already been tracked or computed.

On ember bootstrap the `errors` property is computed through the `@defaultValue` decorator.
https://github.com/kaliber5/ember-bootstrap/blob/e25ed88a0c0c1e3c1493187a12bad30659f6d359/addon/components/bs-form/element.js#L382-L383

On ember-bootstrap-changeset-validations the `errors` property is computed through the `@dependentKeyCompat` decorator.
https://github.com/kaliber5/ember-bootstrap-changeset-validations/blob/3a8ed2915819c05eeb47ab01004a7a40e5343338/addon/components/bs-form/element.js#L20-L36

The assertion is fired on every forms that use changeset-validations.
If one of these decorator is removed, the assertion is fixed.

https://github.com/kaliber5/ember-bootstrap-changeset-validations/issues/33

**Comment by jelhan** [comment]
I _think_ refactoring `<Form::element>` to `@glimmer/component` and tracked properties is the best solution to address that problem. I _hope_ that the current API for validation plugins is still working afterwards. But I haven't explored that one in detail yet.

Pull requests refactoring `<Form::element>` as a glimmer component are highly welcome.

Please also note https://github.com/kaliber5/ember-bootstrap-changeset-validations/issues/33#issuecomment-723115120 for some additional context.

**Comment by jelhan** [comment]
@simonihmig This issue affects `ember-source@3.20.6`. So far it has only affected latest release. Now it's affecting current LTS as well. A quick fix would be removing `@defaultValue` decorator from `errors` property of `<BsForm::element>`. https://github.com/kaliber5/ember-bootstrap/blob/50937097944ad7c8a0504088628fc1972606bea4/addon/components/bs-form/element.js#L375-L383 Would you be okay with such a change as an interim solution until refactoring `<BsForm::element>` to glimmer component using tracked properties?

**Comment by jelhan** [comment]
This should be fixed in `ember-bootstrap-changeset-validations@v4`.
