### ISSUE TITLE
"You cannot set both property and value on a form element" – Exception?

### ISSUE THREAD

**Issue by danieledraganti** [kaliber5/ember-bootstrap#1291]
Hello,
I am opening this in reference to the #804 PR and the following warning: "You cannot set both property and value on a form element".
I just happened to stumble on this warning when debugging a strange behaviour on my app. I have the following template using both `ember-bootstrap` and `ember-power-select`:
```js
<form.element @property="subject" as |el|>
  <div class={{if el.validation (concat 'is-' (if (eq el.validation 'success') 'valid' 'invalid'))}}>
    <PowerSelect @options={{this.subjects}} @disabled={{or form.isSubmitting form.isSubmitted}} @selected={{el.value}} @placeholder={{t "contact.form.subjects.placeholder"}} @onChange={{action (mut el.value)}} as |item|>
      {{t (concat "contact.form.subjects." item)}}
    </PowerSelect>
  </div>
</form.element>
```
In this case, `ember-bootstrap` obviously can't bind the element value to the property, because the element is highly customised; on the other end, I want to keep the `@property` bound value of the `form.element` to pass to the `PowerSelect`, because it's part of a bigger form and I can keep the same logic throughout every element.
Suggestions on how I can reformat the code to avoid that blocking error on the `ember-bootstrap` side? Maybe the warning is a little too much on the safe side?

**Comment by jelhan** [comment]
You should use the yielded `setValue` function to mutate the value. It was introduced in #1203. Setting yielded `value` is not supported anymore.

**Comment by danieledraganti** [comment]
Missed that. It works now, thanks!
