### ISSUE TITLE
Dropdown does not join the button-group.

### ISSUE THREAD

**Issue by benedikt-d** [kaliber5/ember-bootstrap#13]
The drop down button stays seperated in the button group:

```html
<div class="input-group">
<div class="input-group-btn">
{{#bs-dropdown}}
{{#bs-dropdown-button}}Dropdown <span class="caret"></span>{{/bs-dropdown-button}}
{{#bs-dropdown-menu}}
<li>Something</li>
<li>Something different</li>
{{/bs-dropdown-menu}}
{{/bs-dropdown}}
</div>
{{bs-input value=foo  placeholder="foo"}}
</div>
```

There is one `<div>` to much in the result: 
`<div class="ember-view dropdown">`

**Comment by simonihmig** [comment]
Your example seems to work fine for me. Which version of the addon are your using? Please try with the latest!

**Comment by benedikt-d** [comment]
It does build the dropdown but it does not seem to work for me though with the latest version. Two Issues: The dropdown does not open when I click on it and also the css is not correct I think:

http://imgur.com/wS4naVl

**Comment by simonihmig** [comment]
I need to see a real example, not just a screenshot, e.g. on jsbin...

Two things:
1. the dropdown class is only applied if the dropdown toggle is not a button. Is that the case?
2. you can elimante the addition div by applying the input-group-btn class to the dropdown component itself: (NOT TESTED)

```html
<div class="input-group">
{{#bs-dropdown containerClass="input-group-btn"}}
{{#bs-dropdown-button}}Dropdown <span class="caret"></span>{{/bs-dropdown-button}}
{{#bs-dropdown-menu}}
<li>Something</li>
<li>Something different</li>
{{/bs-dropdown-menu}}
{{/bs-dropdown}}
{{bs-input value=foo  placeholder="foo"}}
</div>
```

**Comment by benedikt-d** [comment]
The dropdown toggle is a button.
Eliminating the div by applying the input-group-btn class worked well.

**Comment by benedikt-d** [comment]
updating to the latest version fixed the issue without the additional class

**Comment by simonihmig** [comment]
@benedikt-d Great, thanks for your feedback!
