### ISSUE TITLE
autofocus is not working as expected

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#130]
`autofocus` is not working as expected. Has been reported as a bug in November 2015 but was closed as unfixable: https://github.com/emberjs/ember.js/issues/12589 Should we address this in ember-bootstrap?

HTML5 spec only addresses handling of `autofocus` on document load:

> Note: This handles the automatic focusing during document load.
> https://www.w3.org/TR/html5/forms.html#autofocusing-a-form-control:-the-autofocus-attribute

I see three possibilities:
- Just add this to docs.
- Remove not working `autofocus` property.
- Add a work-a-round to fix it.

A possible work-a-round would be (not tested yet):

``` js
// in ember-bootstrap/addon/components/bs-input.js
autofocus: on('didInsertElement', function() {
  if (this.get('autofocus')) {
    this.$().focus();
  }
});
```

**Comment by simonihmig** [comment]
You are certainly right about this. Actually this property was introduced in a different context, for the `bs-modal` component, by https://github.com/kaliber5/ember-bootstrap/pull/60. I guess adding this to the documentation makes sense. I am not so sure about adding a work-around, introducing a different behavior that what the specs say...

**Comment by lbmeira** [comment]
I had a similar issue, and in addition to this work-around I had to specify the class name within "this.$().focus()" to get it to work:
`this.$('input').focus();`

**Comment by simonihmig** [comment]
Closing this as there is no global `bs-input` anymore
