### ISSUE TITLE
Your FastBoot test code is great, can we pull it out into an addon?

### ISSUE THREAD

**Issue by taras** [kaliber5/ember-bootstrap#131]
I think it's be helpful for anyone using fastboot.

Would you be open to pulling into an addon and consuming the addon in your app instead?

**Comment by simonihmig** [comment]
Hi @taras, thanks for the feedback. Sure would be open for that, given I find the time for it. 

Have not thought much about it yet. What functionality do you have in mind? 

Currently the given testing code is only applicable to addons, not apps actually. And most functionality comes from `ember-cli-addon-tests`. The only reusable code is probably https://github.com/kaliber5/ember-bootstrap/blob/master/fastboot-tests/module.js. Besides that the addon could maybe set some things up like some boilerplate stuff to get things started, through the use of blueprints. 

Or any other ideas?

**Comment by simonihmig** [comment]
You got me inspired, started working on this! :)

Will try to pull something together over here: https://github.com/kaliber5/ember-fastboot-addon-tests. 

Closing this. Feel free to track/give feedback/contribute at the other repo! :)

**Comment by taras** [comment]
Sorry, I didn't get back to you earlier. You did exactly what I had in mind, but I also found this https://github.com/tomdale/ember-cli-addon-tests

**Comment by simonihmig** [comment]
No problem. Actually I was already using this addon! :) It was the base I built upon, but its intend is more general (not explicitly for Fastboot, and does not add testing support). So this new thing still makes sense!

**Comment by taras** [comment]
awesome :)
