### ISSUE TITLE
Customize bootstrap with variables?

### ISSUE THREAD

**Issue by mmahalwy** [kaliber5/ember-bootstrap#134]
Is there a way to have a file with all the variables that gets loaded before bootstrap?

**Comment by simonihmig** [comment]
I am sorry, but I do not understand your question. What kind of variables are you referring to?

**Comment by mmahalwy** [comment]
@simonihmig see:
http://getbootstrap.com/customize/

example with bootstrap-sass:
https://github.com/twbs/bootstrap-sass#sass-1

**Comment by simonihmig** [comment]
Ok, I see... this should be easy. You will have to install the css preprocessor addon you want to use, e.g. `ember-cli-less`, if you have not done so already.

Then you have to opt out of including the static bootstrap CSS, and instead import the bootstrap less/sass files and set your variables. See http://kaliber5.github.io/ember-bootstrap/getting-started/

There is direct support for less, as bootstrap ships with it. See the last chapter in the Getting Started Guide. To use Sass you would have to use Sass-port your already linked to.

**Comment by mmahalwy** [comment]
Ah makes sense. Thanks @simonihmig
