### ISSUE TITLE
It is necessary to manually set focus on the modal backdrop when dynamically rendering a BsModal

### ISSUE THREAD

**Issue by kboucher** [kaliber5/ember-bootstrap#1362]
The native Bootstrap modal component places focus on the modal backdrop when opening a modal dialog. The `BsModal` component does the same thing, but only when it is statically rendered.

To reproduce:

1. Place a minimal `BsModal` component in your markup (with focusable elements in the content)
2. Load the page (modal will be displayed by default)
3. Press tab (note that focus moves immediately into the modal content)

This is because Bootstrap places focus on the `.modal` (backdrop) element after opening.

Now, add either an `{{#if this.showModal}}` block or use the `@open={{this.showModal}}` attribute, and wire up a trigger.

Click the trigger, observe the modal opens, but the focus remains on the trigger.

Focus does remain trapped in the modal (as expected) once you've tabbed into it, but it would be nice if it was not necessary to manually set focus to the backdrop using `@onShown={{<FOCUS_METHOD_HERE>}}`.

---

The output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^4.4.0 -> 4.4.0
ember-cli: ~3.22.0 -> 3.22.0
bootstrap: ^4.5.3 -> 4.5.3
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: true
```

**Comment by simonihmig** [comment]
Thanks for reporting, something seems indeed wrong. Strange since I thought we had pretty decent test coverage added when focus trapping was implemented.

**Comment by simonihmig** [comment]
It turned out, the issue was present both when the modal is rendered statically as well as dynamically, so unrelated to that!

> Strange since I thought we had pretty decent test coverage added when focus trapping was implemented.

Actually this was not covered unfortunately. I am pretty sure it worked initially, but a later change probably broke this, undetected by CI.

#1370 should fix this.

**Comment by kboucher** [comment]
@simonihmig Thanks so much for this fix!
