### ISSUE TITLE
Carousel coming soon? 

### ISSUE THREAD

**Issue by mmahalwy** [kaliber5/ember-bootstrap#138]

**Comment by simonihmig** [comment]
I have some first implementation, but it is too early to publish. Cannot tell you a date, as this is all happening in my spare time...

**Comment by c410-f3r** [comment]
Is anyone working on this issue? If not, I could put some effort to make this feature since it is highly desirable to me.

**Comment by jelhan** [comment]
I'm also interested in this feature and willing to help out.

**Comment by Techn1x** [comment]
I've reached a point in my project as well where I could use a carousel implementation - happy to help test it out when they code is ready :)

**Comment by simonihmig** [comment]
Fyi, we are getting close, thanks to @c410-f3r: #375

**Comment by Techn1x** [comment]
Fantastic! I've been using the standard bootstrap js for carousel and it's super annoying, can't wait for the ember implementation! :)

**Comment by simonihmig** [comment]
Btw, #522 has been merged! 🎉

Scheduled for release soon! Give @c410-f3r a huge thanks! :)
