### ISSUE TITLE
Unable to do clean install on Ember-cli 2.8.0

### ISSUE THREAD

**Issue by hcderaad** [kaliber5/ember-bootstrap#139]
When trying to install a ember-bootstrap on a clean Ember 2.8.0 test app the ember install command fails at the bootstrap installation.
 
```
Installed packages for tooling via npm.
installing ember-bootstrap
  install bower package bootstrap
  cached https://github.com/twbs/bootstrap.git#3.3.7
  cached https://github.com/twbs/bootstrap.git#3.3.7
  cached https://github.com/twbs/bootstrap.git#3.3.7
  cached https://github.com/twbs/bootstrap.git#3.3.7
  cached https://github.com/twbs/bootstrap.git#3.3.2
  cached https://github.com/twbs/bootstrap.git#3.1.1
  cached https://github.com/twbs/bootstrap.git#3.0.0
  conflict Unable to find suitable version for bootstrap
    1) bootstrap 3.0.0
    2) bootstrap ~3.1.1
    3) bootstrap 3.3.2
    4) bootstrap ^3.3.7
    5) bootstrap >=2
    6) bootstrap >= 2.3.2
    7) bootstrap >= 3.0.1
    8) bootstrap ~3.3.5
? Answer 4
```
After providing a (seemingly sensible, or actually any) answer, the installation just stops. Installing bootstrap through bower install bootstrap works.
Is there anything to debug on this?

**Comment by simonihmig** [comment]
Have you tried `bower cache clean` before? Seems you have some bower versions cached coming directly from github there. Do not know why you have some issue there, cannot reproduce...

**Comment by hcderaad** [comment]
Thanks for responding! Nevermind, this seems to be a collision with ember-dynamic-forms, possibly/probably related to https://github.com/toddjordan/ember-cli-dynamic-forms/issues/44
I'm closing this issue as it appears to be non ember-bootstrap related.
