### ISSUE TITLE
Q: How to use a dynamic property path

### ISSUE THREAD

**Issue by basz** [kaliber5/ember-bootstrap#142]
[From](http://kaliber5.github.io/ember-bootstrap/api/classes/Components.Form.html):
When using Components.FormElements with their property set to property names of the form's validation enabled model, you gain some additional powerful features:

- the appropriate Bootstrap markup for the given formLayout and the form element's controlType is automatically generated
- markup for validation states and error messages is generated based on the model's validation (if available), when submitting the form with an invalid validation, or when focusing out of invalid inputs

```
{{#bs-form formLayout="horizontal" model=this action="submit"}}
  {{bs-form-element controlType="email" label="Email" placeholder="Email" property="email"}}
  {{bs-form-element controlType="password" label="Password" placeholder="Password" property="password"}}
  {{bs-form-element controlType="checkbox" label="Remember me" property="rememberMe"}}
  {{bs-button defaultText="Submit" type="primary" buttonType="submit"}}
{{/bs-form}}
```

So when I have a template that generates form-element through a loop (`model.phoneNumbers` is an array) how would I reference an property path that contains an index?

```
property="model.phoneNumbers[index]"
```

```
{{#bs-form formLayout="vertical" model=model action="submit" disabled=isProcessing}}
    {{#each model.phoneNumbers as |component|}}
        {{bs-form-element controlType="input" placeholder="phonenumber" property="????" disabled=isProcessing showValidation=true}}
    {{/each}}
{{/bs-form}}
```

**Comment by simonihmig** [comment]
Hm, as there is no way in Ember to specify a property path accessing an array item given its index, I currently see no easy solution there, unfortunately. 

But I am just wondering, how did you define the validations on the individual array items in the first place? Using what validation library? Can you give an example?

**Comment by basz** [comment]
Hi, I'm using ember-cp-validations and someone told me how to do this... :-)

This is what we want;
```
property="phoneNumbers.0.number"
```
Which can be done dynamically via
```
{{#bs-form formLayout="vertical" model=model action="submit" disabled=isProcessing}}
    {{#each model.phoneNumbers as |component index|}}
        {{bs-form-element controlType="input" placeholder="phonenumber" property=(concat 'phoneNumbers.' index '.number') disabled=isProcessing showValidation=true}}
    {{/each}}
{{/bs-form}}
```

Assuming phoneNumbers are objects with a `number` property

**Comment by simonihmig** [comment]
Again, Ember does not support accessing array items in a property path, so I am sorry to say that this case does not seem to be supported, and have no idea how ember-bootstrap could work around this unfortunately! Closing this for now...
