### ISSUE TITLE
`onShow` action is not called when controlling bs-popover visibility programmatically

### ISSUE THREAD

**Issue by silhusk** [kaliber5/ember-bootstrap#1438]
`onShow`, `onShown` are not executed when controlling bs-popover visibility through the `visible` property.
Also `ContextualHelp._show()` is not executed. This means that workarounds for touch devices, hover state and transition are not applied.

I would expect the actions to be called also when controlling the bs-popover component programmatically. The same as when triggered by an event. (It did work before glimmer, anyway)

I think the cause is that `@visible` is passed on directly to popper as `@showHelp`.

Workaround
----
```hbs
<BsPopover @visible={{@visible}}>
  <!-- ... -->
  {{#if @visible}}
    {{did-insert this.onShow}}
  {{/if}}
</BsPopover>
```

bootstrap:info
----
Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^4.3.0 -> 4.6.3
ember-cli: ~3.25.0 -> 3.25.0
bootstrap: ^4.5.3 -> 4.6.0
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
Thanks for reporting. Unfortunately we suffered from similar issues on other components during the Glimmer refactoring, which were not covered by tests unfortunately. Will need to investigate...
