### ISSUE TITLE
tooltip container option

### ISSUE THREAD

**Issue by nruth** [kaliber5/ember-bootstrap#145]
Bootstrap allows setting the [tooltip container](http://getbootstrap.com/javascript/#tooltips-options) to "body", which according to our designer helps with some issues regarding tooltips changing component/container sizes when toggled. 

We can't see an option for this here, and when the tooltip is triggered it moves around a bunch of unrelated page elements because the tooltip is wider than the button triggering it.

Is this something that could be supported?

**Comment by simonihmig** [comment]
By default tooltips use [ember-wormhole] to inject its HTML into a different place than where they are declared in the template. They are put inside of the `#ember-bootstrap-modal-container` div that is being generated for you by ember-bootstrap at the `rootElement` (by default "body") of the ember app. So basically it should be working like you suggested by default!

Did you do anything special, like using the `insertEmberWormholeElementToDom` flag in your build config?
