### ISSUE TITLE
hasBlock deprecation

### ISSUE THREAD

**Issue by cah-briangantzler** [kaliber5/ember-bootstrap#1467]
Several of the components use hasBlock and need to be changed to (has-block)

**Comment by jelhan** [comment]
Thanks a lot for reporting. Currently lacking a little bit resources to address all outstanding tasks. Especially Octane migration is eating up a lot of time. Would be great if you could provide a pull request to address the deprecation.

**Comment by cah-briangantzler** [comment]
Sure. Have reported issue in several addons, working my way through the PRs.   :)

**Comment by cah-briangantzler** [comment]
Fixed via https://github.com/kaliber5/ember-bootstrap/pull/1468
