### ISSUE TITLE
Form element does not disable validation icons if setting @hasIcons to false in BS4

### ISSUE THREAD

**Issue by bvedad** [kaliber5/ember-bootstrap#1589]
**Steps for reproduction:**
A form element rendered with @hasIcons={{false}} does not disable validation icons. The code we are using is a modified version of file `tests/dummy/app/templates/fastboot/forms.hbs`. We have only added `@customError='Lorem ipsum'`, `@useIcons={{false}}` to form.element and `@validationType='error'` to el.control:
```
<BsForm @model={{this}} as |form|>
  <form.element
      @useIcons={{false}}
      @controlType='email'
      @label='Email'
      @placeholder='Email'
      @property='email'
      @required={{true}}
      @customError='Lorem ipsum'
      @useIcons={{false}}
      as |el|
    >
    <el.control @validationType='error' />
   </form.element>
  <BsButton @defaultText='Submit' @type='primary' @buttonType='submit' />
</BsForm>
```

**Problem:**
The problem is that `useIcons` is not used anywhere except on `hasFeedback` getter in `bs-form/group.js` file. And `hasFeedback` is only used in `bs-form/element.hbs` and `bs-form/group.hbs` files only if we are using BS3 to apply `has-feedback` class in every file. In other words, `@hasIcons` argument is useless unless we use BS3.

**Potential solution:**
The only way I found to disable it for BS4 would be one I found [here](https://newbedev.com/remove-bootstrap-s-validation-icons). It is by having a custom CSS class and if we are using BS4 adding that class to the element which has `@useIcons={{false}}` set. The class should look something like this:
```
.form-control.is-invalid{
    background-image: none;
}
```

If anybody has a better idea of how to disable validation icons for BS4 please write it in this issue.

**Comment by jelhan** [comment]
This seems to be a documentation issue. `@useIcons` is only supported for Bootstrap 3. But that limitation is only [documented for `<BsForm::Group>`](https://www.ember-bootstrap.com/api/classes/Components.FormGroup.html#property_useIcons) not for [`<BsForm::Element>`](https://www.ember-bootstrap.com/api/classes/Components.FormElement.html#property_useIcons).
