### ISSUE TITLE
bs-alert dismiss

### ISSUE THREAD

**Issue by trapias** [kaliber5/ember-bootstrap#16]
Hello,
I'm new to Ember, so please forgive what is probably a silly question. I'm using a bs-alert on a login form to display an eventual error message, in case user fails to login.

If user dismisses the alert by clicking its "close" button, and then fails again to login, the alert does not show anymore. I think I should somehow reset the control when he tries to login, but cannot understand how to do this: could you please help?

Thanks,
al.

**Comment by simonihmig** [comment]
Apparently you are somehow reusing the existing (now dismissed) alert component for a new message, which is the root of the problem. If you are displaying a new message to the user, this should be a new component instance as well. As soon as the user resubmits the form, the old messages should disappear anyway, especially if the user did not dismiss it by himself, the old messages should not stay there.

Say you have an array of error messages. You iterate over the array in your template and create alerts out of them (Code not tested):
```hbs
{{#each messages as |message|}}
{{#bs-alert type="danger"}}{{message}}{{/bs-alert}}
{{/each}}
```

In the controller action that handles the form submission, reset the error messages before sending your AJAX request or whatever:
```js
this.set('messages',[]);
```

This will destroy the alert components, so they loose their state. When a new error message is shown by adding it to the messages array, a new component instance is created, that does not have any connection to old one, so it will show up.

Hope that helped!

**Comment by trapias** [comment]
@simonihmig yeah thank you, I'm so new to Ember! Will study more before asking again :blush:

**Comment by Redsandro** [comment]
@simonihmig I know this is old, but this was exactly my issue/misunderstanding.

However, `this.set('messages',[])` causes the errors to disappear immediately rather than fade out. How would one gracefully hide and re-use an alert?
