### ISSUE TITLE
How to control width of ONE tooltip?

### ISSUE THREAD

**Issue by rstudner** [kaliber5/ember-bootstrap#161]
I can do:
```
.tooltip-inner {
  max-width: 500px
}
```
in my app.scss for ALL tooltips.

But how can I control the width of ONE tooltip?

**Comment by simonihmig** [comment]
You could assign an individual class and use that as a CSS selector. See https://guides.emberjs.com/v2.9.0/components/customizing-a-components-element/#toc_customizing-the-element-s-class

**Comment by rstudner** [comment]
Oh, then I must have just botched it hah. I thought I tried that first and the class didn't get applied.  I'll try again :)

**Comment by simonihmig** [comment]
Oh, yeah, I guess you are right... should have thought about it a little bit more. The tooltip is inserted at some other place in the DOM through ember-wormhole, therefore this won't work. 

This needs some changes in code, will make this a feature request. Should be pretty easy to add...
