### ISSUE TITLE
BsModal @open should not treat falsy values as truthy

### ISSUE THREAD

**Issue by lolmaus** [kaliber5/ember-bootstrap#1612]
`ember-bootstrap` v4.9.0.

[Here](https://github.com/kaliber5/ember-bootstrap/commit/1bf4cf7aa2fe9aefa4e618b601877e1d4b0b5843#diff-e071449aeb5436c622964ec59e95bbb45deb6552acca75046b8f29f479d263bbR688) `@open` logic was changed and some apps broke.

This is not technically a bug, since `@open` is documented as boolean.

But:

1. Passing a record as a property is convenient.
2. I expect null to be treated as falsy. This is what most libs do.
3. I believe, there may be many cases in ember-bootstrap where null is treated as falsy. Thus, strictly requiring a boolean is kinda inconsistent.
4. A truthy non-boolean value sitll works. Only falsy doesn't.

**Comment by bryanhickerson** [comment]
Any chance this could be back-ported to the 4.x series? This issue actually breaks a lot of modals in my app and we're currently on bootstrap 3, so it's unclear when I'll be able to upgrade to 5.0.

**Comment by simonihmig** [comment]
@bryanhickerson I don't think we will actively maintain the v4 series, but I am not opposed to releasing updates when receiving bug fix PRs. There is a `dev-v4` branch, so when you want to contribute that fix, then the (quite minimal) changes of https://github.com/kaliber5/ember-bootstrap/pull/1720 just need to be applied to that branch!

**Comment by jelhan** [comment]
> @bryanhickerson I don't think we will actively maintain the v4 series, but I am not opposed to releasing updates when receiving bug fix PRs. There is a `dev-v4` branch, so when you want to contribute that fix, then the (quite minimal) changes of #1720 just need to be applied to that branch!

I think it wouldn't be a breaking change as only boolean values are documented as public API. But this issue shows that it is used with other values in practice. I fear changing it in a minor release may break some applications.

**Comment by bryanhickerson** [comment]
> > @bryanhickerson I don't think we will actively maintain the v4 series, but I am not opposed to releasing updates when receiving bug fix PRs. There is a `dev-v4` branch, so when you want to contribute that fix, then the (quite minimal) changes of #1720 just need to be applied to that branch!
> 
> I think it wouldn't be a breaking change as only boolean values are documented as public API. But this issue shows that it is used with other values in practice. I fear changing it in a minor release may break some applications.

Changing it in a minor release did break it in my application 😄. It was very common in my app to not set an initial value for the `@open` property and then have a button on the page that set the value to on.

**Comment by bryanhickerson** [comment]
Thanks for pointing out the dev branch, if I have time I'll take a look at back porting as updating a significant number of modals in my app was a lot longer.

**Comment by bryanhickerson** [comment]
In digging more, my issue is actually this change in 4.4.0: https://github.com/kaliber5/ember-bootstrap/commit/33d4456baee518a9d9d7a50986cbd417c7796da7, so I'll have to think more about the appropriate migration path for my app.
