### ISSUE TITLE
bs-modal handling more than one open modal

### ISSUE THREAD

**Issue by ajball** [kaliber5/ember-bootstrap#1621]
We've run into an issue where `bs-modal` does not intelligently handle closing a modal when another modal is also open and in the DOM. The crux of the issue lies in `removeBodyClass()` which is called when a modal closes:

```
  removeBodyClass() {
    // no need for FastBoot support here
    document.body.classList.remove('modal-open');
  }
```

Removing `.modal-open` from the body element's class list removes the `overflow: hidden` rule applied to the 2nd modal that is still open and introduces scrolling issues.

As a temporary workaround, we are extending `BsModal` and overriding the base implementation of `removeBodyClass()` to look like:

```
export default class BsModal extends BsModalExtend {
  removeBodyClass() {
    super.removeBodyClass();
    schedule('afterRender', this, () => {
      const modals = document.getElementsByClassName('modal');
      if (modals.length > 0) {
        document.body.classList.add('modal-open');
      }
    });
  }
}
```

Ideally we'd like to stop extending the base implementation of `BsModal` as soon as possible, so I would like to know if there are any plans to address the issue I've described here.

I'm happy to pitch in and fix the issue myself but would need some direction from the repo's maintainers on what a final, prod-ready solution should look like.

Thanks for your attention here

Output from `ember bootstrap:info`:

```
  Npm packages:
  ember-bootstrap: ^4.6.3 -> 4.6.3
  ember-cli: ~3.25.0 -> 3.25.3
  bootstrap: ^4.6.0 -> 4.6.0
  bootstrap-sass: n/a
  ember-cli-sass: ^10.0.1 -> 10.0.1
  ember-cli-less: n/a

  Bower packages:
  bootstrap: n/a
  bootstrap-sass: n/a

  ember-bootstrap configuration:
  bootstrapVersion: 4
  importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
We haven't supported this as Bootstrap itself [clearly states](https://getbootstrap.com/docs/5.1/components/modal/):

> Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

I have recently used [https://github.com/PrecisionNutrition/ember-body-scroll-lock](https://github.com/PrecisionNutrition/ember-body-scroll-lock) for this use case (not Bootstrap related), so we could introduce that, which would fix this issue for you. However be aware that the use of multiple modals would still not be considered supported!

**Comment by ajball** [comment]
Thanks @simonihmig, figured that was the case. Will take a closer look at that library as well - looks like it'll do the trick.
