### ISSUE TITLE
Testing ember-bootstrap components should be documented

### ISSUE THREAD

**Issue by ykaragol** [kaliber5/ember-bootstrap#165]
How to be tested a component that uses modal? 
"ember-wormhole failed to render into '#ember-bootstrap-modal-container' because the element is not in the DOM" error raised when that component is tested.

**Comment by simonihmig** [comment]
Which version are you using? The latest should not trigger that error if `#ember-bootstrap-modal-container` is missing (created by an initializer, but that is not executed in component integration tests). 

See also the integration tests in this addon, these are running fine...

**Comment by ykaragol** [comment]
Yes, my version was 0.6.0. No problem with 0.11.2. 
Thank you.
