### ISSUE TITLE
Form action="registerUser" as |formValues|

### ISSUE THREAD

**Issue by absemetov** [kaliber5/ember-bootstrap#166]
How to  add dynamic property in action form?

**Comment by simonihmig** [comment]
Please provide more information, it is not clear to me what you want to achieve!

**Comment by absemetov** [comment]
Like this
````
{{#simple-form onsubmit="registerUser" as |formValues|}}
  {{input value=formValues.email placeholder="Email"}}
  {{input type="password" value=formValues.password placeholder="Password"}}

  {{input value=formValues.firstName placeholder="First Name"}}
  {{input value=formValues.lastName placeholder="Last Name"}}

  <button>Submit</button>
{{/simple-form}}
````

**Comment by simonihmig** [comment]
What is `{{simple-form}}`? This is not part of ember-bootstrap!?

**Comment by absemetov** [comment]
This is some component. 
How send some data in action (as |formValues|)?

**Comment by simonihmig** [comment]
Sorry, but I cannot see any relation to ember-bootstrap here. I cannot provide general ember support here. See http://emberjs.com/community/ for general support forums. Closing this.
