### ISSUE TITLE
if `link-to` is placed inside `bs-button-group` it is always active

### ISSUE THREAD

**Issue by mpugach** [kaliber5/ember-bootstrap#170]
Hello

I see this behaviour. Is it a bug?

**Comment by simonihmig** [comment]
Yes, it seem you are right. While this is not intended an could be regarded as a bug, I wonder is there a legit reason to put a link into a button group? I was assuming that only buttons may be children of a button group.

**Comment by mpugach** [comment]
Is this advised in Bootstrap documentation?

**Comment by simonihmig** [comment]
No, but Bootstrap does not have any special handling of button groups like ember-bootstrap has (as the group itself has a value, based on the type (e.g. radio). This makes only sense for real buttons, I cannot imagine why to put a link in there.

If you just want to apply the button group styling to some links, you can use the simple bootstrap classes without any components:

```hbs
<div class="btn-group">
{{#link-to "something" class="btn"}}Link{{/link-to}}
</div>
```

**Comment by mpugach** [comment]
Ok, thanks
