### ISSUE TITLE
Ember how to change Ember boostrap Tooltip background color

### ISSUE THREAD

**Issue by Abderazak-Amiar** [kaliber5/ember-bootstrap#1724]
Currently I'm using Ember Bootstrap Tooltip component, I read the doc, I didn't found anything about custom Background-color. It will be helpful if you will add @color.

**Comment by simonihmig** [comment]
You don't apply any styling via JS, you customize the BS components as you would for any other Bootstrap-based project. If using plain CSS (not recommended), you would need to override the default styles using CSS, If using Sass (recommended!), you can just tweak the related Sass variables. See https://getbootstrap.com/docs/5.1/components/tooltips/#variables (this is BS v5)
