### ISSUE TITLE
Value on model is not set if value is not undefined

### ISSUE THREAD

**Issue by web-melt** [kaliber5/ember-bootstrap#173]
Hi, 
whenever a bs-form-element with a preset value from a models attribute is used the change of the input doesn't trigger a model change.

Example:
`{{bs-form-element controlType="text" value=model.lastname}}`

When model.lastname is undefined typing into the input updates the models `lastname` property
When model.lastname is "foo" changing the inputs value doesn't update the models `lastname` property

Is this expected behaviour or a bug?

Thanks in advance.

**Comment by simonihmig** [comment]
I just checked this, and this is working fine for me!?

Please check this again. Also, is it working when using a simple `{{input value=model.lastname}}`?

**Comment by web-melt** [comment]
Hi,

yes it's working fine with `{{input value=model.lastname}}` an with `{{bs-input value=model.lastname}}`

I'll set up a demo outlining the issue tomorrow.

Thanks for the response.

**Comment by web-melt** [comment]
Okay I have to apologize. On a minimal, clean project this bug does not occur, therefore chances are
it's due to another part of our project.

Sorry for the report and thanks for answering so soon.

**Comment by simonihmig** [comment]
Don't mind, thanks for letting me now!
