### ISSUE TITLE
BsPopover throwing exception in @popper/core in ember-bootstrap 5

### ISSUE THREAD

**Issue by lupestro** [kaliber5/ember-bootstrap#1767]
We have a single use of `<BsPopover>` in our app, and when we render it in ember-bootstrap 5, we get an error from @popover/core/lib. 

I'm not at all sure how to troubleshoot from here, but here's what I've got. With a little guidance, I'm willing to do some legwork. Getting this working is the only impediment that we have encountered to getting the application building and running in Ember 4.x.

Here's the use:
```hbs
<CustomSelect
    id="selectedGainInput"
    @optionClasses="hiddenOption"
    @options={{@selectedPart.gainInputs}}
    @fieldId="selectedPart.selectedGainInput"
    @selectedValue={{@selectedPart.selectedGainInput}}
    @updateField={{this.selectedGainChanged}}
/>
<BsPopover
    @triggerElement="#selectedGainInput"
    @placement="below" as |popover|
>
    <div id="gainStagesContainer">
        ... what shows up in the popover ...
    </div>
</BsPopover>
```
The `<CustomSelect>` is just a `<select ...attributes><option/>...</select>` arrangement. The error remains if we reduce the contents of the popover to an empty `<div>`, so it doesn't appear that anything inside the popover is involved. 

Here's the exception:
```none
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'x')
    at offset (offset.js:9:1079)
    at Object.forceUpdate (createPopper.js:45:635)
    at eval (createPopper.js:47:129)
    at new Promise (<anonymous>)
    at eval (createPopper.js:47:90)
    at eval (debounce.js:5:164)
```

The function that fails is:
```javascript
var _enums_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../enums.js */
"./node_modules/@popperjs/core/lib/enums.js");

function offset(_ref2) {
    var state = _ref2.state
      , options = _ref2.options
      , name = _ref2.name;
    var _options$offset = options.offset
      , offset = _options$offset === void 0 ? [0, 0] : _options$offset;
    var data = _enums_js__WEBPACK_IMPORTED_MODULE_1__.placements.reduce(function(acc, placement) {
        acc[placement] = distanceAndSkiddingToXY(placement, state.rects, offset);
        return acc;
    }, {});
    var _data$state$placement = data[state.placement]
      , x = _data$state$placement.x
      , y = _data$state$placement.y;
    if (state.modifiersData.popperOffsets != null) {
        state.modifiersData.popperOffsets.x += x;
        state.modifiersData.popperOffsets.y += y;
    }
    state.modifiersData[name] = data;
}
```
And the line that fails is the `x = _data$state$placement.x`, so somehow the data[state.placement] is coming up empty.

Here's the relevant module info from yarn.lock:
```none
"@popperjs/core@^2.4.2":
  version "2.11.2"
  resolved "https://registry.yarnpkg.com/@popperjs/core/-/core-2.11.2.tgz#830beaec4b4091a9e9398ac50f865ddea52186b9"
  integrity sha512-92FRmppjjqz29VMJ2dn+xdyXZBrMlE42AV6Kq6BwjWV7CNUW1hs2FtxSNLQE+gJhaZ6AAmYuO9y8dshhcBl7vA==
```

Our ember-cli-build has the configuration section:
```none
    'ember-bootstrap': {
      bootstrapVersion: 4,
      importBootstrapFont: false,
      importBootstrapCSS: false,
      whitelist: ['bs-popover', 'bs-contextual-help', 'bs-tooltip'],
    },
```

Because the application is using slickgrid for tables, it also imports jquery-ui and bootstrap.js (for our sins):
```
  app.import('node_modules/bootstrap/dist/js/bootstrap.js');
  app.import('node_modules/jquery-ui/ui/version.js');
  app.import('node_modules/jquery-ui/ui/data.js');
  app.import('node_modules/jquery-ui/ui/ie.js');
  app.import('node_modules/jquery-ui/ui/scroll-parent.js');
  app.import('node_modules/jquery-ui/ui/widget.js');
  app.import('node_modules/jquery-ui/ui/widgets/mouse.js');
  app.import('node_modules/jquery-ui/ui/widgets/sortable.js');
  app.import('node_modules/slickgrid/lib/jquery.event.drag-2.3.0.js');
  app.import('node_modules/slickgrid/slick.core.js');
  app.import('node_modules/slickgrid/plugins/slick.rowselectionmodel.js');
  app.import('node_modules/slickgrid/slick.grid.js');
  app.import('node_modules/slickgrid/slick.dataview.js');
  app.import('node_modules/slickgrid/slick.grid.css');
  app.import('node_modules/bootstrap/dist/css/bootstrap.css');
```
(We hope to be able to reduce this to just the CSS one day.)

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^5.0.0 -> 5.0.0
ember-cli: ~3.24.0 -> 3.24.0
bootstrap: ^4.5.2 -> 4.6.1
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
whitelist: undefined

```

**Comment by simonihmig** [comment]
Thanks for the extensive report @lupestro! 

I believe your popover invocation is wrong, should be like this:

```diff
<BsPopover
    @triggerElement="#selectedGainInput"
-    @placement="below" as |popover|
+    @placement="bottom" as |popover|
>
```

But the API for this hasn't changed. Only top, bottom, left and right are supported values (see the API docs). Maybe it worked by coincidence previously, as this was passed to popper.js v1 in ember-bootstrap 4.x. But starting with 5.0 we use v2 of popper, which might explain why `below` stopped working.

**Comment by lupestro** [comment]
Many thanks! I fixed the string and it is all working now. Our app is now completely working in Ember 4.2 and I’m ecstatic.

Oddly, that parameter had always been wrong like that and we never noticed. Doing what we expected must have been inadvertent fallback behavior in the old implementation for an invalid value, so the issue wasn’t called to our attention.

Given how obscure the actual failure is, it would have been really helpful if a little code in bs-popover or in the modifier gave some kind of error with a good message if the placement value is invalid rather than bombing out like that. I’ll leave this open in case you want to do something about that. If not, feel free to close the issue.

thanks again.

**Comment by jelhan** [comment]
> Given how obscure the actual failure is, it would have been really helpful if a little code in bs-popover or in the modifier gave some kind of error with a good message if the placement value is invalid rather than bombing out like that.

I fully agree. I hope we can soon address this by providing types. [RFC Glimmer component signature](https://github.com/emberjs/rfcs/pull/748) and the tooling I expect to be build on top of it, should enable that.

**Comment by simonihmig** [comment]
> I hope we can soon address this by providing types. https://github.com/emberjs/rfcs/pull/748 and the tooling I expect to be build on top of it, should enable that.

I agree. Glint is getting pretty awesome! And I would not want to add runtime code (even when stripped in prod) to every place where we could validate arguments, I think that's hardly maintainable...

So I'll close this one, and refer to https://github.com/kaliber5/ember-bootstrap/issues/1743.
