### ISSUE TITLE
Accordion on Ember 2.10.0

### ISSUE THREAD

**Issue by PratheepV** [kaliber5/ember-bootstrap#177]
Hi,

I was trying accordion on Ember CLI 2.10.0. Getting bellow error.

> "Property set failed: object in path "accordion" could not be found or was destroyed."

https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-accordion-item.js#L49

```hbs
{{#bs-accordion selected=activeSection}}
  {{#bs-accordion-item value=sectionPosition title="List1" selected=(action 'toggleSection' selected)}}
      .....
   {{/bs-accordion-item}}
   .
   .
{{/bs-accordion}}
```

**Comment by simonihmig** [comment]
Is this specific to Ember 2.10, so did it work before and stopped working at 2.10?

And when does that occur, on first render, on destroying the view, or on changing the selected item? Have a stack trace?

**Comment by PratheepV** [comment]
@simonihmig , Yeah stopped working on upgrade of ember and as well as ember-bootstrap.

It fixed by changing the hbs to 

```
{{#bs-accordion selected=activeSection action=(action 'toggleSection')}}
    {{#bs-accordion-item value=sectionPosition}}
      .....
   {{/bs-accordion-item}}
   .
   .
{{/bs-accordion}}
```

It would be great if we update README. 

Thanks,
Pratheepv
