### ISSUE TITLE
ember-cli-sass integration

### ISSUE THREAD

**Issue by Nelvios** [kaliber5/ember-bootstrap#178]
While it is convenient to use @import "ember-bootstrap/bootstrap"; on .less files, I can't seem to use it on .sass or .scss type file. I think this isn't too big of a request as some addons are already around. But I think your addon is outstanding and I like to use the addon you provide without having to install other bootstrap addon for ember just for enabling bootstrap on sass. Thanks by the way.

**Comment by simonihmig** [comment]
Will look at it, thanks!

**Comment by simonihmig** [comment]
Just released 1.0.0-alpha.3 that includes this!
