### ISSUE TITLE
Use modifier outside of an opening tag

### ISSUE THREAD

**Issue by aolvictim** [kaliber5/ember-bootstrap#1780]
This is not really an issue but more of a programming question about the code segment below:

https://github.com/kaliber5/ember-bootstrap/blob/b30a863cc42fc516a1faf36cbf044678f5508c51/addon/components/bs-popover.hbs#L28

How did you use the `did-insert` modifier without calling it from an open `<..>` tag? Thanks

**Comment by jelhan** [comment]
This is not the `{{did-insert}}` modifier but a helper with the same name. It is provided by [ember-render-helpers](https://github.com/buschtoens/ember-render-helpers) package.

Neither the render modifiers nor the helper are good practice for new code. We introduced it when refactoring from `@ember/component` to `@glimmer/component` as a replacement for some lifecycle hooks. Mainly to avoid to big refactoring at once. For new code I would highly recommend to use patterns, which do not reintroduce lifecycle hooks.
