### ISSUE TITLE
Add additional attributes to the form elements

### ISSUE THREAD

**Issue by ixSci** [kaliber5/ember-bootstrap#179]
There are a few attributes which can be applied to the corresponding html elements and which is not presented in the `bs-form-element` component. I believe this component should mimic the attributes Ember [allows to set](https://guides.emberjs.com/v2.10.0/templates/input-helpers/#toc_text-areas). For example, right now you can't set `spellcheck` on the form element which is a bit frustrating.

**Comment by simonihmig** [comment]
Thanks for pointing this out, most common attributes are supported now!
