### ISSUE TITLE
Should `bs-form-group` be contextual?

### ISSUE THREAD

**Issue by srvance** [kaliber5/ember-bootstrap#186]
Right now `bs-form-group` is freestanding. I think it should be contextual under `bs-form`. It probably escaped notice because `bs-form-element` inherits from it rather than it being used explicitly.

I ran into this trying to adjust for some BS4 changes to how the `form-group` class is composed in horizontal layouts.

**Comment by simonihmig** [comment]
Yes, I also had this in my mind. However I was a bit unsure if there might be use cases where one would want to use `bs-form-group` without a `bs-form`, when showing validation state without a real `<form>`? So I left it untouched so far, but might rethink this...

**Comment by srvance** [comment]
So the `form-group` class doesn't automatically pull in `row` in BS4 in horizontal layout. That means that for it to behave the same, we need to add both `row` and `form-group`.  So far, I built it into `bs-form.element`, but that doesn't apply to all form groups like it should. It would be easier to integrate it nicely as a contextual component, although not required. It took me awhile to realize that `element` *extended* `form-group`.
