### ISSUE TITLE
Examples for the alpha release

### ISSUE THREAD

**Issue by stephencarr** [kaliber5/ember-bootstrap#189]
The read-me recommends using the alpha release for new projects. The API docs only target the stable release. Would it be possible to see an example for validating a form with custom input-groups as shown below? I'd like to have the styled `input-group-addon` spans in the group.

![image](https://i.imgur.com/LJaePM8.png)

**Comment by simonihmig** [comment]
You can see the v1.0 API docs here: http://kaliber5.github.io/ember-bootstrap/api/v1.0/

You will have to use the "Custom controls" method: http://kaliber5.github.io/ember-bootstrap/api/v1.0/classes/Components.FormElement.html. Will try to put an example of this use case into the upcoming demo app!

**Comment by stephencarr** [comment]
Thanks @simonihmig. I've got this working, and the validation on my model (`ember-cp-validations`) halts the submission of the form, but all the elements are marked valid with the classes `form-group has-success has-feedback`. The form won't submit no matter how I fill it, and all the fields always show `has-success`. This gist shows my model and form template: https://gist.github.com/stephencarr/53c8c0e11f326de432cc543f69c12f4e

**Comment by simonihmig** [comment]
Looks good at first glance. Might be related to ember-bootstrap-cp-validations, which needs an update. The PR has just been merged a few hours ago, make sure to use this new release of it: https://github.com/offirgolan/ember-bootstrap-cp-validations/pull/9#event-907883291

**Comment by stephencarr** [comment]
This worked, thanks so much. Only comment is the icons are not lined up - I think I saw something in source that was supposed to deal with this, I may be wrong. I can fix this in my CSS though.

![image](https://i.imgur.com/JNnyZMR.png)
