### ISSUE TITLE
Programmatically changing tabs

### ISSUE THREAD

**Issue by rstudner** [kaliber5/ember-bootstrap#194]
So I have the beginnings of 3 tabs etc like this:
```
  {{#bs-tab customTabs=true activeId=initialActiveTab fade=false as |activeId select|}}
```
initialActiveTab is a computed, and it starts properly on tab 1, 2 or 3.

Is there a 'correct' way, to trigger the tabs to change from say, 2 to 3, based on a property on the controller or programmatically  (versus I guess using jquery to find the right tab and clicking it)

Thanks!

**Comment by simonihmig** [comment]
This is ember-bootstrap 0.x or 1.0-alpha?

By setting `initialActiveTab` (and thus `activeId`) the tab content should be updated. As you are using a custom tab navigation, you are responsible of setting its active state accordingly, as described in the "Custom Tabs" example: http://kaliber5.github.io/ember-bootstrap/api/classes/Components.Tab.html

If this is still not working for you, then please post a complete code example!

**Comment by rstudner** [comment]
Maybe i'm just having a glimmer2 problem then.

I have this code in my alerts/index.js controller:
```
  selectedAlert: computed('model.@each.isSelectedInAlertListView', function() {
    let alerts = this.get('model');
    let selectedAlert = alerts.find((m) => {
      return m.get('isSelectedInAlertListView') == true; // m.get is not a function
    });
    return selectedAlert;
  }),
  initialActiveTab: computed('selectedAlert', function() {
    if (this.get('selectedAlert.isHighPlus')) {
      return 'highPlusTab';
    }
    if (this.get('selectedAlert.isMedium')) {
      return 'mediumTab';
    }
    if (this.get('selectedAlert.isLow')) {
      return 'lowTab';
    }
  })
```

So on initial rendering of the page, initialActiveTab gets a value and activeId uses that value and we're golden.

But, if I put a console.log statement in the selectedAlert computed, I can see that sucker change all day, but then initialActiveTab *never* changes again (odd) and thus activeId=initialActiveTab never does anything.

**Comment by simonihmig** [comment]
Hm, seems to be really not related to the tab component, if your CP is not updated as expected. Don't think it's related to Glimmer2, as rendering is not involved there. 

Do you set the `initialActiveTab` property somewhere? If you set it and is has not a setter method, then it looses its "observing" functionality. 

http://emberjs.com/api/classes/Ember.ComputedProperty.html
> You can overwrite computed property with normal property (no longer computed), that won't change if dependencies change, if you set computed property and it won't have setter accessor function defined

**Comment by rstudner** [comment]
I definitely don't set it anywhere/that is the only place.. so for some odd reason it just isn't "bothering" to note when selectedAlert updates.  Hrmph.

Thanks for the help.

**Comment by rstudner** [comment]
Addendum, if I make the computed property:
```
  initialActiveTab: computed('selectedAlert', function() {
    if (this.get('selectedAlert.isHighPlus')) {
      return 'highPlusTab';
    }
    if (this.get('selectedAlert.isMedium')) {
      return 'mediumTab';
    }
    if (this.get('selectedAlert.isLow')) {
      return 'lowTab';
    }
  }).readOnly()
```
and then click on a tab... I get this error
<img width="1212" alt="screen shot 2016-12-31 at 10 20 24 am" src="https://cloud.githubusercontent.com/assets/209970/21578122/e1ea8202-cf42-11e6-9f9b-78e6d7baef8e.png">

There are *no lines of code* doing something.set('initialActiveTab') in the codebase.

**Comment by srvance** [comment]
Bidirectional binding? What if instead of a `readOnly` property, you implement `get` and `set` with the no-op `set` pattern.

**Comment by rstudner** [comment]
Hrm. So clicking on a tab, which changes activeId changes initialTab.

I guess I didn't suspect that would happen.

Thanks for the info.

**Comment by simonihmig** [comment]
Glad that this has been resolved.

Yes, ember-bootstrap 0.x will set the property when changing tabs, because (somewhat unfortunately) all component bindings in Ember are still always two-way. ember-bootstrap 1.0 will follow the DDAU (Data down actions up) best practices by taking care that the public properties you can bind to are never modified.

**Comment by adong** [comment]
If you are using ember-bootstrap 2.7.x

https://github.com/kaliber5/ember-bootstrap/blob/afee843d74306d9fed14683d0499cf4939f2ecfe/addon/components/base/bs-tab/pane.js#L40

It compares `activeId` against `elementId`. Just pass-in your own `activeId` and keep track of it.

You could refer my PR https://github.com/screwdriver-cd/ui/pull/469/files#diff-ac346895cac69e986fe48f3fe9a3e76dL6

Just want to give an example, and hope it helps.
