### ISSUE TITLE
deprecation warnings in ember 1.12 and 1.13beta

### ISSUE THREAD

**Issue by karudo** [kaliber5/ember-bootstrap#2]
I have deprecaton warning "Ember.required is deprecated as its behavior is inconsistent and unreliable."
For example, in the line: https://github.com/kaliber5/ember-bootstrap/blob/master/addon/mixins/type-class.js#L18

**Comment by simonihmig** [comment]
Thanks for reporting, will fix this. As well as the other API docs issue...

**Comment by simonihmig** [comment]
Fixed in master
