### ISSUE TITLE
How can I pass my model to form in bs-modal? 

### ISSUE THREAD

**Issue by meliborn** [kaliber5/ember-bootstrap#209]
I iterate over hasMany relationships and want to make a button, that opens modal dialog with form inside for selected model. How can I do that? Here is a simplified code:

```handlebars
{{#each photos as |photo|}}
   <button>Edit caption</button>
{{/each}}
```

**Comment by srvance** [comment]
If you have your form as a component, you can pass `model=photo`. If you do the form inline as a `bs-modal`, the contents can access `photo` directly. See [here](http://www.ember-bootstrap.com/#/components/modal) and just put something like the "Custom markup" example inside your `each` block.

**Comment by meliborn** [comment]
@srvance if I put bs-modal form inside each block, it edits only last photo caption.
```handlebars
{{#each model.realEstate.photos as |photo|}}
              {{#bs-modal open=modal3 onHidden=(action (mut modal3) false) as |modal|}}
                {{#modal.body}}
                  <div class="form-horizontal">
                      <div class="form-group">
                        <div class="col-sm-9">
                          {{input value=photo.caption class="form-control"}}
                        </div>
                      </div>
                  </div>
                {{/modal.body}}
              {{/bs-modal}}
```

**Comment by simonihmig** [comment]
I would put one modal outside of the each-loop, and have a property like `selectedPhoto` be bound to the forms `modal` property (or the inputs value if you don't ant to use the `bs-form` component). Then add an action to the button passing the current `photo`, and in that action set the `selectedPhoto` and `modal3` (maybe rename this ;)) to true. So hitting that action will open the modal and supply the correct photo model to the form.

Will close this, as this is more a general ember question, not directly an issue within ember-bootstrap. Hope that works out for you!
