### ISSUE TITLE
Navbar collapse

### ISSUE THREAD

**Issue by kmmathis** [kaliber5/ember-bootstrap#21]
I don't see any documentation on getting the collapsable navbar to work. Clicking the hamburger icon doesn't seem to open up the collapsed menu. Is there a component needed to get that to work?

**Comment by simonihmig** [comment]
The collapsable thing requires the collapse jQuery plugin in plain bootstrap.js, which is currently not available as an ember component, but will be soon!

**Comment by simonihmig** [comment]
bs-collapse component is availably as of now in ember-bootstrap v0.4.0! :)
