### ISSUE TITLE
Assign initial (true) value to checkbox in bs-form

### ISSUE THREAD

**Issue by buckmaxwell** [kaliber5/ember-bootstrap#214]
Hi, I would be surprised if I couldn't do this... but I havent' been able to figure it out.  Is this possible?

**Comment by srvance** [comment]
Have you tried setting the `value` or `property` attributes per the API docs?

http://www.ember-bootstrap.com/api/classes/Components.FormElement.html#property_value
http://www.ember-bootstrap.com/api/classes/Components.FormElement.html#property_property

**Comment by buckmaxwell** [comment]
Thanks, just fiddled around with it a bit more -- `property` was able to do the job, I simply hadn't initialized the variable properly.
