### ISSUE TITLE
Collapse example from ember-bootstrap.com fails

### ISSUE THREAD

**Issue by chrischambers** [kaliber5/ember-bootstrap#216]
Should I have to implement my own `controller.actions.toggle`? Most of the examples are plug-and-play, but when testing the collapse one Ember throws the following error:

```javascript
Assertion Failed: An action named 'toggle' was not found in (generated foo.index controller)
```

**Comment by simonihmig** [comment]
You mean this example?

```hbs
{{#bs-button active=notCollapsed onClick=(action "toggle")}}{{#if collapsed}}Show{{else}}Hide{{/if}}{{/bs-button}}

    <hr/>

    {{#bs-collapse collapsed=collapsed}}
        <div class="well">
            <p>This is collapsible content</p>
        </div>
    {{/bs-collapse}}
```

Then yes, sure, you will have to implement actions that you declare in your template. In this case it just toggles the `collapsed` property that is used for the `bs-collapse` component. 

So this is just a basic example, you will have to implement things based on your actual use case.
