### ISSUE TITLE
Textarea bound to model not clearing when the value clears

### ISSUE THREAD

**Issue by masterX244** [kaliber5/ember-bootstrap#217]
WHen using model.rollbackAttributes() all fields reset back to default except the Textarea input type
Reproduction example here: 
https://github.com/masterX244/FormBug

**Comment by simonihmig** [comment]
Can confirm this, thanks for reporting and for the repo!

```hbs
<textarea>{{value}}</textarea>
```

works for every value except `undefined`. Will try to fix this asap.
