### ISSUE TITLE
I want to sent the form object back to the action but not sure how

### ISSUE THREAD

**Issue by vasilakisfil** [kaliber5/ember-bootstrap#22]
First of all congrats for this awesome addon.

I have a bs-form with an action attribute pointing to my action in the route. One thing I haven't found how to do it is to send back (data up) the form object to the action. Using model=formObject doesn't work either. Do you know how I could achieve that? I think it's rather crucial since most actions in Ember 2.0 take place in the route and not in the controller. I can explicitly ask the controller from the route to get the formObject but I would prefer return it from the component's action directly.

**Comment by vasilakisfil** [comment]
The solution to this is
* wrap the form in a component
* pass the data down to the component from route as 1 object, like a formObject
* set the action in the ember-bootstrap form and catch the action from the component 
* resend the action to the controller/router with the modified formObject

**Comment by wukongrita** [comment]
Hi @vasilakisfil , do you have the example code?
