### ISSUE TITLE
Overlaying multiple modals

### ISSUE THREAD

**Issue by Elberet** [kaliber5/ember-bootstrap#226]
I have built a "confirmation" modal that is triggered for several different user interactions, some of which occur inside another modal. This works surprisingly well, however since modals and backdrops are arranged with fixed `z-order` styles, the overlaying modal's backdrop does not actually stack on top of the first modal.

In tinkering with the CSS, I've found that a trivial solution would be to assign the `z-order` directly to `#ember-bootstrap-modal-container`, and let the elements within stack naturally, but this only works as long as the backdrop element appears before the dialog in the DOM.

For now, I have a bit of code that shuffles the modal container's children around whenever a modal is opened, along with some CSS that restores natural z-ordering and pulls the modal container above everything else, but I'd rather have native support for overlaying modals in ember-bootstrap. :+1:

**Comment by srvance** [comment]
From the [Bootstrap docs](https://v4-alpha.getbootstrap.com/components/modal/#how-it-works), "Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences."

The goal of ember-bootstrap is to make Bootstrap available in an Ember-y way.

**Comment by simonihmig** [comment]
I would second that. We should not add this as it may have unwanted side effects for other users. Feel free to extend any component of this addon for your specific requirements though!

**Comment by Elberet** [comment]
Ok, thanks for the feedback. :smile:

@srvance, I haven't yet looked at Bootstrap v4. In v3, multiple modals are not supported out of the box, but only "[require custom code](http://getbootstrap.com/javascript/#modals)" which, apparently, ember-bootstrap provides. Maybe the docs should explicitly mention that multiple modals are still not supported, even if they sort-of work?
