### ISSUE TITLE
Broken compatibility with IE10 in bs-form-element

### ISSUE THREAD

**Issue by ikondrat** [kaliber5/ember-bootstrap#230]
Hi 

I am not sure is known problem or not but I have got incompatibility error in IE10,
it caused by usage of bs-form-element
https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form/element.js
ln 576

It uses non-shimed method for Array 'includes'
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

I fixed it by including shim for that but it looks like better to include shim for this in 'ember-bootstrap'

Thanks

**Comment by simonihmig** [comment]
Hm, I could not reproduce this, even with IE9. When visiting http://ember-bootstrap.com, do you see the same?

The uses of `includes` operate on an `Ember.Array`, which implements `includes` on its own. This should even work for older Ember versions that do not yet have `includes` implemented (see https://github.com/kaliber5/ember-bootstrap/blob/master/package.json#L79).

What Ember version were you using?

**Comment by simonihmig** [comment]
@ikondrat could you please provide some feedback to the questions above, otherwise I will have to close this, as I cannot reproduce it...

**Comment by ikondrat** [comment]
@simonihmig I updated to Ember 2.11 and it was fixed, problem was reproduced in Ember-cli version 2.4.3
