### ISSUE TITLE
Customizable primary button type on ModalSimple?

### ISSUE THREAD

**Issue by bgentry** [kaliber5/ember-bootstrap#232]
One feature I'd like is the ability to control which button `type` is used as the submit button in the simple modal, such as `primary`, `danger`, etc., depending on the action being performed. Of course I could just use the full modal and completely control its contents that way, but that's quite a bit messier 😃 

Do you have thoughts on if that's a good idea and if so, what the option should be called? `submitType` seems like the obvious choice.

The other issue is that if I were to contribute this as a PR, I'd want to be able to use it on the BS4 branch (#206) because that's where I'm currently running. Maybe if I PR it to master it can be cherry-picked over to `bs4`?

**Comment by simonihmig** [comment]
I am a bit hesitant to put too many customization options into the simple modal, as to keep it "simple". But this case maybe is ok to support. I would call it `submitButtonType` maybe? :)

A PR is certainly welcome. We have to merge master into bs4 anyway to keep bs4 up to date.
