### ISSUE TITLE
Remove dependency on bower

### ISSUE THREAD

**Issue by Caltor** [kaliber5/ember-bootstrap#238]
Please refactor this add-on to remove the dependency on bower in favour of npm/yarn as has been in ember itself. Note ember 2.12 will not install bower by default. http://emberjs.com/blog/2017/01/23/ember-2-11-released.html

**Comment by srvance** [comment]
We're looking at updates to the blueprint in #233 and will consider that.

**Comment by srvance** [comment]
The latest blueprint updates remove the bower dependency. This can be closed once that is merged to master and a new release is cut.

**Comment by simonihmig** [comment]
#233 has been merged and removed bower dependency.
