### ISSUE TITLE
Dropdown in Navbar creates infinite loop

### ISSUE THREAD

**Issue by bholbrook73** [kaliber5/ember-bootstrap#242]
I'm trying to add a dropdown inside a navbar and it creates an infinte loop for the navbar. How does one create a dropdown menu inside a navbar?

```
{{#bs-navbar type=inverse fluid=fluid as |navbar|}}
    <div class="navbar-header">
         {{#navbar.toggle}}
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
         {{/navbar.toggle}}
         {{#link-to "dashboard" class="navbar-brand"}}BRAND{{/link-to}}
    </div>
    {{#navbar.content}}
        {{#navbar.toggle}}Dropdown <span class="caret"></span>{{/navbar.toggle}}
        {{#navbar.nav as |nav|}}
            {{#nav.item}}{{#link-to "dashboard"}}Dashboard{{/link-to}}{{/nav.item}}
            {{#nav.item}}{{#link-to "dashboard.users"}}Users{{/link-to}}{{/nav.item}}
            {{#nav.item}}
                {{#bs-dropdown tagName="li" as |dd|}}
                    {{#dd.toggle}}Dropdown <span class="caret"></span>{{/dd.toggle}}
                    {{#dd.menu}}
                        <li>{{#link-to "index"}}Home{{/link-to}}</li>
                        <li>{{#link-to "demo.dropdown"}}Dropdowns{{/link-to}}</li>
                    {{/dd.menu}}
                {{/bs-dropdown}}
            {{/nav.item}}
        {{/navbar.nav}}
    {{/navbar.content}}
{{/bs-navbar}}

<div class="container-fluid">
   <div class="row">
       <div class="col-lg-2 col-md-3">

       </div>
       <div class="col-lg-10 col-md-9">
		   {{outlet}}
	   </div>
   </div>
</div>

**Comment by srvance** [comment]
What version are you using? If you're using 1.0.0-alpha.5, try changing `bs-dropdown` to `nav.dropdown`. If using an earlier alpha, can you try upgrading?

**Comment by michelboaventura** [comment]
I was able to reproduce this on a brand new Ember app with:

```
Ember 2.11.1
Bootstrap 4.0.0-alpha.6
Ember-bootstrap 1.0.0-alpha.5
Ember-models-table 1.11.0
```

All I did was adding this to template.hbs:

```Handlebars
{{#bs-navbar position="fixed-top"  as |navbar|}}
  {{#link-to "index" class="navbar-brand"}}Stocks{{/link-to}}
  {{#navbar.content}}
    {{#navbar.nav as |nav|}}
      {{#nav.item class="active"}}
        {{#nav.link-to "index" class="active"}}Home{{/nav.link-to}}
      {{/nav.item}}
    {{/navbar.nav}}
  {{/navbar.content}}
{{/bs-navbar}}
<div class="container">
  {{models-table classes=invalidVariable}}
</div>
```

One thing to bare in mind. The variable ``invalidVariable`` doesn't exist. But if you just change "classes" to "columns", for instance, it works properly. I was also able to reproduce it without ember-models-table, but couldn't reduce to a simple case as this one.

**Comment by srvance** [comment]
@michelboaventura I'm not sure I see how this relates to the original report. There is no dropdown in your navbar and ember-models-table doesn't use ember-bootstrap.

When you say `template.hbs`, do you mean you're using pods and this is the index route template?

**Comment by michelboaventura** [comment]
Hi @srvance, I should have better explained myself. I think the issue is not with dropdown, but with the navbar itself. I use ember-models-table only to trigger the behavior, because I couldn't find another simpler way of trigger it.

**Comment by srvance** [comment]
@michelboaventura Thank you for clarifying that. I'll try to reproduce it and see if I can figure it out.

**Comment by srvance** [comment]
I don't understand exactly why, but it appears that certain types of errors cause an infinite rerendering loop. In @bholbrook73's example, when I changed all `link-to` route targets to `index` and no errors were generated, the looping stopped. Same with @michelboaventura's example when you remove the use of `models-table`. It made no difference to me if the attribute was `classes` or `columns`.

@simonihmig I think it's an interaction with the `component-child` and `component-parent` mixins and all the CPs used to compute `active` and `disabled` states in `bs-nav/item`.

**Comment by srvance** [comment]
May be related to emberjs/ember.js#14351. There are some anecdotal pointers to ember-cli-active-link-wrapper, which is handling almost the exact same management of `active` around links in Bootstrap. Coincidence?

**Comment by srvance** [comment]
I spoke with one of the Ember core team members about this. It's actually a problem with the way Ember and glimmer2 deal with rendering errors. It's justifiably complex and non-trivial to solve. They're working on some ways to improve it and possible contain it within the scope of an `{{outlet}}`, but that's not available yet.

It's also not a problem with ember-bootstrap. It just seems that way because that's the component that gets repeatedly rendered. At its root, it's caused by an error on the page. For my use of the original report, that error is the presence of a `link-to` with a non-existent route. Not having the routes from the original app's context, I assume one of the routes in the example was misstated. For the second example, it's the error in usage of `models-table`. In both cases, the causal error message was interspersed with the rendering error messages to tell you what needs fixing.

**Comment by simonihmig** [comment]
@srvance Thanks for working on this! 👍

**Comment by michelboaventura** [comment]
Thanks for tracking this down @srvance, I appreciate!

**Comment by srvance** [comment]
I just with I could give a solution other than "don't create errors!"
