### ISSUE TITLE
Change dropdown class "btn-group" to "dropdown"

### ISSUE THREAD

**Issue by absemetov** [kaliber5/ember-bootstrap#244]
I use Dropdown component,  with button block=true.

**Comment by absemetov** [comment]
````
{{#bs-dropdown as |dd|}}
          {{#dd.button block=true}}Dropdown <span class="caret"></span>{{/dd.button}}
          {{#dd.menu as |ddm|}}
              {{#ddm.item}}{{#link-to "index"}}Something{{/link-to}}{{/ddm.item}}
              {{#ddm.item}}{{#link-to "index"}}Something different{{/link-to}}{{/ddm.item}}
          {{/dd.menu}}
 {{/bs-dropdown}}
containerClass: computed('toggle.tagName', 'direction', function() {
    return 'dropdown';
    // if (this.get('toggle.tagName') === 'button') {
    //   return this.get('direction') === 'up' ? 'btn-group dropup' : 'btn-group';
    // } else {
    //   return this.get('direction') === 'up' ? 'dropup' : 'dropdown';
    // }
  })
````

**Comment by simonihmig** [comment]
Could you please clarify what you think is wrong here! According to the docs http://getbootstrap.com/components/#btn-dropdowns a dropdown button should have the `btn-group` class?

**Comment by absemetov** [comment]
I use simplle dropdown http://getbootstrap.com/components/#dropdowns
{{#bs-dropdown as |dd|}} 
      {{#dd.button block=true}}
          Dropdoww           
          <span class="caret"></span>
        {{/dd.button}}
        {{#dd.menu align='right' as |ddm|}}
               {{#ddm.item}}<a {{action 'toggleSort' 'asc'}}>Sort</a>{{/ddm.item}}
         {{/dd.menu}}
{{/bs-dropdown}}

**Comment by srvance** [comment]
Comparing the two examples, it looks like you can have simple dropdown buttons without the `btn-group` class. The `btn-group` class add a top margin of 5 to the button. Is this the issue you're reporting @absemetov? I'm not sure what we should do with this, @simonihmig.

**Comment by simonihmig** [comment]
I have seen the 5px as well, but they are part of the examples CSS of getbootstrap.com, not part of Bootstrap CSS itself. So given the following examples both class variants seem to be legit:
* http://getbootstrap.com/components/#dropdowns
*http://getbootstrap.com/components/#btn-dropdowns

So the question remains, @absemetov what's the actual issue?

**Comment by absemetov** [comment]
If dropdown class="dropdown" button block work.
If dropdown class="btn-group" button block not work.

````
 <div class="row">
          <div class="col-md-3 col-md-offset-9">
            {{#bs-dropdown as |dd|}}
              {{#dd.button block=true}}Dropdown <span class="caret"></span>{{/dd.button}}
              {{#dd.menu align='right' as |ddm|}}
                  {{#ddm.item}}<a {{action 'toggleSort' 'asc'}}>Цена по возрастанию</a>{{/ddm.item}}
                  {{#ddm.item}}<a {{action 'toggleSort' 'desc'}}>Цена по убыванию</a>{{/ddm.item}}
                  {{#ddm.item}}<a {{action 'toggleSort' 'brand'}}>Сортировать по брендам</a>{{/ddm.item}}
                  {{#ddm.item}}<a {{action 'toggleSort' 'default'}}>По умолчанию</a>{{/ddm.item}}
              {{/dd.menu}}
            {{/bs-dropdown}}
        	</div>
        </div>
````
