### ISSUE TITLE
collapsedSize not working?

### ISSUE THREAD

**Issue by mikejerome** [kaliber5/ember-bootstrap#247]
I'm having trouble with the collapse component. It is only applying 'collapsedSize' during the collapsing transition, not collapse or collapse in. So the size is only being applied while the 'collapsing' class is on the element.

**Comment by simonihmig** [comment]
Yes, that's how it is supposed to work. Same for the original bootstrap plugin: http://getbootstrap.com/javascript/#collapse. What's the problem?

**Comment by mikejerome** [comment]
Sorry I guess I just don't understand how it works yet. I'm new to bootstrap. I'll keep reading, thanks.
