### ISSUE TITLE
Fix BS4 `active` state in tabs and dropdown items

### ISSUE THREAD

**Issue by srvance** [kaliber5/ember-bootstrap#248]
This is waiting for the BS4 beta to see how they resolve the known `active` issues.

From #206,

* Why aren't default tabs initial state outlined properly? Diagnosis: The `active` class needs to go on the element with the `nav-link` rather than the `nav-item`. See [this](https://github.com/twbs/bootstrap/issues/21223) and [this](https://github.com/twbs/bootstrap/issues/20156).
  * Change 1caa0ebb2c9aabfb9c0f9896301b1a00a532ee82 has a little leakage of BS4 classes into common templates with `nav-link`. To fix the `active` state issue, there's even more. However, it's a pretty complex template to duplicate and i'm not sure refactoring out a new component is worth it.
  * The same kind of issue exists with dropdown items within a nav.

**Comment by simonihmig** [comment]
With all the latest changes to BS4 beta support, I *think* this should be fixed by now, so closing this...
