### ISSUE TITLE
Multiple error messages in form fields

### ISSUE THREAD

**Issue by eflorit** [kaliber5/ember-bootstrap#253]
Is there a reason why we only display the first error on an invalid model attribute? (cf: https://github.com/kaliber5/ember-bootstrap/blob/536036adad90e70a4ac9add59bea881a99eff631/addon/templates/components/common/bs-form/element/errors.hbs#L2)

Wouldn't we want to loop through all items to show them?

**Comment by simonihmig** [comment]
I guess it depends. I think for many cases I want not want to display multiple lines of error text, causing all following form elements to move down. Also with just one message displayed, when the user types and the message does not apply anymore (say minimum length) but there is still another one, that would be shown then, so you still see the others until there are no errors anymore.

But I am ok with adding this as an opt-in, so will flag this as a feature request. PRs certainly welcome! ;)

**Comment by srvance** [comment]
I'll keep this in mind when I do #249
