### ISSUE TITLE
Add Components.FormElement title property

### ISSUE THREAD

**Issue by absemetov** [kaliber5/ember-bootstrap#254]
{{form.element controlType="tel" label="Mobile number" placeholder="tel" title="+380xx1234567" property="tel" pattern="^[\(\)\s-]*(((\+?[\(\)\s-]*3)?[\(\)\s-]*8)|(\+?[\(\)\s-]*7))?([\(\)\s-]*\d){10}[\(\)\s-]*$"}}

**Comment by simonihmig** [comment]
Indeed this is missing, will add it. 👍

**Comment by srvance** [comment]
I'll keep this in mind when I do #249
