### ISSUE TITLE
BS Dropdown should use capture phase in events

### ISSUE THREAD

**Issue by estshy** [kaliber5/ember-bootstrap#255]
BS Dropdown adds events on `document` and use `bubble` phase of events. I don't like two things about this approach. First of all some ember application are not rendered into body but inside custom container (`appRoot` div) and the second thing is the fact that this handler will be never called in case event will be cancelled beforehand which happens quite often I must say.

It should be at least refactored to `capture` phase of event.

https://developer.mozilla.org/en-US/docs/Web/API/Event/eventPhase

**Comment by simonihmig** [comment]
Regarding the `capture` phase that seems to be a good point.

But regarding the app root div, wouldn't it be strange when the ember app is rendered in a smaller region of the page (so app root div not covering the whole page), and the user clicks outside that region, then the dropdown would not close?

**Comment by estshy** [comment]
@simonihmig I was thinking about a case with 2 ember applications being rendered at the same time and I think you have a point about clicking outside of the region. It should still close it.

**Comment by jeloba** [comment]
@simonihmig I seems this causes dropdowns to stay open when clicking on bs-buttons. This in turn makes it possible to open multiple dropdowns at once. I think this is should be classified as a bug and not as an enhancement.

**Comment by simonihmig** [comment]
@jeloba Agree, this is not desirable. 

I am a bit busy with other things (related and not related to e-b), anyone up for a PR? Shouldn't be too hard hopefully...

**Comment by jeloba** [comment]
@simonihmig one PR comming up.
