### ISSUE TITLE
Add documentation for using HTML in Tooltip

### ISSUE THREAD

**Issue by matthewvalimaki** [kaliber5/ember-bootstrap#257]
http://getbootstrap.com/javascript/#tooltips-options allows use of html in title if attribute html is true (either via JS `html=true` or via html `data-html=true`). None of these options seem to work with `{{bs-tooltip title="test<br>"}}`. However if I put the title between tags it gets rendered `{{#bs-tooltip}}test<br>{{/bs-tooltip}}` which I believe is to be expected per how Bootstrap itself handles things by default. I propose adding support for `html=true` attribute.

**Comment by simonihmig** [comment]
Why would you need that when the block form of the component works? We could support `html=true` by using the non-escaping handlebars syntax (`{{{title}}}`). But this would allow only static html, no dynamic parts (values, helpers, components). But you can do all of this in the block form, already now!

**Comment by matthewvalimaki** [comment]
@simonihmig thanks for the quick response. I do not specifically need it. I should have been more precise in my report. Reason why I propose it is because this projects documentation does not say anything about it and I merely assumed that support for it was missing not that it was specifically left out due to "block form of the component works" :) In my use case I have a very simple text with a line break and using block form simply requires a bit more code and is not as clean :)

I am good with how it currently works. Might be a good idea to add the explanation to documentation.

**Comment by simonihmig** [comment]
> Might be a good idea to add the explanation to documentation.

Makes sense! 👍
