### ISSUE TITLE
Option defaults during fresh installation

### ISSUE THREAD

**Issue by srvance** [kaliber5/ember-bootstrap#272]
A [user reported](https://embercommunity.slack.com/archives/C3T23FY73/p1489969674561523) an installation experience that sounds like the version did not default properly. Text copied below:

```
Hi all,
i’m having trouble installing the ember-bootstrap addon. After running:
$ ember install ember-bootstrap
it shows a red message in the terminal:

Bootstrap version must be 3 or 4

Anybody know what’s up with that and where to configure the version?
```

**Comment by simonihmig** [comment]
Hm, I was just able to reproduce this :(

**Comment by simonihmig** [comment]
Indeed there seems to be an issue with defaults not being applied for `ember install`. `bootstrapVersion` was `3` for `ember g ember-bootstrap`, while `NaN` for `ember install ember-bootstrap`. Will file an issue...

**Comment by simonihmig** [comment]
For the record: https://github.com/ember-cli/ember-cli/issues/6875

**Comment by srvance** [comment]
Thanks for reproducing this, @simonihmig. It was too late here for me to dig into it when I saw the report.

**Comment by simonihmig** [comment]
No problem! There must be some benefit in being in different time zones! ;)
