### ISSUE TITLE
Can't seem to get bootstrapVersion: 4 to trigger the generator to install version 4

### ISSUE THREAD

**Issue by joshuairl** [kaliber5/ember-bootstrap#276]
It just keeps switching it back to bootstrapVersion: 3

**Comment by joshuairl** [comment]
Ignore this...
Just found the
`ember generate ember-bootstrap --bootstrap-version=4 --preprocessor=sass`

**Comment by simonihmig** [comment]
@joshuairl If I understand this correctly, did you have `bootstrapVersion: 4` already in your `ember-cli-build.js`, and it reverted that to 3 when running `ember generate ember-bootstrap`? Is that right?

Which version of ember-bootstrap did you use?

**Comment by joshuairl** [comment]
That is correct.
I’m using latest in your releases list on GitHub.

**Comment by simonihmig** [comment]
Thanks! This still seems to be wrong, it should not do that...
