### ISSUE TITLE
Only override configuration in blueprint when necessary

### ISSUE THREAD

**Issue by srvance** [kaliber5/ember-bootstrap#282]
In the #281 discussion we noted that the blueprint sometimes overrides build configuration settings unconditionally when it shouldn't. For example, `importBootstrapFont` needs to be turned off for BS4, but should be preserved as configured for BS3.

**Comment by simonihmig** [comment]
A quick fix could be to just skip setting `importBootstrapFont` and `importBootstrapCSS` here https://github.com/kaliber5/ember-bootstrap/blob/master/blueprints/ember-bootstrap/index.js#L185-L187, as `index.js` will ignore them anyway if they don't apply.

For the user it might be more convenient to have them set (not unconditionally like now) though, so he can edit them right away without looking them up in the docs...

**Comment by srvance** [comment]
BS4 doesn't include any fonts and you don't want to import the CSS if you're using a preprocessor. At least that was my reasoning for setting them in the blueprint.

**Comment by simonihmig** [comment]
Yes, but in the cases you mentioned, these settings are ignored anyways, see index.js

**Comment by srvance** [comment]
Why don't I change it so it sets 1) the configuration required setting, 2) the existing setting, or 3) the default setting, for all properties?

**Comment by simonihmig** [comment]
Sorry for the late answer, I think that would be a good solution!

**Comment by simonihmig** [comment]
I reclassified this as a bug, as I think it actually is, having some unwanted and unexpected effects on your build. Certainly not critical though.

@srvance would like to cut another release soon, with those latest fixes. Should I wait for this one, or include that with a later release?

**Comment by srvance** [comment]
I'll take care of this one tomorrow.
