### ISSUE TITLE
Error thrown when ember-bootstrap is referenced by another addon.

### ISSUE THREAD

**Issue by themikejr** [kaliber5/ember-bootstrap#286]
## Symptoms

After installing an addon to my ember app that depends on `ember-bootstrap`, the following error is thrown on app startup:

```
Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
  at assertPath (path.js:7:11)
  at Object.join (path.js:1211:7)
  at Class.included (/Users/themikejr/Development/repos/eFlex/webApp/node_modules/ember-bootstrap/index.js:27:30)
  at addons.map.addon (/Users/themikejr/Development/repos/eFlex/webApp/node_modules/ember-cli/lib/models/addon.js:346:34)
  at Array.map (native)
```

## Diagnosis

It seems that when one addon references another addon in this way, the arguments to the `included` function in `index.js` change. ([See this related issue](https://github.com/ember-cli/ember-cli/issues/3718))

[These changes](https://github.com/kaliber5/ember-bootstrap/commit/a2e5b29fc51ebb3b5efef4aae35e36e7f6500b6d) were made to deal with the this problem, but in my case they do not fix this issue. The culprit is the condition: `typeof app.import !== 'function' && app.app`. For some reason in my case, `app.import` is indeed a function. When removing this condition (and leaving the truthy check on `app.app`) it appears to work as expected. (See the code below for more context).

```
module.exports = {
  name: 'ember-bootstrap',

  included: function included(app) {
    // workaround for https://github.com/ember-cli/ember-cli/issues/3718
    if (typeof app.import !== 'function' && app.app) {
      app = app.app;
    }
    this.app = app;

    var options = extend(defaultOptions, app.options['ember-bootstrap']);
    var bootstrapPath = path.join(app.bowerDirectory, 'bootstrap/dist');

```

*I'm wondering if anyone else can recreate this, if I should create a PR with the proposed change, or if there is some environmental condition that I'm missing which makes `typeof app.import !== 'function'` necessary.*

**Comment by simonihmig** [comment]
@themikejr The changes here #291 should hopefully fix this. Can you try that out (use `kaliber5/ember-bootstrap#fix-import` in your package.json) and confirm?

Though if you want to depend of `ember-bootstrap` in another addon, I would still recommend adding `ember-bootstrap` as a direct dependency to the app. You can do that in the addon's default blueprint used when installing it, using [`addAddonToProject`](https://ember-cli.com/api/classes/Blueprint.html#method_addAddonToProject), so users can manage the version on their own. I would not consider nested usage a scenario we would want to actively support...

**Comment by simonihmig** [comment]
@themikejr did you have a chance to test the proposed fix? Would like to close this if it works for you...

**Comment by Wylan** [comment]
@simonihmig Even though its not exactly the same issue I just thought I'd chime in on this. We are experimenting with ember-engines and were encountering a similar error with the current version of ember-bootstrap when trying to use it in an in-repo-engine:

`The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/engine-vendor.js] failed with:
Error: ENOENT: no such file or directory, open 'tmp/source_map_concat-input_base_path-6vkax4OT.tmp/vendor/transition.js'`

I've tested the fix in #291 locally and no longer encounter the issue.

**Comment by simonihmig** [comment]
@Wylan thanks for the feedback, good to know! Will merge and release then soon!

Well actually, the next release probably won't need to import `transition.js` anymore as part of #300, so that will have fixed your issue anyways! 😝

**Comment by Wylan** [comment]
@simonihmig sounds good! 😄

**Comment by robertbenjamin** [comment]
Believe I've been having a related issue with this when trying to use this inside another addon:

```
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: /Users/$USER/Work/ember-aupac-control/node_modules/bootstrap/dist/css
```

Glad you guys figured out the solution, looking forward to the release!

**Comment by simonihmig** [comment]
@robertbenjamin I actually don't see how that is related to ember-bootstrap. Seems more like an issue with this `ember-aupac-control` addon!?

**Comment by robertbenjamin** [comment]
Realized a bit after that was the case, sorry for the distraction.

**Comment by simonihmig** [comment]
I think this should work now, see https://github.com/kaliber5/ember-bootstrap/pull/387: If not feel free to reopen.
