### ISSUE TITLE
Add disabled property to accordion item

### ISSUE THREAD

**Issue by danidr** [kaliber5/ember-bootstrap#287]
Hi again,
I have another feature request for the accordion: Maybe you could add a disabled property to the item so that, by setting it as true, opening that specific item would be inhibited? It would make sense to make such properties available to all components that trigger an action, actually, to keep the logic consistent.
Thank you.

**Comment by dajk** [comment]
Should we do this since it's not a feature bootstrap has as a default?

**Comment by danidr** [comment]
> Should we do this since it's not a feature bootstrap has as a default?
Well, it's not a default feature, but then, the Ember way of doing things is intrinsically different from Bootstrap; whereas Bootstrap offers quite a bit of flexibility by allowing to directly use jQuery and direct DOM manipulation, it's quite hard to obtain the same control in Ember.
The same logic applies, for example, to the navbar automatically collapsing on small viewports; not a default function, but controlling it with Ember is a lot more complex.
