### ISSUE TITLE
Integration with MDBootstrap

### ISSUE THREAD

**Issue by fr0gs** [kaliber5/ember-bootstrap#288]
Hello, and thank you very much for the effort invested in creating and maintaining the addon.
I recently discovered [MDBootstrap](https://mdbootstrap.com), and I love it. 

Despite of having an npm package, I find no easy way to integrate it in my ember build process. Is there any intent of adding support for an addon with this awesome package?

Thank you.

**Comment by simonihmig** [comment]
No, sorry, direct support is out of scope of this addon.

I don't really know this package. You can import additional (or replace the default ones) styles in your app, without this addon having to support this. Also you can add some classes to any component using default Ember functionality (like `{{bs-button class="btn-fancy-wahtever"}}`). Other than that there will be no explicit support, like additional components which not part of the original Bootstrap, sorry!
