### ISSUE TITLE
Button action not firing

### ISSUE THREAD

**Issue by jamesmgg** [kaliber5/ember-bootstrap#29]
{{#bs-button id="detect-user" type="primary" classNames="primary-button" action="detect-user"}}
     Detect user
 {{/bs-button}}

The action is never fired... all I did was install the addon, restart ember server, and add this line of code. The button shows up with the correct bootstrap styling and everything, but the action NEVER gets fired on click. Am I doing something wrong or is this a known issue?

**Comment by jamesmgg** [comment]
Any support?

**Comment by jamesmgg** [comment]
If anyone is interested, this is how I fixed the linking:
  {{#link-to 'two-item-view'}}
    {{#bs-button id="pickup-another" type="primary" classNames="primary-button"}}
        Pick up another bottle
    {{/bs-button}}
  {{/link-to}}

**Comment by simonihmig** [comment]
I don't think there is an issue here, as triggering the default action is covered by a test here:
https://github.com/kaliber5/ember-bootstrap/blob/master/tests/integration/components/bs-button-test.js#L82-L89

I think there must be something wrong elsewhere. 

You are using Ember 1.13 or 2.x?
Have you tried using the action helper: `action=(action "detect-user")`? It will actually throw an exception if there is no action found with this name...

**Comment by simonihmig** [comment]
If you just need an ember link styled as a bootstrap button, then just apply the appropriate classes to the link-to helper directly: Untested: `{{#link-to 'two-item-view' class="btn btn-primary"}}`
