### ISSUE TITLE
FormElement: add class named after property

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#295]
I find myself adding a `classNames` property all the time to form elements to make them addressable in integration and acceptance tests. A short code example:

```
{{#bs-form model=this as |form|}}
  {{form.element classNames='email' controlType="email" label="Email" property="email"}}
  {{form.element classNames='password' controlType="password" label="Password" property="password"}}
{{/bs-form}}
```

Could we please consider adding a class named after property as default? So a form element `{{form.element property='email'}}` would have an class `property-email`?

Perhaps we should make the prefix configurable to prevent naming collisions:

```
module.exports = function(environment) {
  var ENV = {
    ember-bootstrap: {
      'form.element': {
        propertyClassPrefix: 'form-element-for-'
      }
    }
  };

  return ENV;
};
```

If you like these proposal I'm willing to write a PR.

**Comment by srvance** [comment]
I like the idea of supporting test addressability of components. We would need to figure out a way to allow multiple instances of a component in a page, for example if something is in an `{{each}}`. Do you have any thoughts on that?

**Comment by simonihmig** [comment]
I am actually not a big fan of that. I think you should use classes only for styling purposes, and stuff used only for testing should not find its way into a production build.

We use https://github.com/simplabs/ember-test-selectors in our apps for this purpose, which I think is a much better solution. An example taken from an app where we automatically set the selectors based to the `property`value by default by extending the default `bs-form/element`:

```js
import FormElement from 'ember-bootstrap-cp-validations/components/bs-form/element';

export default FormElement.extend({
  'data-test-selector': computed.reads('property')
});
```

**Comment by MatthewDaize** [comment]
I also have run into this issue while writing acceptance tests. @simonihmig, I agree from the context of integration testing that test descriptors are ideal. However, from an acceptance testing perspective, manipulating the outputs results in an inconsistent release between testing/production since the selectors are removed in production.

What might the solution be if you're running some form of validation/acceptance tests against "production" worthy code?

**Comment by jelhan** [comment]
I agree with @simonihmig that extending default components to add testing selectors is the best solution if you don't want to add them to all elements manually. Test selectors applied could be either CSS classes or data attributes. I would also recommend data attributes now as the distinction between CSS classes used for styling and test selectors could be critical especially in bigger teams. I'm closing this issue now. Feel free to reopen.
