### ISSUE TITLE
Stop form.element from wrapping element in form-group

### ISSUE THREAD

**Issue by JCBarry** [kaliber5/ember-bootstrap#296]
Basically the title.  I'd like to specify the form-group myself in a few cases, is it possible to tell the `form.element` component to not wrap itself?

Thanks and great library!

**Comment by simonihmig** [comment]
@JCBarry It is currently not possible, as the FormElement _is_ a FormGroup by inheritance. can you explain your use case?

**Comment by JCBarry** [comment]
I'm trying to accomplish something like this:
http://www.bootply.com/5eJRejdDsu

**Comment by srvance** [comment]
Would an `input-group` satisfy your need?

I'd be curious what the Boostrap folks would say about this. None of their examples put two inputs in a `form-group` leading one to think they mean for it to group labels and their inputs. The also specifically warn not to mix up `form-group` with `input-group` but none of the `input-group` examples show two input fields, either.

**Comment by JCBarry** [comment]
It's a good point, and I'm not really sure.

Regarding `input-group`, the additional wrench is that I'd actually like the first form element to be a `<select>` and bootstrap advises against using textarea's and selects inside of inputgroups.

**Comment by srvance** [comment]
Although you could use a dropdown and a textarea. I believe their caution is because selects are often implemented by the browser with native components and don't always take styling well.

**Comment by simonihmig** [comment]
First, sorry for the long delay. I somehow missed this one...

As it is the task of the FormElement to provide the markup that Bootstrap specified, it needs to be opinionated. And I think the example you provided cannot be covered by the FormElement in a useful way. I think you would have to use a plain FormGroup component, and setup the markup, controls and bindings by yourself.

**Comment by JCBarry** [comment]
>As it is the task of the FormElement to provide the markup that Bootstrap specified, it needs to be opinionated.

This is fair.  Though, it's not explicitly stated that `form-group` to `form-controls` is 1-to-1 and when using a horizontal form, it's possible you would want more than one input on a line (as I'm trying to accomplish).  

This is further supported by the description text from the Bootstrap documentation: http://getbootstrap.com/css/#forms-horizontal which implies that if `form-groups` are treated like `row`s you would want different columns.

I'd be curious to know how to setup the example used in that section using ember-bootstrap.

> I think you would have to use a plain FormGroup component, and setup the markup, controls and bindings by yourself.

Yep. This was the workaround.
