### ISSUE TITLE
Infinite rendering loop

### ISSUE THREAD

**Issue by MichalBryxi** [kaliber5/ember-bootstrap#298]
Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-alpha.9 -> 1.0.0-alpha.9
ember-cli: 2.12.1 -> 2.12.1
bootstrap: ^3.3.7 -> 3.3.7
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 3
importBootstrapFont: true
importBootstrapCSS: true
```
Tried to use this library and stumbled upon following problem:

<img width="999" alt="screen shot 2017-04-10 at 16 47 24" src="https://cloud.githubusercontent.com/assets/847473/24870206/7a7c92c6-1e0d-11e7-887c-6e685485aea3.png">

Basically main application template is rendered infinite number of times under certain conditions. I tried to strip down [the sample app](https://github.com/MichalBryxi/cryptopals.com/tree/ember-2.12-LTS) to bare minimum. Curious thing is that there is nothing really except this template: https://github.com/MichalBryxi/cryptopals.com/blob/ember-2.12-LTS/app/application/template.hbs

- Tested with 2.12 (future LTS).
- The problem seems to be gone with 2.13.
- I'm absolutely not sure whether the problem might be in this addon or Ember itself. Trying to poke the "lower instance" with this.

**Comment by srvance** [comment]
We've seen this before and found it to be due to Ember and glimmer error handling when there is an error on the page. I don't have the reference handy since I'm on my phone. In this case, I would guess you don't have a defined `whatever` route. Create the route or reference an existing route and I'd bet it will behave.

**Comment by MichalBryxi** [comment]
Thanks @srvance, yes I can confirm that `whatever` route does not exist. It's mentioned in the source code & attached screenshot. It's very specific setup. Not sure how many cases can cause this error. My feeling is that this is Ember/Glimmer level problem, right? It seems odd that addon would cause yielding parent template into DOM multiple times.
Just want to verify before reporting to Ember/Glimmer.

**Comment by srvance** [comment]
The addon gets rendered multiple times because it's correct. The render restart happens at the point of the error. 

Yes, this is an Ember/glimmer problem that a core contributor characterized as "halting problem hard." There's another e-b issue that has pointers to those issues IIRC.
