### ISSUE TITLE
disconnect bindings in bs-form-element

### ISSUE THREAD

**Issue by jcope2013** [kaliber5/ember-bootstrap#30]
should this be added into the bs-form-element component? potential memory leak without it? I will submit PR if wanted

https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form-element.js

``` 
 willDestroyElement: function() {
   if (!Ember.isBlank(this.get('property'))) {
       Ember.Binding.from("model." + this.get('property')).to('value').disconnect(this);
       Ember.Binding.from("model.errors." + this.get('property')).to('errors').disconnect(this);
    }
 }
```

**Comment by simonihmig** [comment]
I am not so sure about this. API docs say that you don't have to call `disconnect()` in most cases. 
Do you have any reference that says you have to do this in the way you suggested?

If you use events on objects like `myHandler: Ember.on(...)` then you don't have to remove those event listeners by yourself, and bindings are just higher level concepts based on event listeners...

**Comment by jcope2013** [comment]
yeah i saw the same, the two spots that mention it are

"To actually connect the binding to a specific object just invoke #connect() and to disconnect invoke the #disconnect() method. UPDATE: as Peter stated in the comments, it’s important to say if you manually create bindings via #connect you have to make sure to #disconnect them as soon as you don’t need them anymore. Otherwise you’ll run into memory leaks. If you use the ***Binding syntax you’re fine since Ember.js handles this for you."

http://code418.com/blog/2012/03/26/advanced-emberjs-bindings/

and this blog post also does it

http://alexspeller.com/simple-forms-with-ember/

not sure if it's still relevant or if ember internals have changed that mitigate this problem for you

**Comment by simonihmig** [comment]
Thanks for pointing this out, will have a look at it and fix it if needed!

**Comment by oswaldoacauan** [comment]
Is there a reason to not use a oneWay computed property?

**Comment by offirgolan** [comment]
With the latest release, all bindings were replaced with `defineProperty` using oneWay CPs.
