### ISSUE TITLE
form element `focus-out`

### ISSUE THREAD

**Issue by dbinetti** [kaliber5/ember-bootstrap#303]
How would you recommend I implement the equivalent of a `focus-out` event on a form element?  I see the `onChange` event, but that is obviously fired on every keystroke; I'm looking to just fire an event when the user leaves a field.  Thanks

**Comment by acorncom** [comment]
@dbinetti if you drop down to the raw element you should be able to add that yourself.  Does that work?

**Comment by dbinetti** [comment]
that's basically what I've done.  thanks!

**Comment by basz** [comment]
> if you drop down to the raw element

what do you mean by this?

```
{{#form.element controlType="text" property="consumer.address.street" showValidation=true as |el|}}
    {{el.control focus-out=(action 'parseAddress')}}
{{/form.element}}
```
This does not work (a click= does by the way)

**Comment by melriffe** [comment]
I can confirm this does not work, as expected:

```hbs
{{#form.element invisibleLabel="Value Amount"
  controlType="number"
  size="sm"
  value=amount
  onChange=(action (mut amount))
  as |el|
}}
  {{el.control focus-out=(action "amountChanged")}}
{{/form.element}}
```
My ``amountChanged``:

```js
amountChanged() {

  debug(`${this.toString()}; amountChanged()`);

},
```

ember-bootstrap: 2.8.0
ember-cli: 2.18.2
node: 10.16.0
os: darwin x64

**Comment by basz** [comment]
I believe camelCase just might, at least a quick search through some code revealed the following

```
{{component el.control focusIn=(action "onFocus" "toe-height") focusOut=(action "onBlur")}}
```

**Comment by melriffe** [comment]
That did it! I could've sworn I tried that combination. Oh boy, I must be truly losing my mind these days. :D Thanks for the tip @basz

**Comment by basz** [comment]
:-) know the feeling. you're welcome
