### ISSUE TITLE
Documentation suggestion: Provide controller code with examples

### ISSUE THREAD

**Issue by skitterm** [kaliber5/ember-bootstrap#305]
I am pretty new to Ember and brand-new to ember-bootstrap.
I was looking at the documentation here: http://www.ember-bootstrap.com/#/components/forms
The first example ("Simple Form"), I was at first confused where the properties on the email and password fields were coming from. Would it be possible to provide the backing controller code for all these examples to clarify how things are getting passed into the form?

**Comment by simonihmig** [comment]
Thanks for the suggestion, makes sense!

**Comment by sernadesigns** [comment]
I can add the controller code snippet to the docs.

**Comment by sernadesigns** [comment]
[#906](https://github.com/kaliber5/ember-bootstrap/pull/906) submitted for review.
