### ISSUE TITLE
First 1.0 beta?

### ISSUE THREAD

**Issue by skitterm** [kaliber5/ember-bootstrap#306]
Thanks for this project. I'd like to use this library in a large project but wanted to know how "bleeding edge" the 1.0 alpha is. I gather from the readme that breaking changes are unlikely, but I was wondering if there's a target (I realize software's hard to predict) date for a stable or beta release. 

Also, what are the major features that stand in between the current alpha version and a target stable version? I just wanted to get a sense for how stable things are at the present, to know whether I should adopt this now or wait until the beta or stable version. Thanks for your help.

**Comment by simonihmig** [comment]
@skitterm there might be another alpha release coming these days. But I think the first beta will then follow pretty soon, which will focus just on fixing eventual bugs, and not introduce any breaking changes anymore (in fact iirc no single BC was introduced after alpha.0). So a stable release should be pretty close!
