### ISSUE TITLE
AccordionItem: click on title link does not work

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#311]
Clicking on the `<a>` does not expand the item, but follows the `href`. See http://www.ember-bootstrap.com/#/components/accordion.

Probably introduced with #307. An `e.preventDefault()` in the `click` handler should do the trick. Should be covered by a test.

@dajk wanna have a look?

**Comment by dajk** [comment]
Ah, yes sure.. I'll do that.

**Comment by Techn1x** [comment]
I think this might be related; accordions seem to be broken on iOS 10 (tried both Safari and Chrome) - could be something to do with the missing preventDefault() in the handler and click propagation.

**Comment by Techn1x** [comment]
Oh and by broken I mean the accordions appear fine, but clicking on them doesn't open the accordion item. Clicking on the title link follows the href, however
