### ISSUE TITLE
bs-tab does not work with bootstrap 4

### ISSUE THREAD

**Issue by jsternberg** [kaliber5/ember-bootstrap#315]
If you use `bs-tab` in bootstrap 3, everything works fine. If you try to use it in bootstrap 4, nothing ever shows up, but the elements are still there. Inspecting, I've traced this to the `fade` class being on every `div` created by `bs-tab.pane`. It appears that the `fade` class never gets removed for either bootstrap 3 or bootstrap 4, but this only seems to affect bootstrap 4. I'm guessing that bootstrap 3 somehow ignored `fade` if `active` was set, but bootstrap 4 doesn't do that.

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-alpha.12 -> 1.0.0-alpha.12
ember-cli: 2.12.1 -> 2.12.1
bootstrap: ^3.3.7 -> 3.3.7
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: true
importBootstrapCSS: true
```

**Comment by jsternberg** [comment]
Revising this a bit, it appears that the Bootstrap 4 version doesn't set the `in` class on the active element for some reason. The bootstrap 3 version does. If I manually add `in` for Bootstrap 4 I can see the active tab again.

**Comment by jsternberg** [comment]
I was not aware that I had to update `package.json` with the bootstrap version. Sorry. I'm closing this.

For those who run into the same error, make sure your `package.json` doesn't still have bootstrap 3 in it.

**Comment by simonihmig** [comment]
Glad that you were able to fix the issue by yourself. 

For reference: to upgrade your project to Bootstrap 4 use this command

```bash
ember generate ember-bootstrap --bootstrap-version=4
```

Things get a bit more complicated if you have to switch from Less to Sass, see http://www.ember-bootstrap.com/#/getting-started/bootstrap-4

**Comment by srvance** [comment]
Likewise glad you were able to fix this yourself.

Just to give you some additional detail, Bootstrap 4 changed the use of the `in` class to `show` in most cases. Also, there is still a problem with proper `active` tab highlighting in the Bootstrap 4 usage that is waiting on Bootstrap itself for resolution.
