### ISSUE TITLE
Consider implementing resizable, draggable for modal dialog

### ISSUE THREAD

**Issue by ykaragol** [kaliber5/ember-bootstrap#319]
Currently modal dialog doesn't have any rezisable or draggable features. Please consider implementing resizable, draggable for modal dialog.

**Comment by simonihmig** [comment]
Thanks for the suggestion. However as this is not supported in the original Bootstrap, I would not want to add this to this library. You could still create a new component extending from `bs-modal` that adds this behavior on top of it, maybe even as a separate addon...

**Comment by arohr** [comment]
I managed to make a modal dialog draggable using jquery-ui, installed via the addon `ember-cli-jquery-ui`.

In a component which renders a `bs-modal`:

```
  didInsertElement() {
    this._super(...arguments);

    // make the modal dialog draggable using the addon ember-cli-jquery-ui
    Ember.$('.modal-dialog').draggable();
  },
```

**Comment by simonihmig** [comment]
@arohr Thanks for sharing this!
