### ISSUE TITLE
Dynamically generated forms : seeking some help

### ISSUE THREAD

**Issue by Moxide** [kaliber5/ember-bootstrap#320]
Hello,
I'm trying to implement dynamically generated forms : the goal is that a user can choose the position and type of inputs within a form.
You can take a look at [this basic twiddle](https://ember-twiddle.com/eef21f750ba331c2039a0b5c47cfd0b7), which shows both a static and dynamic forms.

With basic form elements (text, email, textarea...), it should work. But I met a problem with a custom type (a masked-input component).

In a static form, I'm using this code, which works pretty well:
```
  {{#form.element property="phoneNumber" as |el|}}
  	{{masked-input mask='11.11.11.11.11' classNames='form-control input' value=el.value}}
  {{/form.element}}
```

In a dynamic form, I refered to #299, and created a custom control at `/component/bs-form/element/control/masked-phone` and used the following code:
`  {{form.element controlType="masked-phone" property="phoneNumber" }}`

This problem with this method is that it is creating an additional `div`, surrounding the input (highlighted in red in the twiddle), with an "****-field" id, that breaks my layout.

Is there a mean to make the form element NOT generate this `div` ?

Thank you, and sorry for the lengthy post :-/

**Comment by simonihmig** [comment]
@Moxide The `<div>` comes from your `bs-form/element/control/masked-phone` component, not form ember-bootstrap itself. Just make this a tagless component by adding `tagName: ''`

See https://ember-twiddle.com/e2879dd5a9b9b07211e48351f31b6087?openFiles=components.bs-form.element.control.masked-phone.js%2C

**Comment by Moxide** [comment]
Thank you very much ! Sorry, I completely missed this !!!
