### ISSUE TITLE
Components.Navbar automatically collapsing on item click

### ISSUE THREAD

**Issue by danidr** [kaliber5/ember-bootstrap#321]
Hello again,
Another feature request which is not included in the original Bootstrap by default but which could make ember-bootstrap even better.
Right now, when in small viewports, the Navbar collapses as expected and can be opened with the toggle menu. What hinders the navigation, though, is that whenever a nav.link-to item is consequently clicked (therefore the app transitions to a new route), the menu stays uncollapsed, hiding most of the page on vertical viewports.
The idea I had is: there could be a property added to the nav.link-to which could either tell the navbar to collapse itself when the user clicks on it, or set it as the default behavior, therefore adding a property which PREVENTS the navbar to collapse. I would put it in the nav.link-to because it is the most logical place where a user would put a route-changing element; other elements in the navbar (such as forms, plain text or icons/images) shouldn't trigger that behavior.
It would go along the lines of:
```
{{#navbar.nav as |nav|}}
	{{#nav.item}}{{#nav.link-to 'page1'}}page1{{/nav.item}}
	{{#nav.item}}{{#nav.link-to 'page2' collapse=true}}page2{{/nav.link-to}}{{/nav.item}}
{{/navbar.nav}}
```
or 
```
{{#navbar.nav as |nav|}}
	{{#nav.item}}{{#nav.link-to 'page1'}}page1{{/nav.item}}
	{{#nav.item}}{{#nav.link-to 'page2' ignoreCollapse=true}}page2{{/nav.link-to}}{{/nav.item}}
{{/navbar.nav}}
```
Sounds plausible?
Thanks.

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: 1.0.0-alpha.9 -> 1.0.0-alpha.9
ember-cli: 2.12.2 -> 2.12.2
bootstrap: ^4.0.0-alpha.6 -> 4.0.0-alpha.6
bootstrap-sass: n/a
ember-cli-sass: 6.1.2 -> 6.1.2
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
importBootstrapFont: false
```

**Comment by simonihmig** [comment]
Thanks for the suggestions. Closing this in favor of the existing feature request #317
