### ISSUE TITLE
Having a ember-cli-sass installed without boostrap-sass breaks build.

### ISSUE THREAD

**Issue by HodofHod** [kaliber5/ember-bootstrap#322]
There is no way to not use bootstrapp-sass (or bootstrap-less (via `importBootstrapTheme` and `importBootstrapCSS`) if you have a supported preprocessor installed.

Therefore, since I have ember-cli-sass installed (for other things), but am including the boostrap css elsewhere, I get an error when trying to build ([index.js:91](https://github.com/kaliber5/ember-bootstrap/blob/master/index.js#L91)):

> Npm package "bootstrap-sass" is missing, but required for SASS support. Please run `ember generate ember-bootstrap` to install the missing dependencies!

I tried running `ember generate ember-bootstrap --preprocessor=none` but all that accomplished was it uninstalling my ember-cli-sass, which wasn't precisely the solution I was looking for.

(For now, I'm working around this by installing ember-boostrap but removing the import from app.scss)
---

> Output from `ember bootstrap:info` 
> ```
> Npm packages:
> ember-bootstrap: ^1.0.0-alpha.12 -> 1.0.0-alpha.12
> ember-cli: 2.12.1 -> 2.12.1
> bootstrap: ^3.3.7 -> 3.3.7
> bootstrap-sass: n/a
> ember-cli-sass: ^5.6.0 -> 5.6.0
> ember-cli-less: n/a
> 
> Bower packages:
> bootstrap: n/a
> bootstrap-sass: n/a
> 
> ember-bootstrap configuration:
> importBootstrapTheme: false
> importBootstrapCSS: false
> bootstrapVersion: 3
> importBootstrapFont: true
> ```

**Comment by srvance** [comment]
It sounds like we should weaken the message to a warning or at least not make it a failing condition.

**Comment by simonihmig** [comment]
@srvance Warning probably makes sense!
