### ISSUE TITLE
How to use tooltips programatically?

### ISSUE THREAD

**Issue by monovertex** [kaliber5/ember-bootstrap#327]
Is there any way to create a tooltip programatically, from a component's JS file, in an Ember way, using this addon?

I am aware I could use the bootstrap functionality directly, but I was wondering if there's any API in the library for this.

My use case is a validation mixin that is applied to various other components, and displays the error in a tooltip, so I can't control the HBS.

**Comment by simonihmig** [comment]
There could be away using private Ember APIs to create the component and attach it to the DOM somewhere, but not in a supported way I think. 

You can create the tooltips in a template anywhere and make them attach to a DOM element that is in a totally different place in the DOM, maybe that would work for you somehow? See last section of http://www.ember-bootstrap.com/#/components/tooltip. Like inserting them in a template that you do control, but attaching them to the elements that you don't, maybe through some service that the mixin uses to exchange the necessary information... just a wild guess ;)

**Comment by monovertex** [comment]
That idea sounds interesting, but I think it's a bit too complex for my use case, so I'll probably resort to normal bootstrap tooltip usage.

I see you attached the help wanted label. Is this a feature you'd like implemented? If so, I can maybe help, if I find the time to look through the code (we're not using this addon yet, I am thinking about it to replace another tooltip library we're using).

**Comment by simonihmig** [comment]
Hm, no, I actually don't think this makes sense as a standard feature. ember-bootstrap already has a number of "meta" addons that add extra functionality (like validation support), so this *could* be made as a separate addon. But I personally am not going to invest that time (as I just have no use case for me), but others (you?) could of course... :)

**Comment by monovertex** [comment]
Alright, I was confused because of the `help wanted` label.

Thanks for the info!
