### ISSUE TITLE
Using BS javascript directly?

### ISSUE THREAD

**Issue by monovertex** [kaliber5/ember-bootstrap#328]
I have encountered some obstacles while trying to use both ember-bootstrap and the bootstrap javascript directly in my project (to understand my use-case, see #327).

I can't import it using `ember-cli-build`, it always says it can't find it. I'm guessing it can't import files from node_modules, or I'm missing something.

I **can** import it via `import 'npm:node_modules/bootstrap/dist/js/bootstrap', but I have to do this for every file requiring it and it's a bit of a mouthful, I would have liked to avoid that. 

I **can** also add it as a bower dependency, separate from ember-bootstrap, and include that in `ember-cli-build`, but that results in the same dependency in two places (npm and bower), plus I receive this warning when building the project:

```
The dependencies for ember-bootstrap can be outdated. Please run `ember generate ember-bootstrap` to install appropriate dependencies!
```

Is there a cleaner option?

**Comment by simonihmig** [comment]
You cannot import from `node_modules`, that's a limitation of ember-cli. But I believe you can use this to accomplish it: https://github.com/dfreeman/ember-cli-node-assets

Using `bootstrap.js` alongside this addon is nothing we intend to support, so you will be on your own if things should not work as expected unfortunately!

Btw, for general questions (hence the "help wanted" label ;)) there is the #e-bootstrap channel on the Ember Community Slack!

**Comment by monovertex** [comment]
Alright, thanks a lot!
