### ISSUE TITLE
Add Support for Submenus with Dropdowns

### ISSUE THREAD

**Issue by directrix1** [kaliber5/ember-bootstrap#329]
It would be nice if there was a feature to toggle submenus with something like:
```
{{#bs-dropdown as |dd|}}
   {{#dd.button}}Dropdown <span class="caret"></span>{{/dd.button}}
   {{#dd.menu as |ddm|}}
     {{#ddm.item}}{{#link-to "index"}}Something{{/link-to}}{{/ddm.item}}
     {{#ddm.submenu as |sub|}}
       {{#sub.toggle}}Special Submenu <span class="caret right"></span>{{/sub.toggle}}
       {{#sub.menu as |subm|}}
         {{#subm.item}}{{#link-to "index"}}Something else{{/link-to}}{{/subm.item}}
         {{#subm.item}}{{#link-to "index"}}Another thing{{/link-to}}{{/subm.item}}
       {{/sub.menu}}
     {{/ddm.submenu}}
   {{/dd.menu}}
{{/bs-dropdown}}

```

**Comment by srvance** [comment]
@directrix1 I'll try to take a look at this over the weekend.

Which e-b and Bootstrap versions are you using? If you're using a recent version of e-b 1.0 alpha, you can run `ember bootstrap:info` and paste the results here.

**Comment by srvance** [comment]
Submenus were deliberately removed from Bootstrap in BS3 and were not re-added in BS4. See twbs/bootstrap#6342.

I'm inclined not to support submenus as a result, but would like @simonihmig's opinion on this.

**Comment by simonihmig** [comment]
I agree with @srvance on this., let's stick to what Bootstrap itself supports. You would still maybe be able to extend the existing components to make this work within your app, but we won't support this by default.
