### ISSUE TITLE
bs4 checkbox and radio syntax missing

### ISSUE THREAD

**Issue by gijsbotje** [kaliber5/ember-bootstrap#336]
the bs4 checkbox uses the markup from common, which is the bs3 way.

bs3: http://getbootstrap.com/css/#checkboxes-and-radios
bs4: https://v4-alpha.getbootstrap.com/components/forms/#checkboxes-and-radios

this results in non styled checkboxes that don't align properly
i don't have enough knowledge of ember to build them myself, so if someone would be so kind to create these that would be awesome

**Comment by simonihmig** [comment]
That seems to be wrong indeed. Thanks for reporting!

**Comment by gijsbotje** [comment]
@simonihmig if i have more elements that are not complient to the bs4 docs, should i comment them here or make new issues?

**Comment by simonihmig** [comment]
@gijsbotje Feel free to create additional issues, at least for all elements that are not really related! Hope there aren't so many! ;)

**Comment by gijsbotje** [comment]
@simonihmig prepare yourself.... :)
