### ISSUE TITLE
bs4 dropdown still uses ul element

### ISSUE THREAD

**Issue by gijsbotje** [kaliber5/ember-bootstrap#337]
the bs4 dropdown does not use a ul element anymore
the dropdown menu just contains the a every menu item, title or divider

bs4: https://v4-alpha.getbootstrap.com/components/dropdowns/#single-button-dropdowns
bs3: http://getbootstrap.com/components/#dropdowns-example

_side note_
would be nice if alignment is configurable with a prop

**Comment by srvance** [comment]
@gijsbotje I don't believe this affects the operation or alignment of the dropdown, but it certainly introduces unnecessary markup contrary to the intent of BS4. I'm working on a fix for that right now.

With respect to alignment, it's supported with the [align attribute on the dropdown menu component](http://www.ember-bootstrap.com/api/classes/Components.DropdownMenu.html#property_align). Does this satisfy your needs?

**Comment by srvance** [comment]
@gijsbotje @simonihmig I'd like your opinions.

While the most common pattern will be an Ember `link-to` as a dropdown item, we can't presume that's the case. The three scenarios that I anticipate based on Ember usage and the BS4 documented examples are

1. `{{link-to}}` item
1. `<a>` item
1. `<button>` item

Given that it's not harmful to address the latter two cases by wrapping them in a `<div>`, for BS4 I'm inclined to create a `{{dropdown-menu.link-to-item}}` to address the first and leave `{{dropdown-menu.item}}` as a wrapper with the `dropdown-item` class on it. It's not perfectly as described in the BS4 docs, but it achieves the same result in an implementable fashion with minimal deviation.

Thoughts?

**Comment by gijsbotje** [comment]
well the dropdown-item class has to be added to the a or button to have the correct styling
so if you use a wrapper with that class it's still wrong
I don't really know what the best option is though, leaving that to the experts (I'm only a css expert)

**Comment by gijsbotje** [comment]
@simonihmig what's your opinion about this? 
currently every link-to, a and button element will not get strechted as it should eg.:
<img width="161" alt="schermafbeelding 2017-06-14 om 21 02 37" src="https://user-images.githubusercontent.com/7714133/27149771-f7da020c-5144-11e7-8707-bf2e6766439a.png">

the inner rectangle is in this case an a element, this rectangle is the clickable area.
The clickable area should be the rectangle surrounding this element.
That is why you need the `nav-item` class on the link-to, a or button element/component.

**Comment by srvance** [comment]
@gijsbotje Thank you for pointing out where the difference would be. I'll see if I can find a good solution to the problem.
