### ISSUE TITLE
Add support in forms for ember-cp-validations

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#34]
Forms support https://github.com/dockyard/ember-validations already, add support for https://github.com/offirgolan/ember-cp-validations

**Comment by basz** [comment]
+1

**Comment by basz** [comment]
alpha support was added by cp-validations : https://github.com/offirgolan/ember-cp-validations/issues/144

**Comment by offirgolan** [comment]
@simonihmig feel free to close this issue :smile_cat:

**Comment by simonihmig** [comment]
Your right. For the record: support is added by https://github.com/offirgolan/ember-bootstrap-cp-validations
