### ISSUE TITLE
Popover, renderInPlace and SVG's

### ISSUE THREAD

**Issue by Techn1x** [kaliber5/ember-bootstrap#344]
I've noticed some strange behaviour with popovers.. when placed in an SVG, they seem to ignore their renderInPlace=false setting (which should wormhole them), instead they attempt to create their div inside the SVG context (causing errors because a div can't be created inside an SVG context)

Placing them outside the SVG, and instead using triggerElement on the layers inside the SVG seems to work just fine.

For example, this works;
```xml
<svg id="tyre-pressure-svg-truck" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" >
    <g id="some-layer">
        a shape or something
    </g>
</svg>
{{#bs-popover autoPlacement=true triggerElement="#some-layer" triggerEvents="hover focus" title="Sensor Information" renderInPlace=false}}
    popover content
{{/bs-popover}}
```

and this doesn't;
```xml
<svg id="tyre-pressure-svg-truck" xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" >
    <g id="some-layer">
        a shape or something
        {{#bs-popover autoPlacement=true triggerEvents="hover focus" title="Sensor Information" renderInPlace=false}}
            popover content
        {{/bs-popover}}
    </g>
</svg>
```

I know SVG is a notoriously difficult thing to work with, and I can definitely work around this in my code by just moving the popover out of the SVG and using trigger elements, I'll just end up with a lot of duplicated code, which is fine... but I was wondering what might be the cause of this? Is this something that can be fixed or is it here to stay?

Thanks! Looking forward to the next update :)

**Comment by simonihmig** [comment]
@Techn1x I think this is related to the fact that ember-wormhole always has a wrapping `div`, even when the wormholed content is somewhere else in the DOM, which seems to break your SVG use case here. See https://github.com/yapplabs/ember-wormhole/issues/70

I guess you have to live with `triggerElement` solution in this case...

**Comment by simonihmig** [comment]
Closing this for now, as there is currently no way of having a tagless wormhole.

**Comment by Techn1x** [comment]
No worries, thanks for the explanation!

**Comment by Techn1x** [comment]
@simonihmig Seems that this works now :) not sure why, something must have updated to support tagless wormholes

I'm glad, got to delete a nice chunk of redundant code...

**Comment by simonihmig** [comment]
> Seems that this works now

Ah, yes. We dropped ember-wormhole in favor of ember-popper, which also does this "wormhole"/"portal" thing, but works tagless!
