### ISSUE TITLE
Popover styling to allow specific width

### ISSUE THREAD

**Issue by AonGroup** [kaliber5/ember-bootstrap#345]
Is there a way to specify the maximum width of the popover?
I can see that it gets styled during creation but can't see an easy way to over-ride this.
I've seen previous examples where a class can be applied to the whole component, but my specific requirement means I need to use in-line styles.

**Comment by simonihmig** [comment]
There is no built-in way to do that, as Bootstrap itself does not have this feature. But you should be able to extend the popover component in your app and add the missing functionality there!
