### ISSUE TITLE
Remove warning when using it without bootstrap-sass

### ISSUE THREAD

**Issue by gnapse** [kaliber5/ember-bootstrap#346]
I'm just integrated this package into my app, but I want to use it without boostrap-sass. We're providing bootstrap css internally in the app. It works ok but the warning is annoying. Is there a way to disable it? If it needs change in the package code, and you're ok with it, please give me some pointers and I can work on it myself.

**Comment by simonihmig** [comment]
@gnapse Can you please post the output of `ember bootstrap:info`, and which warning are you receiving?

**Comment by gnapse** [comment]
@simonihmig here it is

```
$ ember bootstrap:info
Npm packages:
ember-bootstrap: 1.0.0-beta.1 -> 1.0.0-beta.1
ember-cli: 2.13.2 -> 2.13.2
bootstrap: n/a
bootstrap-sass: n/a
ember-cli-sass: 5.5.1 -> 5.5.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 3
importBootstrapFont: false
importBootstrapCSS: false
```

```
$ ember build --watch
Npm package "bootstrap-sass" is missing, but is typically required for SASS support.
Please run `ember generate ember-bootstrap` to install the missing dependencies!
```

**Comment by srvance** [comment]
So you want to use SASS for something else, but not with ember-bootstrap? If you want to use Bootstrap 3 with SASS, we recommend the bootstrap-sass packaging of Bootstrap.

We recently downgraded it to a warning instead of an error, but it's a configuration that only makes sense for more advanced or unusual use cases. I think we need some level of safety net for newer users.

@simonihmig Do you think the more intelligent blueprint may justify removing some of the warnings or only generating them in a verbose mode that has to explicitly be turned on? Do we still need the same level of safety net?

**Comment by gnapse** [comment]
If I state that I don't want to load bootstrap's css, can't that setting be used to decide wether to show the warning or not? I thought that stating in the settings not to load the bootstrap css, would mean this package is not needed.

**Comment by srvance** [comment]
That setting determines whether the load the static CSS, where `true` implies you aren't using a preprocessor and `false` implies you are using a preprocessor in the dominant configurations.

What is your use case for using ember-bootstrap and not wanting to import any bootstrap package? Do you have a customized bootstrap or equivalent set of classes? You need some bootstrap equivalent for ember-bootstrap to be useful.

**Comment by gnapse** [comment]
Never mind. I just realized bootstrap also worked because we were importing it via bower prior to incorporating your gem. Now that I incorporated this package, which requires `bootstrap-sass`, I'll remove the bower dependency and use that instead.

**Comment by srvance** [comment]
@gnapse Cool. Thanks for talking through this. I recommend running the generator. It will make all the changes for you.

`ember g ember-bootstrap --bootstrap-version=3 --preprocessor=sass`
