### ISSUE TITLE
Stop event bubbling on bs-button

### ISSUE THREAD

**Issue by adambedford** [kaliber5/ember-bootstrap#347]
Is it possible to stop event bubbling when passing a closure action into the `onClick` handler of a `bs-button`?

My use case is:  table row navigates to a route on click, button in table row deletes row on click. Clicking delete button should not navigate to table row, it should only delete the record.

This isn't working:

```handlebars
{{#bs-button size="sm" onClick=(action "destroy" model bubbles=false) type="danger"}}
  Delete
{{/bs-button}}
```

Any help greatly appreciated!

**Comment by simonihmig** [comment]
@adambedford thanks for mentioning this. I actually think preventing the event to bubble should be the default behavior (maybe configurable?). This needs to be fixed!

**Comment by adambedford** [comment]
Thanks, Simon! Now, as someone new to ember ... how do I bundle this latest version of `ember-bootstrap`?

**Comment by srvance** [comment]
Once a new release is cut, it will be as simple as updating the `ember-bootstrap` version in your `package.json` and doing an install with npm or yarn. You could use a GitHub branch reference to get it sooner, but you would pick up ongoing changes.

**Comment by simonihmig** [comment]
@adambedford to get zit immediately, you can reference ember-bootstrap using `kaliber5/ember-bootstrap#45b8482e57e0a3b3217d9f55fe6cff83c42edf13`minsteqd of the version number in your package.json, and `npm install`.

**Comment by adambedford** [comment]
Thanks @srvance and @simonihmig, I successfully pulled this version. It actually ended up breaking my form submissions, however. Perhaps the button submit isn't now bubbling up to the form? The form's `onSubmit` action isn't being called when clicking a button with `buttonType="submit"`

**Comment by simonihmig** [comment]
@adambedford Oh, that's bad. Will fix this asap
