### ISSUE TITLE
Compatibility with ember-cli-datepicker?

### ISSUE THREAD

**Issue by sfbwalder** [kaliber5/ember-bootstrap#349]
Are there any compatibility issues when using ember-bootstrap and ember-cli-datepicker in the same app?
We'd like to use ember-cli-datepicker as a component on a ember-bootstrap form.

**Comment by simonihmig** [comment]
> Are there any compatibility issues when using ember-bootstrap and ember-cli-datepicker in the same app?

I don't know, never used it. You have to find out by yourself ;)
