### ISSUE TITLE
bs-tooltip "calling set on destroyed object" when removed

### ISSUE THREAD

**Issue by XaserAcheron** [kaliber5/ember-bootstrap#350]
If a tooltip is placed inside an #if and later removed from view, it leaves behind some stray hover events on the trigger element, causing some "calling set on destroyed object" errors to get console'd when mousing over it.

I've tossed up [a twiddle](https://ember-twiddle.com/73d918e1515223b733a5d1ea0aa66957) to demonstrate the problem. Type something into the input field, mouse over the alert box to see the tooltip, then clear the input field. When you hover over the box again, you get no tooltip (as intended), but also some ugly console errors.

[BTW, my specific use case is simply hiding the tooltip when a variable message is blank, and I couldn't find a good way to do this other than tossing the tip in an #if. If I've missed something in the API, that'd help I suppose, though ideally this issue ought to be fixed either way.]

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-beta.1 -> 1.0.0-beta.1
ember-cli: ^2.13.1 -> 2.13.1
bootstrap: v4.0.0-alpha.6 -> 4.0.0-alpha.6
bootstrap-sass: n/a
ember-cli-sass: ^6.2.0 -> 6.2.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: true
```

**Comment by simonihmig** [comment]
@XaserAcheron thanks for tracking that down. Indeed this should never happen, will look at it asap!

**Comment by XaserAcheron** [comment]
Thanks for the quick response! The momentum is strong with this one. :)
