### ISSUE TITLE
Best approach to add server errors to ember-bootstrap forms?

### ISSUE THREAD

**Issue by adambedford** [kaliber5/ember-bootstrap#356]
I'm wondering if anyone can weigh in on how to approach handling server-side errors with `bs-form`s. I'm using `ember-changeset` and the corresponding bootstrap library for client-side validation, however I don't have a good sense of how to handle server errors short of manually adding them in the `save()` operation.

Is this something the library already handles that I've missed? Are other folks doing this somehow?

**Comment by simonihmig** [comment]
@adambedford unfortunately I am not that experienced with `ember-changeset`. I know for example that `ember-cp-validations` supports ember-data errors. So if the validation library supports integrating them, they should show up in correctly within the form. So I think this is actually more an issue related to ember-changeset itself!?

**Comment by simonihmig** [comment]
Closing this as I think this is more an issue with the validation library rather than e-b itself. Feel free to reopen if you think there is something missing in e-b! Btw, for general question/help there is the #e-bootstrap Slack channel!

**Comment by adambedford** [comment]
Hi @simonihmig Thanks for your response. Let's pretend I'm not using `ember-changeset` or `ember-changeset-validations` ~ Does this library add `DS.Model` errors to the form when the server rejects a `save()` operation?

**Comment by srvance** [comment]
There is no connection between ember-bootstrap and ember-data. It knows nothing about ember-data.
