### ISSUE TITLE
Question about usage nested inside a non-Ember web site

### ISSUE THREAD

**Issue by haldiggs** [kaliber5/ember-bootstrap#36]
I currently have an asp.net mvc application that has its own copy of bootstrap that I need available to it. I use simple imports in the ember-cli-build so that I have access to it. I'm assuming your add-on brings in its own bootstrap version as well... maybe not? 

do you have any recommendations on handling this? I can't see having my users download both bootstrap copies. Really want to use this add-on.

Thanks

**Comment by simonihmig** [comment]
No, it is not. It is only incuding CSS and glyphicons, which you can disable (see http://kaliber5.github.io/ember-bootstrap/getting-started/). The (still incomplete) JS functionality of Bootstrap is implemented with native Ember components, so bootstrap.js is not included by the addon!

**Comment by haldiggs** [comment]
sweet, thanks!
