### ISSUE TITLE
Popover tip not being offset

### ISSUE THREAD

**Issue by Techn1x** [kaliber5/ember-bootstrap#361]
My current situation; Using Chrome, I have several popovers with `viewportSelector` set, and `autoPlacement=true`. When mousing over a popover that needs to be adjusted due to viewportselector, it seems to be correct for the first hover (popover & tip are placed correctly), but then on 100% of subsequent hovers on that same popover the popover 'tip' is in the incorrect place.

I was hoping it would be related to this issue; https://github.com/kaliber5/ember-bootstrap/issues/357
But unfortunately, I tried applying the changes to my ember-bootstrap code and my issue was still apparent..

I've made a twiddle here (well, I adapted one of the twiddles from the above link), scroll down and click the button multiple times to see the popover tip placed incorrectly
https://ember-twiddle.com/5fdb5a458006fb8dbe23f10dae8e5ce9/6faeaf1738d1379c8cb1b4077b7f9ee5f79a9813?openFiles=templates.application.hbs%2C

---

I did some investigation into the `applyPlacement(...)` function https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-contextual-help.js#L541-L586

It seems the way the offset is applied is by applying a `top: x%` style (default 50%) to the tip/arrow element in `this.replaceArrow(...)` https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-contextual-help.js#L586

I can see that this replaceArrow function is called exactly the same way (same args) on every hover, and each time definitely applies a `top: x%` to the arrow element it was passed - however when I look at the arrow element in the DOM, only the first hover has top: x% style set... each subsequent hover the element is missing this top style.

Any ideas? I'm a bit out of my depth at this point

Thanks!

**Comment by Techn1x** [comment]
Also: Even though the twiddle has the popover in a scrollbox, I believe this has nothing to do with the problem (I have other popovers showing the same systems that aren't in scroll's)

**Comment by simonihmig** [comment]
Thanks for investigating this!
