### ISSUE TITLE
Native form validation tips are not shown

### ISSUE THREAD

**Issue by c410-f3r** [kaliber5/ember-bootstrap#371]
This behaviour affects forms without `submit` button like modals with forms and forms submitted  with "enter" event (both use `event.initEvent('submit', true, true)`).

```
 {{#bs-modal-simple title="Form Example" closeTitle="Cancel" submitTitle="Ok"}}
   {{#bs-form onSubmit=(action "submit") model=this as |form|}}
     <!-- Required tip is not shown -->
     {{form.element controlType="text" label="first name" property="firstname" required=true}}
     {{form.element controlType="text" label="last name" property="lastname"}}
   {{/bs-form}}
 {{/bs-modal-simple}}
```

Solution? Automatically create a `submit` button with `display:none;` for forms without `submit` button?

**Comment by simonihmig** [comment]
You mean the native validation is not shown, when creating a `submit` event programmatically?

Just tested this in some plain HTML5 form, this seems to be the standard behavior of browsers, and not specifically related to ember-bootstrap in any form, is it?

**Comment by c410-f3r** [comment]
In the modal with forms scenario, the submit button is kind of "replaced" with the modal button, therefore, should act like a native submit button. Do you mind a PR with this feature?
Nevertheless, you are right, the whole thing is the standard behavior :)

**Comment by simonihmig** [comment]
@c410-f3r what exactly do you have in mind, as a PR? Really creating a click event on the form's  own submit button (if there is any)? As the form creation is out of control of the modal, we cannot create it inside of the modal, so the user would have to cooperate (like creating an invisible submit button). At least not in an ember-ish way using a template, we could create a button using DOM and remove it after triggering the submit, but that feels quite like a hack...

**Comment by c410-f3r** [comment]
That was the plan but it is indeed a ugly non-transparent hack so I am closing this issue. Thanks for the explanation.
