### ISSUE TITLE
BS4 dropdown doesn't collapse

### ISSUE THREAD

**Issue by xg-wang** [kaliber5/ember-bootstrap#379]
I'm using the Button dropdowns. Instead of `link-to`, I used a `bs-button` inside the dropdown menu item, but the menu wouldn’t close after clicking the menu.

The sample code would be like:
```
{{#bs-dropdown class="my-2 my-sm-0" as |dd|}}
  {{bs-button defaultText="Search" buttonType="submit"}}
  {{#dd.button type="outline-success" class="dropdown-toggle-split"}}
    <span class="sr-only">Toggle Dropdown</span>
  {{/dd.button}}
  {{#dd.menu as |menu|}}
    {{#menu.item}}
        {{bs-button class="dropdown-item" defaultText="something" onClick=(action "select" "param")}} 
    {{/menu.item}}
  {{/dd.menu}}
{{/bs-dropdown}}
```

The thing I noticed is that there will be a `show` class on {{bs-dropdown ... as |dd|}}, but clicking on the buttons wouldn't remove the class. If I manually remove that `show` class with jQuery, I need to click the dropdown icon twice to show the menu again.

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-beta.2 -> 1.0.0-beta.2
ember-cli: ~2.14.0 -> 2.14.0
bootstrap: next -> 4.0.0-alpha.6
bootstrap-sass: n/a
ember-cli-sass: ^7.0.0 -> 7.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
I think the reason is that the button intercepts the click event, see https://github.com/kaliber5/ember-bootstrap/pull/354. Will need to think about how to best handle this, either provide a means to still let the event bubble up from the button, or a way to programmatically control the dropdown, or both!? :)

**Comment by xg-wang** [comment]
I think we can always control whether to bubble it or not within the action defined? https://guides.emberjs.com/v2.14.0/components/handling-events/
BTW, just looked into the code, should I use toggle instead of bs-button?

**Comment by simonihmig** [comment]
#382 adds support to add `bubble=true` to the button. With that this should be fixed!
