### ISSUE TITLE
Ember v2.0 issue with modal (wormhole)

### ISSUE THREAD

**Issue by ianbale** [kaliber5/ember-bootstrap#38]
Trying out the basic demo in an Ember-cli 2.2.0-beta.1 project:

 {{#bs-modal title="Simple Dialog"}}
   Hello world!
 {{/bs-modal}}

I'm getting this error:

Uncaught Error: ember-wormhole failed to render into '#ember-bootstrap-modal-container' because the element is not in the DOM

Is Ember-cli v2+ supported by ember-bootstrap / ember-wormhole? If so, any idea why I might get this error? The few other controls I tried seem to work ok.

**Comment by simonihmig** [comment]
I just tried it with a fresh installation of ember-cli 2.3.0-beta1 and it worked flawlessly!?

An initializer of ember-bootstrap is responsible for creating the `#ember-bootstrap-modal-container` div. If that div is missing, you will likely get that error. See this screenshot:

![image](https://cloud.githubusercontent.com/assets/1325249/12421085/b27c0d08-bec0-11e5-9726-1cfb14f036fc.png)

The div is missing in your project? Any errors in the console?

**Comment by ianbale** [comment]
Ah! Interesting... Only that error above. I backed it out of my project so I could carry on working. I'll put it back in later and give it another whirl and check for that DIV and report back.

Thanks for taking a look...

**Comment by ianbale** [comment]
That was it. Missing DIV. My app does some pretty funky stuff when it starts up, removing content from the page it's loaded into which is generated by a CMS system, but it not required here. Looks like that DIV gets created in an area of the page which I remove. Added a DIV with that ID elsewhere manually and it's all working now.

Thanks for the pointer in the right direction.
