### ISSUE TITLE
Provide example of dropdown in navbar

### ISSUE THREAD

**Issue by srvance** [kaliber5/ember-bootstrap#384]
From a Slack thread on behalf of @gmartell:

Please provide an example in the documentation of using a dropdown in a navbar.

**Comment by munkyboy** [comment]
does [this example](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-nav.js#L41-L57) satisfy the request?

**Comment by srvance** [comment]
No. That's the responsive behavior. He's looking for an example of a dropdown component used in an item.

**Comment by jvenezia** [comment]
What is the correct way to use a dropdown in a `{{#bs-navbar as |navbar|}}` ?
Looks like there is no `{{#navbar.dropdown}}` component.

**Comment by simonihmig** [comment]
@srvance Isn't indeed the link @munkyboy provided a valid example? [here](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-nav.js#L49) the dropdown yielded form `bs-nav` is used as a `<li>` item. Or do I miss sth?

**Comment by srvance** [comment]
I don't know what I was thinking before. I think that example shows it properly.
