### ISSUE TITLE
Build error using ember-engine

### ISSUE THREAD

**Issue by c410-f3r** [kaliber5/ember-bootstrap#389]
**bootstrap:** 4.0.0-alpha.6
**ember-bootstrap:** 1.0.0-rc.1
**preprocessor:** Sass

Created the new standard `/addon/styles/addon.scss` file with `@import "ember-bootstrap/bootstrap"`, since engines shouldn't include anything inside the app directory, and got the following error:

```
Error: File to import not found or unreadable: ember-bootstrap/bootstrap.
Parent style sheet: /blah/blah/blah/tmp/sass_compiler-input_base_path-W0IxlCC7.tmp/addon.scss
    at options.error (/blah/blah/blah/node_modules/node-sass/lib/index.js:291:26)
```

In a dummy app environment, everything is OK using the normal `/app/styles/app.scss` file but nothing  seems to work in real consuming apps.

**Comment by mohitsud** [comment]
i'm having the same issue- @c410-f3r  are you able to share how you solved it?

**Comment by c410-f3r** [comment]
Wow! This 3 years old bug still occurs to this very day :thinking: 

@mohitsud I didn't solve and I don't use EmberJS anymore. You might want to checkout the official repository for further investigation

**Comment by jelhan** [comment]
@mohitsud Can you provide a reproduction?

**Comment by mohitsud** [comment]
Thanks for the reply @c410-f3r  and @jelhan . I actually figured this out. It was a challenge to get ember-bootstrap to work inside an ember engine. The solution for me was:

- do not import @import "ember-bootstrap/bootstrap" into the addon css
- move ember-bootstrap and sass from a devDependency to a dependency in the engine package.json.

**Comment by jelhan** [comment]
>     * do not import @import "ember-bootstrap/bootstrap" into the addon css

What is the use case for importing Bootstrap in an engine? Not having much experience with engines. But would have thought that this is the responsibility of host app. Aren't you facing bundle size issues and CSS class clashes if every engine brings its own CSS framework?

Wondering if the issues you are seeing are less related to Ember Bootstrap but more to ember-cli-sass and it's [requirements for being used in addon](https://github.com/adopted-ember-addons/ember-cli-sass#addon-usage).

**Comment by mohitsud** [comment]
@jelhan  I love engines to really separate groups of logic in my code. Through some tests, npm does some magic where it does not bundle the same library twice between the host and engine, but instead only once. Naturally its critical to ensure the version number remains the same across host and engine.

**Comment by jelhan** [comment]
@mohitsud Sorry. Can't follow. I was talking about Bootstrap CSS. I thought it would be included twice in the build output if it's imported in `app/styles/app.scss` of host and `adfon/styles.scss` of engine.

**Comment by mohitsud** [comment]
Got it. That is very likely. It actually might be the cause of my most recent issue. 
I basically created a new project to verify this bug. I installed ember-bootstrap and ember-paper (Ember-CLI v3.20). I notice I am not able to `@import 'ember-paper' and `@import ember-bootstrap/bootstrap` at the same time without getting sass errors. Its likely both those projects are fighting to modify the default bootstrap theme.
