### ISSUE TITLE
Accordion class binding on item.title and item.body

### ISSUE THREAD

**Issue by Techn1x** [kaliber5/ember-bootstrap#404]
I've just been playing around with accordions and noticed that a supplied class name doesn't seem to get binded to item.body (but it does for item.title)

For example, the following code;
```handlebars
{{#bs-accordion class="list-accordion" as |acc|}}
	{{#acc.item class="list-accordion-item" type=(if (lt i 5) 'danger' 'warning') as |accItem|}}
		{{#accItem.title class="list-accordion-item-heading"}}
			...
		{{/accItem.title}}
		{{#accItem.body class="list-accordion-item-body"}}
			...
		{{/accItem.body}}
	{{/acc.item}}
{{/bs-accordion}}
```

Results in the something similar to the following;
```html
<div role="tablist" class="list-accordion panel-group ember-view">
	<div id="ember1174" class="list-accordion-item panel panel-danger ember-view">
		<div id="ember1175" role="tab" class="list-accordion-item-heading panel-heading collapsed ember-view">
			...
		</div>
		<div id="ember1191" class="panel-collapse collapse ember-view">
			...
		</div>
	</div>
</div>
```

I tried to pinpoint in the e-b code what was causing it but some of the accordion code goes a little over my head unfortunately

**Comment by simonihmig** [comment]
The item.body is a tagless component (`tagName: ''`), so cannot receive a class automatically. We would have to assign it explicitly [here](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/templates/components/bs3/bs-accordion/body.hbs#L2) (same for bs4). Want to do a PR?

Nevertheless, you should be able to appply your custom styling without having to set new classes everywhere, with a selector like `ist-accordion-item .panel-body`, right?

**Comment by Techn1x** [comment]
Ah ok! I'll see if I can do a PR for it.

Definitely only a minor issue because like you say, I can just use a different selector, I was more just curious about why the class binding worked for one component and not another :)
