### ISSUE TITLE
Components.Button add role button attribute

### ISSUE THREAD

**Issue by absemetov** [kaliber5/ember-bootstrap#411]
When add this attr cursor change to pointer.

**Comment by absemetov** [comment]
Solved:
component bs-button.js
````
attributeBindings: ['disabled', 'buttonType:type', 'title', 'role'],
role: 'button'
````

**Comment by simonihmig** [comment]
Why would you want to do this? The button role is useful for assistive technology to indentify something that is *not* a button as behaving like a button. But a `<button`> (which `bs-button` will generate) is always considered a button!?

Btw, I think `role` is already by default part of `attributeBindings`, so should not be needed.

**Comment by srvance** [comment]
Have you looked at your computed styles to see if and where `cursor` is set?

@simonihmig I don't see `role` in the `bs-button` source.

**Comment by simonihmig** [comment]
Little correction: the property is called `ariaRole`, and is part of `Ember.Component` ([here](https://www.emberjs.com/api/ember/2.14/classes/Ember.Component/properties/ariaRole?anchor=ariaRole)). So you can set the role for every component, without having to add to `attributeBindings`. Like `{{bs-button ariaRole="link"}}`. 

But again, if it is already a `<button>` there is no need to set the role to button, and a button already has the right cursor, so probably you customized things in a special way? Closing this for now...
