### ISSUE TITLE
rc.1 and v4-beta : dropdown is not rendering correctly

### ISSUE THREAD

**Issue by thornomad** [kaliber5/ember-bootstrap#421]
Hi there - just upgraded to the latest and am wondering if I did something wrong in upgrading or this is in fact a bug.  Clicking on my `dropdown` items no longer toggles a menu visibily.  

#### Using the example code from the API:

```hbs
{{#bs-dropdown as |dd|}}
  {{#dd.toggle}}Dropdown <span class="caret"></span>{{/dd.toggle}}
  {{#dd.menu as |ddm|}}
    {{#ddm.item}}
      {{#ddm.link-to "index"}}Something{{/ddm.link-to}}
    {{/ddm.item}}
    {{ddm.divider}}
    {{#ddm.item}}
      {{#ddm.link-to "index"}}Something different{{/ddm.link-to}}
    {{/ddm.item}}
  {{/dd.menu}}
{{/bs-dropdown}}
```

#### Renders this output (after click - when I would expect to see the menu):
![image](https://user-images.githubusercontent.com/124717/29487553-d1fd737c-84af-11e7-85c4-215c7890114a.png)

It is missing a `.show` class on the the nested `div.bootstrap-menu` -- if I add that class in the console the item displays correctly.

Do others see this behavior?  I am fairly new to Ember and the whole package management/upgrade thing is still something I am learning.  Thanks.

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```text
Npm packages:
ember-bootstrap: ^1.0.0-rc.1 -> 1.0.0-rc.1
ember-cli: 2.13.2 -> 2.13.2
bootstrap: ^4.0.0-beta -> 4.0.0-beta
bootstrap-sass: n/a
ember-cli-sass: ^6.2.0 -> 6.2.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by thornomad** [comment]
Oh my goodness, sorry, I just saw this pull https://github.com/kaliber5/ember-bootstrap/pull/410

Seems on the radar.

**Comment by srvance** [comment]
Nope. You're correct. Working on the beta right now. That one has been fixed. See #410.

I'd recommend either reverting explicitly to 4.0.0-alpha.6 or using the branch for the PR, although the latter still has some issues.

**Comment by thornomad** [comment]
I will keep an eye out for updates!  Thanks!  Still developing Ember Warrior Ninja Status -- will be happy to help in the future with pull requests.  Have to figure out how addon development works first.  Smile.
