### ISSUE TITLE
Add onClick hook on {{nav.link-to}} component

### ISSUE THREAD

**Issue by Turbo87** [kaliber5/ember-bootstrap#422]
It would be awesome if the `{{nav.link-to}}` component would support an `onClick=(action "foobar")` hook that is triggered before collapsing the navbar and starting the route transition.

**Comment by simonihmig** [comment]
I actually did an implementation of this quickly, when I realized that the `bs-nav.item` component already calls an `onClick` action (should know my own stuff a little bit better 🙄). As this should wrap any `link-to`, and as long as the `link-to` does not prevent event bubbling (`bubbles` not set to false), you could attach your action to this one to achieve the same effect (not tested).

@Turbo87 does that cover your use case? Again I could add this requested featurel as most work is already done, but if that's not necessary, it's probably better to not increase the public API unnecessarily!?

**Comment by Turbo87** [comment]
Hmm, I'm pretty sure I tried that and it did not work. Can you give a small code snippet of what exactly you mean?

**Comment by simonihmig** [comment]
@Turbo87 sorry, forgot about this one... would something like this work for you?

```hbs
...
{{#navbar.nav as |nav|}}
  {{#nav.item onclick=(action "someAction")}}
    {{#nav.link-to "index"}}Home{{/nav.link-to}}
  {{/nav.item}}
  ...
{{/navbar.nav}}
...
```

**Comment by Turbo87** [comment]
I actually managed to solve it another way, but yes, I think that would've solved it too :)
