### ISSUE TITLE
bs-navbar example renders itself 12 times

### ISSUE THREAD

**Issue by Argus9** [kaliber5/ember-bootstrap#424]
I am using the Navbar example under "Usage" at http://www.ember-bootstrap.com/api/classes/Components.Navbar.html in a fresh Ember application, and am noticing that the navbar is rendering 12 times. See the following screenshot: 
![localhost-4200-navbar](https://user-images.githubusercontent.com/3951240/29497062-3837c08e-85af-11e7-894d-37939b5d4ba9.png)

I simply copied and pasted the code into a new route's template (.hbs) file and navigated to the page. I'm not sure why this is happening. Nothing in the code makes it obvious that it is iterating over anything.

For what it's worth, using the plain HTML example from Bootstrap's web site does not result in repeated headers.

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-rc.1 -> 1.0.0-rc.1
ember-cli: ~2.14.2 -> 2.14.2
bootstrap: ^4.0.0-beta -> 4.0.0-beta
bootstrap-sass: n/a
ember-cli-sass: ^7.0.0 -> 7.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by Argus9** [comment]
Found the issue - the link-to segments pointed to routes that don't exist. I feel so silly!

**Comment by srvance** [comment]
@Argus9 This is a known issue with glimmer rendering. I'm glad you figured it out.
