### ISSUE TITLE
request: bootstrap-version=4 should setup sass by default

### ISSUE THREAD

**Issue by ballPointPenguin** [kaliber5/ember-bootstrap#428]
Thank you for taking the time to open an issue!

For general questions please use the #e-bootstrap channel on the Ember
community Slack.

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
ember-bootstrap: ^1.0.0-rc.2 -> 1.0.0-rc.2
ember-cli: ~2.14.2 -> 2.14.2
bootstrap: ^4.0.0-beta -> 4.0.0-beta
bootstrap-sass: n/a
ember-cli-sass: ^7.0.0 -> 7.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

Since bootstrap v4 is using sass by default, it might be helpful & expected to include sass setup when the generator is run with --bootstrap-version=4

first I ran:
```
ember g ember-bootstrap --bootstrap-version=4
```
but then I realized what I wanted to run was:
```
ember g ember-bootstrap --bootstrap-version=4 --preprocessor=sass
```
so maybe (?) the first should imply the second. But then again, maybe not.

**Comment by openhouse** [comment]
To install ember-bootstrap with bootstrap v4beta and ember-cli-sass
`ember install ember-bootstrap --bootstrap-version=4 --preprocessor=sass`

**Comment by srvance** [comment]
It defaults to SASS if you were already using it. We didn't want to default it for compatibility with the defaults for people migrating from BS3, and we thought that the choice of a new  tool should be an explicit rather than implicit choice. That's just the rationale for the original implementation, but it needs to be considered at least until BS4 comes out of "experimental."

**Comment by simonihmig** [comment]
I still believe adding Sass to your project should be an explicit choice by the user, as stated by @srvance. But the work in #569 to add an interactive installer will make this choice much more apparent. So will close this for now. Thanks for your feedback!

**Comment by ballPointPenguin** [comment]
ok thank you
