### ISSUE TITLE
Way to subscribe to component events?

### ISSUE THREAD

**Issue by paultannenbaum** [kaliber5/ember-bootstrap#43]
Is there a way to subscribe to events that happen within a component? For example, If I have an alert or modal open and the containing controller needs to know when that component has been closed, is that possible given the current api? If not, why not just go ahead and allow the current actions to continue bubbling up?

**Comment by simonihmig** [comment]
For the `bs-modal` component, you have a couple of actions that get called at the different lifecycle events, like [closedAction](http://kaliber5.github.io/ember-bootstrap/api/classes/Components.Modal.html#property_closedAction).

For the `bs-alert` you are right, a similar `closedAction` is missing. I will file an issue for this. In the meantime you can use an observer on the [dismissed](http://kaliber5.github.io/ember-bootstrap/api/classes/Components.Alert.html#property_dismissed) property.
