### ISSUE TITLE
Cannot install any ember-bootstrap 1.x version

### ISSUE THREAD

**Issue by langereissilvio** [kaliber5/ember-bootstrap#430]
ember-cli: 2.14.2
node: 8.4.0
os: win32 x64

When I install ember-bootstrap, it always hangs when it gets to fsevents or fs-extra. From what I've gathered, they're not meant to be installed on a windows machine.

I tried installing with --no-optional, but to no avail:
C:\Users\rrush\Documents\GitHub\TuinenDeMeulenaere>npm install --no-optional
[            ......] / extract:fs-extra: sill extract define-property@0.2.5

When I install any 0.x version, these files are skipped properly and the installation succeeds.

Any suggestions would be appreciated ! :)

**Comment by sfbwalder** [comment]
1.0.0-rc.1 works for me, but 1.0.0-rc.2 hangs.  When I use npm with verbose to get more info:
```
npm install ember-bootstrap@1.0.0-rc.2 --verbose --no-optional
```
it stops here:
```
npm verb gentlyRm don't care about contents; nuking C:\dev\ember\ssaa-example\node_modules\.staging\fs-extra-5844dc74\node_modules
```

ember-cli: 2.14.2
node: 6.11.0
npm: 3.10.10
os: win32 x64

Any help will be appreciated.

**Comment by langereissilvio** [comment]
Another one with the same issue over at SO. I posted this question over there, someone tested it but had the same issue as me (and sfbwalder).

https://stackoverflow.com/questions/45904802/install-of-ember-bootstrap-1-x-hangs

**Comment by keanedawg** [comment]
Coming from that thread. I am having either a very similar or the same issue.

**Comment by srvance** [comment]
Simon is on holiday, and I don't have easy access to a Windows box, so it may take a little to follow up on this.

**Comment by noahgelman** [comment]
Same for me? 1.0.0-rc.1 is fine, but 1.0.0-rc.2 hangs

**Comment by srvance** [comment]
@noahgelman @keanedawg Also Windows?

**Comment by keanedawg** [comment]
Yes

**Comment by debelop13** [comment]
Same for me!

It hangs for me with 1.0.0-rc.2 in windows, in mac works.

I have to install 1.0.0-rc.1

**Comment by simonihmig** [comment]
I was able to reproduce this on Windows 10 (in a VirtualBox). I don't think the root issue is within ember-bootstrap, rather probably npm itself (some dead locking issue or so), as I was able to "fix" this by downgrading `findup-sync` (more a workaround, but worked for me). Here is a PR: #435. Took me quite some time... 

Could someone who ran into this try to confirm that installing ember-bootstrap using the following command fixes the issue? 

```bash
npm i --save-dev kaliber5/ember-bootstrap#downgrade-findup
```

**Comment by sfbwalder** [comment]
I agree its an npm issue with some dependent package.  The install you asked to be tried worked.  I then uninstalled ember-bootstrap and tried installing 1.0.0-rc.2 direct from github and that worked also.
```
  "ember-bootstrap": "github:kaliber5/ember-bootstrap#1.0.0-rc.2",
```
I uninstalled again and tried `npm i ember-bootstrap@1.0.0-rc.2` to pull it from npm and it failed.  npm must be doing something different when pulling from github vs. npmjs.com.

**Comment by SKYnv** [comment]
npm i --save-dev kaliber5/ember-bootstrap#downgrade-findup
work for me!

**Comment by langereissilvio** [comment]
Same here. Works like a charm.

**Comment by langereissilvio** [comment]
@simonihmig : If you'd like, you can add the answer to the SO topic, if you want some rep. If not, is it ok that I copy and link your reply solution/workaround ?

**Comment by simonihmig** [comment]
> If not, is it ok that I copy and link your reply solution/workaround

@langereissilvio sure
