### ISSUE TITLE
Problem with ember-bootstrap and bootstrap@4.0.0-beta

### ISSUE THREAD

**Issue by michelboaventura** [kaliber5/ember-bootstrap#438]
I've created a brand new ember 2.15 app, added ember-bootstrap with bootstrap 4 support and discovered that navbar is always being showed as the mobile version.

Messing around I've discovered that when installed ember-bootstrap put bootstrap version ``^4.0.0-alpha.6`` on package.json. The issue is that since ``4.0.0-beta`` has been released it is being used instead of ``4.0.0-alpha.6`` which seems to have changed the way navbar should work: https://github.com/twbs/bootstrap/issues/23788

I've put an app example with this issue at https://github.com/michelboaventura/ember_bootstrap_test

A work around is just fix the correct version on package.json

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-rc.2 -> 1.0.0-rc.2
ember-cli: ~2.15.0 -> 2.15.0
bootstrap: ^4.0.0-alpha.6 -> 4.0.0-beta
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: true
```

**Comment by srvance** [comment]
Hi, @michelboaventura. Thank you for the report. The BS4 beta work is happening on the `bs4-beta` branch. There were quite a few changes.

**Comment by michelboaventura** [comment]
Hi, @srvance. it took me a while to figure this out because ember-bootstrap was installing an incompatible BS version, so I've created this issue to help others with the same issue.

Cheers,

**Comment by simonihmig** [comment]
Closing this. #415 makes sure that for now only alpha is installed by default. And #462 is a tracking issue for supporting beta...
