### ISSUE TITLE
Modals don't work with mobile safari

### ISSUE THREAD

**Issue by bhje** [kaliber5/ember-bootstrap#44]
The bs-modal component doesn't seem to work on Safari for iPhone.  The modal dialog does not appear on the screen.

**Comment by simonihmig** [comment]
I cannot reproduce. Tested it, works for me without any problems. 

Can you provide a code sample? And it does work for other (desktop) browsers, does it?

**Comment by bhje** [comment]
Thanks for your reply.  After doing some more digging, I discovered that this is not an issue with ember-bootstrap.  I was trying to launch a bootstrap modal from a click on a row <tr>.  After reading this [https://guides.emberjs.com/v2.3.0/templates/actions/#toc_attaching-actions-to-non-clickable-elements](url) I added tr { cursor: pointer;} to my css and everything worked.
