### ISSUE TITLE
form not working in production build

### ISSUE THREAD

**Issue by xg-wang** [kaliber5/ember-bootstrap#441]
```
ember new bs-test
ember install ember-bootstrap
// copy paste form http://www.ember-bootstrap.com/api/classes/Components.Form.html
ember build --prod
```
Then serve the files in dist/, only buttons in #bs-form would show up, `form.element` would not be rendered.

Both bootstrap3/4 fail.

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-rc.2 -> 1.0.0-rc.2
ember-cli: ~2.15.1 -> 2.15.1
bootstrap: ^3.3.7 -> 3.3.7
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 3
importBootstrapFont: false
importBootstrapCSS: true
```

**Comment by donaldwasserman** [comment]
Is this the same issue as I identified in #418 ? I thought I fixed that particular error.

**Comment by xg-wang** [comment]
@donaldwasserman 
I think it isn't. `ember s` and `ember build` works well if the property is null, only prod build wouldn't render.

**Comment by donaldwasserman** [comment]
Try defining the layout property. If it renders, that's the same bug that
my PR didn't actually fix.

**Comment by simonihmig** [comment]
@xg-wang first of all, having a formLayout that is not one of the three valid strings is not going to work, so please check if it works when you change that as @donaldwasserman suggested!

Not having that should show an error in your browsers console, added by the mentioned PR. Don#T you see that?

**Comment by xg-wang** [comment]
```hbs
{{#bs-form as |form|}}
{{/bs-form}}
```
and setting `formLayout = null` in controller would render the `form.element` in prod build.

It should be relating to how Ember checks properties in Object in prod build.

**Comment by jvenezia** [comment]
Same here, element doesn't show in production only (without any error).
Only works if I don't set `formLayout` property.

**Comment by kitsuneyo** [comment]
Just want to add my voice as another experiencing this issue.
If I hand-write inputs they work, but form.element doesn't in production.
