### ISSUE TITLE
Fixed table headers

### ISSUE THREAD

**Issue by Techn1x** [kaliber5/ember-bootstrap#442]
Unfortunately it seems to be really difficult to implement fixed/sticky table headers in bootstrap, without some kind of jquery plugin, or some hacky solution of two tables stacked on top of each other with fixed column widths

I know the goal of this project is mainly to replace the bootstrap javascript, but would a feature like this be within scope and/or simple to implement?

There is an issue about it on bootstrap's github page, but it was closed due to the effort that would be involved
https://github.com/twbs/bootstrap/issues/1804

Alternatively if anyone does know a nice way to implement fixed table headers in bs3 I would love to hear it!

**Comment by simonihmig** [comment]
@Techn1x This would certainly be out of scope for ember-bootstrap. But I know that https://github.com/offirgolan/ember-light-table supports a sticky table header, you might want to try it!

**Comment by Techn1x** [comment]
Fantastic! That will work well
