### ISSUE TITLE
Form element with tooltip for label

### ISSUE THREAD

**Issue by Techn1x** [kaliber5/ember-bootstrap#449]
Is it possible to access the label block of a form-element?

I tried this, which didn't seem to work;
```handlebars
{{#form.element property="eventType" useIcons=false as |el|}}
	{{#el.label}}
		Event
		{{bs-tooltip title='The event that will generate an alert'}}
	{{/el.label}}
{{/form.element}}
```

Specifically I'm trying to attach a tooltip to the label, not quite sure how...

Thanks!

**Comment by simonihmig** [comment]
No, that's not possible. You _could_ supply a custom component (name) with the `labelComponent` property (see https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-form/element.js#L761), to replace the default one. But that is still considered a private API, so _might_ break in the future. But might as well become public some day... 😝

**Comment by Techn1x** [comment]
Sorry to take so long to get back to this, thanks for pointing me in the right direction. So supplying a custom `labelComponent` seems easy enough to do, but how would I pass down the tooltip text?

**Comment by simonihmig** [comment]
You can use the component helper:

```hbs
{{#form.element labelComponent=(component "my-label" tooltipText="my text")}}
```

**Comment by Techn1x** [comment]
This works well, thanks.

The only way I would like to improve on this would to be able to use the label as a block (that way I can use markup in the tooltip), just like how you can with the control...

I guess I could pass in markup as the tooltip text and use the triple stash {{{tooltipText}}}
