### ISSUE TITLE
`container` is deprecated when using popover and parentView

### ISSUE THREAD

**Issue by cwhittl** [kaliber5/ember-bootstrap#452]
`{{#bs-popover
        placement="top" triggerEvents="hover" title="Actions"
        container="body" triggerElement="parentView"}}
        {{status}}: {{publications.length}}
      {{/bs-popover}}`

Messages
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.

DEPRECATION: Providing the `container` property to <lucy@component:bs-popover::ember240> is deprecated. Please use `Ember.setOwner` or `owner.ownerInjection()` instead to provide an owner to the instance being created. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.

**Comment by cwhittl** [comment]
Found this, if it helps...
https://github.com/tim-evans/ember-pop-over/commit/efad30fc349d343942afc06546bd7d5c88eb69b1

**Comment by simonihmig** [comment]
Not sure where this might come from. I know access to `this.container` is deprecated, but that's not happening anywhere in this addons code. You are using the most recent release? (1.0.0-rc.2) 
_The output of `ember bootstrap:info` would have helped here..._

If so, could you please copy paste the full stack trace that you see in your console?

**Comment by cwhittl** [comment]
Trying to get the full stack but here is my bootstrap infoL

Npm packages:
ember-bootstrap: ^1.0.0-rc.2 -> 1.0.0-rc.2
ember-cli: ~2.15.1 -> 2.15.1
bootstrap: n/a
bootstrap-sass: ^3.3.7 -> 3.3.7
ember-cli-sass: ^6.1.2 -> 6.2.0
ember-cli-less: n/a
Bower packages:
bootstrap: ^3.3.7
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 3
importBootstrapFont: true
importBootstrapCSS: false

**Comment by simonihmig** [comment]
I just realized you are setting `container` in your template:
```hbs
{{#bs-popover placement="top" triggerEvents="hover" title="Actions" container="body" triggerElement="parentView"}} {{status}}: {{publications.length}} {{/bs-popover}}
```

There is no supported `container` property in `bs-popover`. However pretty sure this will have triggered the error you reported.
