### ISSUE TITLE
"popover-content" class seems to be renamed to "popover-body" in bootstrap@v4.0.0-beta

### ISSUE THREAD

**Issue by roberkules** [kaliber5/ember-bootstrap#453]
hi,

trying to use popovers and customize the background color using bootstraps variables... that didn't work because ember-bootstrap renders `.popover-content`, but bootstrap is using now `.popover-body`

(uses `popover-content`)
https://github.com/kaliber5/ember-bootstrap/blob/bs4-beta/addon/templates/components/common/bs-popover/element.hbs#L5

(expects `popover-body`)
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_popover.scss#L192

**Comment by roberkules** [comment]
oh, and `.popover-title` is now `.popover-header`

**Comment by simonihmig** [comment]
This is fixed in the latest push of the `bs4-beta` branch, thanks for reporting!
