### ISSUE TITLE
[Quest issue] Can we drop support for IE9/10?

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#454]
I would like to gather some feedback from all of you who use ember-bootstrap for your projects, if you still have a hard requirement to support IE 9 and 10!

The current version (`1.0.0-rc.2`) does support IE9 and 10, but there are quite a few good reasons for dropping it:
* continuing to support them will occur additional development costs, directly in this addon, or in upstream dependencies (e.g. https://github.com/kybishop/ember-popper/issues/42)
* although the [RFC to drop support for IE9/10 in Ember 3.0](https://github.com/emberjs/rfcs/pull/252) itself is still open, support for that move seems to be overwhelming
* They have reached end of life, Microsoft itself does not support them, does not fix bugs, even security issues

The downside of such an eventual move would of course be a breaking change, that might lead users that still _have_ to support them for whatever reason without an upgrade path.

So please give some feedback here, if you still have IE9/10 support as a requirement, or if you feel comfortable dropping support for them! Thanks a lot!

**Comment by cibernox** [comment]
In case it helps, ember-power-select which this addon uses, does't support IE9 already. It has been that way for at least a year. Not a single person ever complained.

**Comment by c410-f3r** [comment]
BS4 supports IE10+ but dropping IE9 and IE10 in `ember-boostrap` would speed up development, e.g., IE10 scores a ridiculous 265 in HTML5test.
As a user, I use `ember-bootstrap` for evergreen browsers only.

**Comment by Techn1x** [comment]
IE11 support is all my webapp needs, dropping IE9/10 should be no big deal for us.

**Comment by elgordino** [comment]
I would be quite happy to see IE 9/10 dropped. The main ember project is also considering the same for Ember 3.0 (https://github.com/emberjs/rfcs/pull/252) and comments in the RFC seems pretty strong for dropping 9/10.

**Comment by basz** [comment]
IE9 shouldn't need to be supported anyway as bs4 doesn't. I have no issues with it

**Comment by srvance** [comment]
No problem here. We'll have to figure out the messaging for BS3 users.

**Comment by acorncom** [comment]
We don't support IE9/IE10 on an app I'm using this addon on. :+1: on dropping support for both of them

**Comment by musaffa** [comment]
In favor of dropping support for IE 9 & 10.

**Comment by simonihmig** [comment]
Seems we all agree here unanimously. That's how it should be then...

Thanks all for the valuable feedback!
