### ISSUE TITLE
Importing variables in v4

### ISSUE THREAD

**Issue by bgentry** [kaliber5/ember-bootstrap#466]
I think the way to import variables has changed in v4. Here's what ember-bootstrap's docs say to do:

```scss
@import "ember-bootstrap/bootstrap/variables.scss";
```

However, that gives an import error. I tried a bunch of different combos, and you actually need to drop the `/bootstrap` part of the path. That also doesn't work on its own, though, because that file now uses functions which have to be imported too. Here's what seems to work for me:

```scss
@import "ember-bootstrap/functions.scss";
@import "ember-bootstrap/variables.scss";
```

Admittedly I'm using the bootstrap v4 beta version right now. I realize lots of stuff is broken there but I don't think this is related or at least not likely to change in future betas.

To be clear, the reason I'm trying to import these files separately is that I want to customize variables before bootstrap itself gets imported (otherwise they have no effect) and I also want to use some of bootstrap's variables in my own definitions. Specifically, things like the grayscale and color functions.

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-rc.2 -> 1.0.0-rc.2
ember-cli: ~2.15.1 -> 2.15.1
bootstrap: ^4.0.0-alpha.6 -> 4.0.0-beta
bootstrap-sass: n/a
ember-cli-sass: ^7.0.0 -> 7.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
> you actually need to drop the /bootstrap part of the path

This is true indeed. The example in the docs were based on Bootstrap 3, which for Sass uses the Sass-port `bootstrap-sass` which has a somewhat different file layout: https://github.com/twbs/bootstrap-sass/tree/master/assets/stylesheets

So this mainly needs to be updated in the docs. Will do that, but PRs are certainly welcome as well! ;)

> That also doesn't work on its own, though, because that file now uses functions which have to be imported too.

This seems to have changed in 4-beta. But there is nothing we can do to fix that I think, so remains a documentation issue as well.

**Comment by simonihmig** [comment]
To Do: an example for BS4 would have to be added [here](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/dummy/app/templates/getting-started/assets.hbs#L82-L100), that addresses https://github.com/kaliber5/ember-bootstrap/issues/466#issue-264644163
