### ISSUE TITLE
Yield submit/validate actions from bs-form

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#476]

**Comment by acorncom** [comment]
I'd love to see this as well. In my situation, I'm dealing with a table with rows with multiple columns that contain form fields. Due to the HTML spec (which states that forms have to either be contained inside a single `<td>` or must live outside of the `<table>`, the best way to handle my use case is to have something similar to the following pseudo-code

```hbs
{{! app/component/my-table.hbs}}

{{#bs-form as |form|}}
  <table>
    <tr> ... </tr>
    <tr class="editing">
      <td><input type="text"></td>
      <td><input type="text"></td>
    </tr>
    <tr class="submit-bar">
      <td colspan="2">
        {{! current approach --}}
        <button {{action 'saveRow' rowModel}}>Save</button>

        {{! desired approach --}}
        <button {{action form.submit rowModel}}>Save</button>
      </td>
    </tr>
  </table>
{{/bs-form}}
```

In my current approach I'm needing to trigger a synthetic event to the form (after setting a model property on the form) so that validation gets handled automatically. It's not ideal ... 😛 

@simonihmig Would you be up for a PR for this?

**Comment by simonihmig** [comment]
> Would you be up for a PR for this?

Oh, absolutely! 👍

**Comment by lindyhopchris** [comment]
@acorncom just came looking exactly for this functionality as I need to submit a form via an action.

I see the PR hasn't had any activity on it recently... do you need a hand finishing it off?

**Comment by acorncom** [comment]
@lindyhopchris if you want to clean up my PR, that'd be great! I ended up not needing to handle things this way for my client project and life intervened pretty substantially after that ... 😀 I have no strong druthers about getting credit for the work I've done so far, but yes, let's get it done!

**Comment by svparijs** [comment]
Hey guys, this feature/fix would help my use case alot. Any chance this could get some tlc?

**Comment by lindyhopchris** [comment]
Sorry, this is still on my to-do list for my application but hasn't hit the top of the list yet!

There's a chance I might be able to get it sorted next week, will let you know

**Comment by svparijs** [comment]
@lindyhopchris that would be really great! Thanks so much.

**Comment by svparijs** [comment]
> Sorry, this is still on my to-do list for my application but hasn't hit the top of the list yet!
> 
> There's a chance I might be able to get it sorted next week, will let you know

Any chance you have time this or next week to finish it? This would really help me.

**Comment by lindyhopchris** [comment]
I didn't get to it last week and I'm now on backend stuff. (Problem of being full-stack... keep flicking between Ember and non-Ember stuff.)

I'll look at this if no one else beats me to it, but can't promise when I'll get to it.

**Comment by lindyhopchris** [comment]
@svparijs I'm back on frontend stuff next week and can justifiably prioritise this, as I'll be working on the app where we need it. So you should see some traction next week!

**Comment by svparijs** [comment]
@lindyhopchris I finally see that your one of the guys behind the Laravel JsonApi implementation. Good stuff :)

**Comment by svparijs** [comment]
@lindyhopchris How far along are you with the change? I could really use the change :)

**Comment by jelhan** [comment]
I'm not sure if I'm convinced of the approach discussed here. Feature request described by @acorncom is not only about yielding submit and validate actions but also about passing a model to these actions, which might be different to form's model. Not having these actions bound to form's model anymore, adds a lot of complexity. This concern was also raised implicitly by @simonihmig as a [comment in review of #539](https://github.com/kaliber5/ember-bootstrap/pull/539#discussion_r163361511).

@svparijs Is your use case also about validating/submitting a model that is not form's `model`?

**Comment by svparijs** [comment]
In my cases the submission is based on the form model. Signing up, signing in, etc.

**Comment by simonihmig** [comment]
#789 implements the submit action! :tada: Which seems to be the most important piece here, so closing this. If there is a need for a yielded validate action, then please open another feature request issue!
