### ISSUE TITLE
Click handler to modal's backdrop is not working on iOS

### ISSUE THREAD

**Issue by dajk** [kaliber5/ember-bootstrap#482]
Click to backdrop is not working on iOS (without setting `cursor: pointer` for this area). 
Seems that is working with original Bootstrap.

**Comment by simonihmig** [comment]
@dajk iOS seems to accept click events on divs when the div has `cursor: pointer`, as we know, but also when it has a direct event listener, like `<div onclick=...>`. #488 should fix this.
