### ISSUE TITLE
navbar toggleBreakpoint 'xs' broken for rc.4

### ISSUE THREAD

**Issue by nickschot** [kaliber5/ember-bootstrap#483]
Bootstrap 4 beta 2 changed the `navbar-expand` classes a bit. In order to never collapse the navbar content, the class `navbar-expand` must be added instead of a `navbar-expand-*` class. There currently seems to be no supported way to do this or to fully turn off toggleBreakpoint functionality.

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-rc.4 -> 1.0.0-rc.4
ember-cli: ~2.16.2 -> 2.16.2
bootstrap: ^4.0.0-beta.2 -> 4.0.0-beta.2
bootstrap-sass: n/a
ember-cli-sass: ^7.0.0 -> 7.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
whitelist: undefined
```

**Comment by simonihmig** [comment]
@nickschot The current BS4 implementation of the breakpoint class would set `navbar-expand` if `toggleBreakpoint` is empty (`null` or ""). See https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs4/bs-navbar.js#L45-L53

Wouldn't that work?

Probably needs some better documentation though!

**Comment by nickschot** [comment]
That should work indeed! I tried "false" but isBlank won't cover that of course. I'll test it today and report back if it doesn't work for some reason. Small addition to the docs would "fix" this then.

**Comment by simonihmig** [comment]
Updated the docs, will close this now. Feel free to reopen if required!
