### ISSUE TITLE
How to prevent reloading the navigation or tab content

### ISSUE THREAD

**Issue by kmichek** [kaliber5/ember-bootstrap#487]
Hi. How do I prevent reloading the content of previously populated navigation or tab content, please? If I have 2 tabs, load a master/detail tables on the first one, select a particular item to see the detail - then go to the second tab - and then return to the first one - the content gets reloaded - but I don't want to search my item over. Each tab/navigation has it's own route. Maybe this is a more general Ember question. Thanks. This is my example:

```
{{#bs-navbar as |navbar|}}
  {{#navbar.content class="navbar navbar-fixed-top"}}
    {{#navbar.nav as |nav|}}
        {{#nav.item }}{{#nav.link-to "products"}}Products{{/nav.link-to}}{{/nav.item}}
        {{#nav.item}}{{#nav.link-to "offers"}}Offers{{/nav.link-to}}{{/nav.item}}
    {{/navbar.nav}}
  {{/navbar.content}}
{{/bs-navbar}}
```

**Comment by simonihmig** [comment]
Indeed this is not really specific to ember-bootstrap. You would need to make sure in your model hook, that you do not reload the data you already have. If you are using ember-data you could try to use the `peek*` methods, or use `backgroundReload: false` in https://emberjs.com/api/ember-data/2.14/classes/DS.Store/methods/findRecord?anchor=findRecord. 

A better help channel would be the Ember Slack, at https://ember-community-slackin.herokuapp.com/

**Comment by kmichek** [comment]
Thanks
