### ISSUE TITLE
Support for Bootstrap 4

### ISSUE THREAD

**Issue by brendan-rius** [kaliber5/ember-bootstrap#49]
When will this project support BS4?

**Comment by simonihmig** [comment]
Nothing planned as of yet, sorry! And I probably won't start working on it as long as it is in alpha stage.

**Comment by tylerturdenpants** [comment]
@brendan-rius I have had success using BS4 for over a year with this addon. It takes a little hacking but for the most part it "works"

Note though I don't use every feature so your mileage may vary.

**Comment by hectorh30** [comment]
@tylerturdenpants would you mind sharing the steps to get it working, besides changing the `bower.json`?

**Comment by tylerturdenpants** [comment]
It takes some modification to the addon but not much. For the most part we have an internal addon that just discards the BS3 CSS in favor of BS4. And since BS4 is in SASS you need to disable the LESS compilation.

Hopefully that can help get you started. At a holiday party now so I'll follow up with some better instructions as soon as I get some free time.

**Comment by srvance** [comment]
@simonihmig Are you interested in getting this into the 1.0 release?

**Comment by simonihmig** [comment]
@srvance Priority for 1.0 is everything that would be a breaking change. So basically making the API stable. Additional features can be built on top later. Certainly includes BS4 support.

Why do you ask?

**Comment by srvance** [comment]
I didn't see it on the roadmap despite this issue. I'm starting a new project and the designer I'm working with requested BS4. I could take a pass at it if you like. I'd love to see @tylerturdenpants work on this as a basis.

**Comment by srvance** [comment]
@simonihmig I'm going to start the work moving to BS4. Doing on an `add-bs4` branch off master is fine?

**Comment by simonihmig** [comment]
FYI: the current progress on this is tracked here: #206

**Comment by simonihmig** [comment]
(Experimental) support released with the latest `1.0.0-alpha.5`: http://www.ember-bootstrap.com/#/getting-started/bootstrap-4
