### ISSUE TITLE
Feature Request: Bootstrap Modals

### ISSUE THREAD

**Issue by anilmaurya** [kaliber5/ember-bootstrap#5]
Are you planning to add bootstrap modal or you are going to merge 'modal-native' branch with master ?

**Comment by simonihmig** [comment]
Yes, I do plan that. In fact it will be the next feature coming.

In the modal branch there is a working implementation, that uses the bootstrap.js and encapsulates that in a component. It is fully working already, but lacks tests and documentation. However I do plan to rewrite it as a purely native ember component (modal-native branch), as the other has some drawbacks (does not behave very well in acceptance tests, as the Ember Run Loop is not used internally). 

Bottom line: stay tuned! ;)

**Comment by anilmaurya** [comment]
Great, looking forward to next release. :+1:

**Comment by Kledal** [comment]
Looking forward to this :+1:

**Comment by vasilakisfil** [comment]
Also looking forward to this!

**Comment by jamesdixon** [comment]
@simonihmig great work on the library! I noticed you have a couple of `modal` branches and was curious if these were functional or when you expected to be finished? I'd be more than willing to give a hand if it will help. Let me know!

**Comment by simonihmig** [comment]
@jamesdixon Thanks. Ember-native contains a working implementation, that I have used already for a production project. It lacks however documentation and tests, so I have not merged it yet. You might want to use it if you need it right now, but without any guarantees! ;)

**Comment by jamesdixon** [comment]
Thanks, @simonihmig! I know you said you don't have any documentation, but perhaps you might be willing to share one an example from your application? Thanks!

**Comment by simonihmig** [comment]
Have a look at the dummy application in the tests folder: https://github.com/kaliber5/ember-bootstrap/blob/modal-native/tests/dummy/app/templates/modal.hbs

**Comment by jamesdixon** [comment]
@simonihmig thanks!

**Comment by simonihmig** [comment]
A first implementation is available as of now in v0.5.0!

**Comment by jamesdixon** [comment]
@simonihmig very nice!
