### ISSUE TITLE
New Ember Yarn project cannot use Bootstrap 4

### ISSUE THREAD

**Issue by jrock2004** [kaliber5/ember-bootstrap#504]
Thank you for taking the time to open an issue!

For general questions please use the #e-bootstrap channel on the Ember
community Slack.

For bug reports please include the following section in your issue details.
If you include instructions on how to reproduce the bug or a failing test case
it will make it easier for us to track down the issue you're having.

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-rc.5 -> 1.0.0-rc.5
ember-cli: ~2.17.0 -> 2.17.0
bootstrap: n/a
bootstrap-sass: n/a
ember-cli-sass: ^7.1.2 -> 7.1.2
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 3
importBootstrapFont: true
importBootstrapCSS: false
```

I am trying ti switch to to use bootstrap 4. Getting the following error

`Error: ENOENT: no such file or directory, copyfile '/home/jcostanzo/.cache/yarn/v1/npm-bootstrap-sass-3.3.7-6596c7ab40f6637393323ab0bc80d064fc630498/assets/javascripts/bootstrap/affix.js' -> '/home/jcostanzo/Development/menu-manager/node_modules/bootstrap-sass/assets/javascripts/bootstrap/affix.js'`

**Steps to produce:**

- ember install ember-bootstrap
- ember generate ember-bootstrap --bootstrap-version=4

Downgraded from rc5 to rc4 and it worked. So it seems to be something with rc5

Thoughts?

**Comment by simonihmig** [comment]
As written in Slack, have you tried cleaning up your `node_modules` and the yarn cache? I cannot think of any recent changes that could have caused this, sound more like a local error...
