### ISSUE TITLE
An Ember-CLI deprecation coming soon

### ISSUE THREAD

**Issue by acorncom** [kaliber5/ember-bootstrap#506]
With a recent change made to `ember-cli`, the usage of `nodeModulesPath` in this add-on will start throwing deprecation notices:

- [original issue](https://github.com/ember-cli/ember-cli/issues/7335) (with a link to Ember Observer code search showing this add-on using `nodeModulesPath`)
- [PR that fixes the issue and adds the deprecation warning](https://github.com/ember-cli/ember-cli/pull/7401)
- [EmberObserver code search showing problem lines](https://emberobserver.com/code-search?codeQuery=nodeModulesPath&sort=usages)

I'm not hitting the issue yet, but it's coming down the pipe 😀

**Comment by simonihmig** [comment]
@acorncom thanks a lot for the notice! I just created #507 that should fix this!
