### ISSUE TITLE
BS4 custom controlType without blocks

### ISSUE THREAD

**Issue by basz** [kaliber5/ember-bootstrap#511]
Hi,

I'm trying to move my block implementations of some form.element to components I can use with the controlType property.

I got a file under: `pods/components/bs-form/element/control/select-other/component.js`

and indeed when I use the `controlType="select-other"` the controlComponent method from below is called and returns `bs-form/element/control/select-other`. However simply dropping a template at `pods/components/bs-form/element/control/select-other/template.hbs` won't cut it. The template used is still the input.

So, my question: What's the recommended way to do this?
What are the exacts paths I should use?
How do I pass options?
Nothing in the documentation about this I think? Is i (still) supported?

From the chat; but didn't work for me. `import layout from 'template'` does seem possible at all (see first link)?
```
Yes - you just drop the component into the right folder, then name the `controlType` the name of the component


[8:50] 
Here’s the example from before: https://github.com/mwisner/ember-junkdrawer/blob/master/addon/components/bs-form/element/control/baremetrics.js
https://github.com/mwisner/ember-junkdrawer/blob/master/addon/templates/bs-form/element/control/baremetrics.hbs


[8:51] 
and you use it like

{{form.element controlType="baremetrics" property="dateRange" options=(hash presets=presets)}}


[8:51] 
in your app, you’d just create a component `bs-form/control/my-custom-thing`
```
Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):

```
Npm packages:
ember-bootstrap: git://github.com/kaliber5/ember-bootstrap.git#master -> 1.0.0-rc.5
ember-cli: ^2.16.2 -> 2.16.2
bootstrap: 4.0.0-beta.2 -> 4.0.0-beta.2
bootstrap-sass: n/a
ember-cli-sass: ^7.0.0 -> 7.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
importBootstrapTheme: false
importBootstrapFont: false
```

from form element
```
  /**
   * @property controlComponent
   * @type {String}
   * @private
   */
  controlComponent: computed('controlType', function() {
    let controlType = this.get('controlType');
    let componentName = `bs-form/element/control/${controlType}`;

    if (getOwner(this).hasRegistration(`component:${componentName}`)) {
      return componentName;
    }

    return 'bs-form/element/control/input';
  }),
```

**Comment by donaldwasserman** [comment]
I think that your component needs to be at pods/components/bs-form/element/control/select-other.js

**Comment by basz** [comment]
when I do that, and have an init method in it with a simple alert it won't show. So i think the location is correct, somehow the template that accompanies it isn't used. I hope simon can tell me why...

**Comment by donaldwasserman** [comment]
I’ve never really worked on a pods app before so, I think It’s more with how to import the template in a pods style component. 

Can you render the component outside of the form?

**Comment by basz** [comment]
i got it
