### ISSUE TITLE
Double click to open dropdown

### ISSUE THREAD

**Issue by drewclauson** [kaliber5/ember-bootstrap#52]
I have an issue where I have to double click on a `bs-dropdown-button` in order for the dropdown menu to appear.  Doing some Googling and finding some info about an Angular/Bootstrap project that had the same problem, I removed the `data-toggle="dropdown"` in Chrome inspector and now it only takes one click.  Does this need to be removed from the library or is it more likely that I have my app set up in a weird way?

Thanks!

**Comment by drewclauson** [comment]
FYI, I confirmed by setting the `data-toggle="dropdown"` to a blank string in the code that it now does not require a second click to open.

```
{{#bs-dropdown-button class='btn-primary btn-xs' data-toggle=''}}
     {{fa-icon 'cog'}} <span class="caret"></span>
{{/bs-dropdown-button}}
```

**Comment by simonihmig** [comment]
I cannot see a problem. There is a test app in the addon's repository, that works as expected: https://github.com/kaliber5/ember-bootstrap/blob/master/tests/dummy/app/templates/dropdown.hbs. Also the tests should cover this, so only a single click is needed. 

The `data-toggle` attribute is not evaluated anywhere in ember-bootstrap, it's just there to emulate the expected markup. Is it possible that some other JS library you have included, maybe even the original bootstrap.js (that should not be used when using ember-bootstrap), is interfering here?

**Comment by drewclauson** [comment]
Yep, you're exactly right.  I was using bootstrap.js before I added this addon.  Thanks for the response and I'm sorry for the confusion - I see the note in the readme now where it says no use of bootstrap.js...
