### ISSUE TITLE
Validation for block form form.element

### ISSUE THREAD

**Issue by andrewheartsxd** [kaliber5/ember-bootstrap#527]
I'm having trouble getting validation to work with block form form.elements. Validation with non-block form elements works fine. I'm using the Bootstrap 4 option with `ember-bootstrap 1.0.0-rc.5`, `ember-cp-validations 3.5.1`, and `ember-bootstrap-cp-validations 1.0.0-alpha.0`. 

My template and model can be found here: https://gist.github.com/andrewheartsxd/352b124a50f15487461aab6b557b0dcf . 

I am under the impression that automatic validation with ember-cp-validations should work with block form form.elements from here: https://github.com/kaliber5/ember-bootstrap/issues/189. Am I missing something and has anyone else run into this? Thanks!

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.0.0-rc.5 -> 1.0.0-rc.5
ember-cli: ~2.16.2 -> 2.16.2
bootstrap: ^4.0.0-beta.2 -> 4.0.0-beta.2
bootstrap-sass: n/a
ember-cli-sass: ^7.1.2 -> 7.1.2
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
@andrewheartsxd looking at your gist, I don't see anything wrong there AFAICT. And yes, this should definitely work. Will have to investigate this...

**Comment by simonihmig** [comment]
@andrewheartsxd I was not able to reproduce this. When I copy the block form element from your gist into this addons dummy app [here](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/dummy/app/templates/demo/forms.hbs#L69), then it works without problems!? 

This is using the latest v1.2.0 though, but I cannot remember that anything related was fixed from your `rc.5` version to now... 🤔

**Comment by wukongrita** [comment]
Hi, I'm getting the same issue. It only affect on Bootstrap 4, the validation error isn't showing up. When I switch to Bootstrap 3, it working fine..

The form won't submit, because there is an error; it just not showing the error message..

Any help?

**Comment by simonihmig** [comment]
As stated above, I did test this and was not able to reproduce. If some of you is able to create a minimal reproduction (using the latest ember-bootstrap release!), that would be very helpful!

**Comment by wukongrita** [comment]
@andrewheartsxd have you solve this?

**Comment by simonihmig** [comment]
I am closing this one in favor of #578, which describes the same problem I believe.
