### ISSUE TITLE
NavbarToggle delete button class btn btn-secondary

### ISSUE THREAD

**Issue by absemetov** [kaliber5/ember-bootstrap#531]
When use {{navbar.toggle}}
Returns:
```
<button type="button" id="ember692" class="btn navbar-toggler btn-secondary collapsed ember-view">  
<span class="navbar-toggler-icon"></span>
</button>
```

**Comment by simonihmig** [comment]
Sorry, given your (very short) description, I don't understand what the problem is or what you are suggesting.

FWIW, `navbar.toggle` is a button, so you can set `type="secondary"` or any class as usual (`class="foo"`), if that is what you need.

**Comment by absemetov** [comment]
I wont set only "navbar-toggler" class in button.
http://getbootstrap.com/docs/4.0/components/navbar/

**Comment by absemetov** [comment]
@simonihmig  Thanks
