### ISSUE TITLE
Sending action to Modal from a child component?

### ISSUE THREAD

**Issue by OakBehringer** [kaliber5/ember-bootstrap#54]
I have a child component (rendered in the modal body) that needs to be able to close the modal in which it is wrapped. Of course, the component shouldn't need to know if it's wrapped in the modal. In the child component, was thinking I could send the modal's close action, to close the modal. But that's not working. 

```
{{#bs-modal footer=false}}
    {{some-component}}
{{/bs-modal}}
```

Where some-component has this: 

```
actions: {
    cancel() {
        this.sendAction('close');
    }
}
```
Not working. Nor can I pass the close action into the child:

`{{some-component close="close"}}`

Suggestions? Help? Thanks!

**Comment by simonihmig** [comment]
That's not how it works in Ember. The action is sent to the targetObject, and that would be your controller (or a parent component). Create an action on your controller and use it to set the `open` property of the modal to false to close it!

**Comment by OakBehringer** [comment]
Hi Simon! Thank you for the reply. 

I think you're contradicting yourself? My child component does this:

`this.sendAction('close');`

You're suggesting that, on my controller, **or parent component**, I have this, to handle the action:

```
actions: {
    close() { // change modal's open property }
}
```

But the bs-modal component IS a **parent component**. And it has a close action, which I interpret to do exactly what I want. 

But obviously I'm missing something. 

Thank you in advance for your help!

**Comment by simonihmig** [comment]
Ok, there is a misunderstanding that I might be responsible for...

Yes, your component is a child of the modal, at least in terms of the DOM. But in terms of how Ember actions bubble up, it is NOT! 

When you define your component in a `foo.hbs` template, its action target is the fooController, no matter how you have nested the component within the DOM! Given an invocation like `{{my-component close=(action "bar")}}` the FooController would have to implement the `bar` action. This is standard Ember stuff,
nothing to do with ember-bootstrap in particular.

There could be another way to support your use case, when the modal component would yield itself to the block template, but this is not the case right now, so you would have to modify the `open` property in your controller action as suggested!

**Comment by OakBehringer** [comment]
Gotchya - and that's what I did. Thank you for your continued attention to my query. Have a good one.
