### ISSUE TITLE
[FEATURE] add focusIn and focusOut events to element control

### ISSUE THREAD

**Issue by fran-worley** [kaliber5/ember-bootstrap#548]
I'm in the process of building a datepicker control in the same way that you've implemented your addon for ember-power-select.

In doing so, I wanted to render a `bs-form/element/control/input ` and listen to the `focusIn` event to open my datepicker and on `focusOut` close it. These event's aren't public on either the element or it's control, though in my case I'm interested in setting it on the control itself.

Obviously we'd need to ensure that the event on the control is still handled as expected by the wrapping element...

**Comment by simonihmig** [comment]
If I understand you right, you want to create a `bs-form/element/control/datepicker` (or similar) component and use `bs-form/element/control/input` internally in its template, right? 

As the `focusin` event bubbles up the DOM tree, you should be able to listen to this event in your `bs-form/element/control/datepicker`, with a simple event handler method like this:
```js
...
focusIn(e) {
  // handle the e event
}
```

Hope that works for you!?

**Comment by fran-worley** [comment]
@simonihmig thank you for coming back to me - I've actually resolved this like you suggest by following the [example here](https://github.com/kaliber5/ember-bootstrap-power-select/blob/master/addon/components/bs-form/element/control/power-select.js)

Is this way of defining custom control officially supported as it's not documented.

**Comment by simonihmig** [comment]
Good to hear @fran-worley! :)

> Is this way of defining custom control officially supported as it's not documented.

Good question! It is not really public API yet, and thus not documented. But it is used (not only be me! 😉), so it won't go away, at least not without a prior deprecation and a clear alternative. So it should be "ok-ish" to use! Hope that's good enough for you!? 😬
