### ISSUE TITLE
Can't auto-focus input fields in modal

### ISSUE THREAD

**Issue by bendemboski** [kaliber5/ember-bootstrap#55]
Can you explain the rationale behind [this](https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-modal.js#L444)?

It seems that when the transition is complete, we are triggering a focus event on the modal root element. I have some code that gives focus to an input field in my modal from the openedAction, but when fade animation is enabled, this line of code de-focuses it as soon as the animation is complete.

What was the intent of this line, and is there a way that I can auto-focus fields in my modal?

**Comment by simonihmig** [comment]
This is adopted from the original bootstrap.js, which does similiar things. The rationale is to have the modal focused so you can listen to key events, in this case the escape key to close the modal.

Maybe it makes more sense to have a `openAction` + `openedAction`, similiar to `closeAction`/ `closedAction`, the latter being fired after the transition has completed and the modal has received focus. This way you can set focus to another element. 

As long as this element is a child of the modal, and you do not call `event.stopPropagation()` on key events, closing the modal via the escape key should probably still work...

**Comment by bendemboski** [comment]
Ah, gotcha. The ```openAction```/```openedAction``` would work, although I think it would break backwards compatibility for anybody depending on ```openedAction``` firing before the transition completes (like if they want to make some changes to the DOM before the animation reveals it).

Another option that would solve my narrow use case would be to support the ```autofocus``` attribute. So instead of

```javascript
this.get('modalElement').trigger('focus');
```

do

```javascript
let modalElement = this.get('modalElement');
let focusElement = modalElement.find('[autofocus]');
if (focusElement.length === 0) {
  focusElement = modalElement;
}
focusElement.trigger('focus');
```

That way if somebody wants some element in the modal to get focus they can just give it the ```autofocus``` attribute.

I'd be happy to put together PRs for either/both of these changes if you a) are okay with breaking compatibility and b) think this autofocus behavior is a good idea.

**Comment by simonihmig** [comment]
I would not be bothered too much about backwards compatibility if the changes make sense, as the addon is in beta stage (0.x) anyway, so I do not feel I have to carry unnecessary stuff along because of compatibility.

Your proposed change using the `autofocus` attribute would be a clever solution as well. I would be glad if you could contribute a PR. If you do so, please add a simple component integration test for this use case, and add a little remark to the component class docs
