### ISSUE TITLE
toggle accordion

### ISSUE THREAD

**Issue by dbinetti** [kaliber5/ember-bootstrap#56]
is there a property to toggle the accordion panel?  forgive me, this is all new; using the example I can get them all to expand and close on switch, but i can't collapse any individual item once expanded -- i can only collapse by expanding another...

**Comment by simonihmig** [comment]
Setting the `selected` property to `null` should achieve what you want, doesn't it?

**Comment by dbinetti** [comment]
no, it doesn't.  perhaps my ignorance is showing?

here's what i have:

```
 {{#bs-accordion selected=selected collapsed=collapsed}}
     {{#bs-accordion-item value="1" title="One"}}
        <p>One</p>
     {{#bs-accordion-item}}

     {{#bs-accordion-item value="2" title="Two"}}
        <p>Two</p>
     {{#bs-accordion-item}}
 {{/bs-accordion}}
```

They all start collapsed, and then expand as I click, closing the prior (as expected.)   But if i want to close each individually by clicking on the title that's not possible.  

Do i need add an action on the controller?  That seems to defeat the purpose, but I can't see anything in docs that makes it clear to me.

**Comment by simonihmig** [comment]
ok, did get what you mean in the first place... indeed there seems to be an issue here, clicking an expanded item should close it, which it does not do currently. Will need to fix this!

**Comment by dbinetti** [comment]
Oh, whew!  Glad it wasn't me! :-)  thanks
