### ISSUE TITLE
Switching between tabs a few times causes pane to "collapse"

### ISSUE THREAD

**Issue by adambedford** [kaliber5/ember-bootstrap#560]
I'm running into an issue where  switching tabs a few times causes the tab pane to "collapse". Looking at the DOM, all three of my tab panels are present, however they all have `display: none`. 

I have forms in all of my tab panes and the "collapsing" happens when I focus on an input in the tab pane.

**Comment by simonihmig** [comment]
@adambedford I was not able to reproduce this, so it's hard to guess what's happening there. Would you be able to create a minimal reproduction repo that shows this defect?

**Comment by jelhan** [comment]
Will close now as there wasn't any update for nearly 1 1/2 years.
