### ISSUE TITLE
Popper having trouble with parent div overflow

### ISSUE THREAD

**Issue by danidr** [kaliber5/ember-bootstrap#561]
Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
ember-bootstrap: 1.2.1 -> 1.2.1
ember-cli: ^2.18.2 -> 2.18.2
bootstrap: 4.0.0 -> 4.0.0
bootstrap-sass: n/a
ember-cli-sass: 7.1.7 -> 7.1.7
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
importBootstrapFont: false
```
**EDIT:** See end of post.

Hello,
Reporting quite a worrying bug here: if dropdown is contained inside of a div which is shorter than the container of the dropdown, the overflow is simply not shown.

<img width="304" alt="calendar" src="https://user-images.githubusercontent.com/1716741/37035251-3a8a2cb2-214c-11e8-88a1-537afcf9e2fd.png">
Example attached. The calendar should be fully visible inside of the dropdown (and it is in case the container div is taller), but since the container div is smaller than it should, the dropdown div is cut out.
I suspect it's due to using popper instead of ember-wormhole.
Thank you,

Daniele

**Edit:**
Apparently, this bug is due to liquid-fire. I was using a `liquid-outlet` to wrap the template where I was using the dropdown, and liquid-fire probably makes use of a overflow: hidden for its features, therefore breaking ember-popper. I'll just disable liquid-fire for now.

**Comment by simonihmig** [comment]
@danidr #570 will allow you to work around this issue! Thanks for reporting!
