### ISSUE TITLE
how to close bootstrap modal in controller code?

### ISSUE THREAD

**Issue by dyh333** [kaliber5/ember-bootstrap#574]
as the title, I follow the [demo](http://www.ember-bootstrap.com/#/components/modal) to add a modal, after submit, I hope to close the modal by myself in the controller, but how ? thanks

**Comment by donaldwasserman** [comment]
You need to set the `open` property in the modal to a falsey value.  See http://www.ember-bootstrap.com/#/components/modal. 

So as a quick example (this is just illustrative, don't copy and paste).

```hbs 
{{bs-model open=isOpen}}
```

```js
actions: {
  closeModal() {
    this.set('isOpen', false);
  }
}```

**Comment by simonihmig** [comment]
Thanks @donaldwasserman for answering this! @dyh333 hope this was helpful!? 
Closing this for now. Also for general questions (rather than bug reports), feel free to visit the #e-bootstrap channel in the Ember Slack!

**Comment by dyh333** [comment]
thanks all.
