### ISSUE TITLE
BS4: validation support for custom form controls

### ISSUE THREAD

**Issue by nickschot** [kaliber5/ember-bootstrap#578]
~~It's been a couple of months since I tried to do this, but I think it's still a thing.~~

~~Currently it seems there is no support for adding validation support to custom elements (e.g. ember-bootstrap-power-select).~~

After some more digging the problem is BS4 related. BS4 changed the places where validation classes are added. As an example:

BS3
```html
<div class="form-group has-error">
    <label class="control-label">Input with error</label>
    <input type="text" class="form-control">
    <span class="help-block">Some validation error</span>
</div>
```

BS4
```html
<div class="form-group">
    <label >Input with error</label>
    <input  class="form-control is-invalid">
    <div class="invalid-feedback">Some validation error</div>
</div>
```

The biggest difference is in the way the CSS selectors to display the validation works. In BS3 the wrapping form-group has a class denoting that an error should be shown, so nesting of form elements doesn't matter (i.e. the validation "help-block" doesn't need to be next to the `input`).

In BS4 the CSS selector is as follows: `.form-control.is-invalid ~ .invalid-feedback` which means it should be a sibling of the form-control. Now in the default cases this isn't a problem, but when wanting to (nicely and reusably) add a custom form control for i.e. a currency field you get the following:

Usage:
```hbs
{{form.element controlType="currency" label="Budget" property="budget" }}
```

Resulting form element HTML:
```html
<div class="form-group">
    <label class="ember-view">My Currency Control</label>

    <div class="input-group">
        <div class="input-group-prepend">
            <span class="input-group-text">$</span>
        </div>
        <input class="form-control is-invalid" type="text">
    </div>

    <div class="invalid-feedback">Budget must be positive</div>
</div>
```

Now `.invalid-feedback` is in the wrong place for the validation styles to work (as it is not being rendered by the control).

I cannot yet think of a clean solution within the established components.

**Comment by nickschot** [comment]
I'll be working on this soon, will report back if it worked. I probably missed that showValidationOn. Is that in the docs? Else we might want to add it.

**Comment by simonihmig** [comment]
> Is that in the docs?

Yes, at least in the API docs: http://www.ember-bootstrap.com/api/classes/Components.FormElement.html#property_showValidationOn

> Else we might want to add it.

It probably makes sense to mention this in the context of custom controls. Tbh, there is quite a lot actually that could be improved for the docs...

**Comment by wukongrita** [comment]
@nickschot have you solve this?

**Comment by nickschot** [comment]
@wukongrita no, ember-bootstrap needs to be updated to support this.

**Comment by elgordino** [comment]
I got a workaround going for a situation where I wanted to add a custom input group, which is to add the `el.validation` state as a class to the element which is a sibling before the `.invalid-feedback` element. 

eg
```hbs
{{#form.element 
    class=formElement.class
    label=formElement.label
    helpText=formElement.help
    property=formElement.property
    showValidationOn=formElement.showValidationOn
    as |el|}}
    <div class='input-group {{el.validation}}'>
        <div class="input-group-prepend">
            <span class="input-group-text">{{options.prepend}}</span>
        </div>
        {{el.control}}
        <div class="input-group-append">
            <span class="input-group-text">{{options.append}}</span>
        </div>
    </div>
{{/form.element}}
```
Then in the css
```css
.input-group.error ~ .invalid-feedback {
      display: block;
 }
```

**Comment by simonihmig** [comment]
I have an extremely simple but seemingly effective solution: #603 
Anyone here have any opinions on this approach?

Btw, we are not the only ones being unhappy with BS4's behavior, as you can see at this long thread: https://github.com/twbs/bootstrap/issues/23454

Here is an example input group, that worked well with the solution above: https://github.com/kaliber5/ember-bootstrap/blob/2f94f1a6eb7c74b017d4e76dba31535ba8eee8e4/tests/dummy/app/templates/demo/forms.hbs#L109-L116

**Comment by nickschot** [comment]
That's a long thread! I'm fine with this solution 👍 . Seems like the simplest way to reliably "fix" it.

**Comment by stark7** [comment]
hey @simonihmig any idea on how to make .is-valid apply to the control <input> under the .input-group div?

**Comment by shafayshahid123** [comment]
Actually i'm using two input in form-group but when i'm going to use help-block it's working if any of two option is filled or select but i want it two working with particular input.

<div class="form-group">
    <div class="input-group">                  
        <span class="input-group-addon">
             <select class="form-control select2" name="calling_code" id="calling_code" required="">
                 <option>.....</option>
              </select>
         </span>
         <input name="mobile_number" class="form-control input-lg flat" placeholder="{{ trans('theme.placeholder.mobile_number') }}" type="text" required/>
     </div>
     <div class="help-block with-errors"></div>
</div>
