### ISSUE TITLE
NavBar.Toggle is documented as extending from Button, but does not

### ISSUE THREAD

**Issue by seansellek** [kaliber5/ember-bootstrap#580]
The `navbar-toggle` component is documented as extending from Component.Button, but extends from base Component.

https://github.com/kaliber5/ember-bootstrap/blob/a2d0888257e3faa5bbcc090cb65632510b94ac24/addon/components/base/bs-navbar/toggle.js#L15

https://github.com/kaliber5/ember-bootstrap/blob/a2d0888257e3faa5bbcc090cb65632510b94ac24/addon/components/base/bs-navbar/toggle.js#L18

**Comment by ynotdraw** [comment]
OK if I pick this one up?

**Comment by simonihmig** [comment]
@ynotdraw sure, go ahead! 👍
