### ISSUE TITLE
BS4 navbar always has .bg-light class regardless of given type

### ISSUE THREAD

**Issue by kitsuneyo** [kaliber5/ember-bootstrap#585]
If I make a dark Bootstrap 4 navbar like this:

```
{{#bs-navbar type="dark" as |navbar|}}
  #stuff
{{/bs-navbar}}
```

Then I get invisible light text on a light bg, with HTML that includes the `.bg-light` class like this:

```
<nav class="navbar navbar-dark navbar-expand-lg bg-light ember-view" id="ember685">
```

If I make a light navbar (or if I don't set the `type` property at all), like this:

```
{{#bs-navbar type="light" as |navbar|}}
  #stuff
{{/bs-navbar}}
```

...then I get dark text on a light background with this HTML:

```
<nav class="navbar navbar-light navbar-expand-lg bg-light ember-view" id="ember685">
```

In short, it seems the navbar `type` property isn't working because it should set a `.bg-dark` class if `type="dark"`.

Manually setting a `bg-dark` class like this...

```
{{#bs-navbar type="dark" class="bg-dark" as |navbar|}}
```

...doesn't override the automatically-set `bg-light` either.

**Comment by simonihmig** [comment]
You should use the `backgroundColor` property to set the `bg-*`class: http://www.ember-bootstrap.com/api/classes/Components.Navbar.html#property_backgroundColor

**Comment by kitsuneyo** [comment]
Thanks, I totally missed the backgroundColour property. I still think it would make sense to set a sensible bg class when type is dark, but I can appreciate it's not a top priority. Thanks for your great work on this add-on.
