### ISSUE TITLE
Set transitions to 0 during testing

### ISSUE THREAD

**Issue by kpfefferle** [kaliber5/ember-bootstrap#595]
I love how this addon makes the Bootstrap components available in a native Ember fashion. It's been great for client projects where they are used to having the conveniences of Bootstrap components but are moving to an Ember front-end.

One improvement I'd love to see is to set all of the transition durations to 0 when the consuming app is running in the test environment. I have a number of acceptance tests which are exercising ember-bootstrap components (like the modal), and the test suite runs much slower with the default transition timings than it does when I override the transition durations to 0.

~I've tried extending the `{{bs-modal}}` component to override the transition durations in testing myself, but when I create the following file:~

```js
// app/components/bs-modal.js
import BSModalComponent from 'ember-bootstrap/components/bs-modal';

export default BSModalComponent.extend({
});
```

~Then I get the following error:~

```sh
Uncaught Error: Cannot instantiate a component without a renderer. Please ensure that you are creating <myapp@template:components/bs-modal::ember727> with a proper container/registry.
```

~I haven't had time as of yet to investigate this further, but it seems to indicate that there's something in the way ember-bootstrap's components are being defined that makes extending them difficult.~

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.2.1 -> 1.2.2
ember-cli: ~3.1.4 -> 3.1.4
bootstrap: ^4.0.0 -> 4.1.1
bootstrap-sass: n/a
ember-cli-sass: ^7.1.7 -> 7.1.7
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
Thanks for your feedback! 

The issue you have with extending a component is weird. We do this in our apps all the time like you did it, never had any issue like yours!? 🤔

For the timeout, I think something like that makes sense. Not sure though if we should totally remove the asynchronicity, which might be a breaking change for some. Also there might be tests that want to assure that transitions are correctly waited for (like transitioning away on modal's `onHidden` rather than `onHide`). So maybe reduce to something like 10ms?

**Comment by kpfefferle** [comment]
I went back this morning and tried extending the component as described above, and it works. I was probably making a mistake last week such as not restarting my Ember server or something, so I've crossed out that section above.

Any delay in the transition is going to slow down test suites (and moreso as more tests are added). Setting the transition to 0 just avoids artificial delay; it doesn't change the order of actions being called. I can't imagine a test scenario where you'd assert something in the middle of the transition, or how such an assertion would reliably work even today. 🤔

**Comment by kpfefferle** [comment]
For anyone who may be curious how I'm handling this for now:

```js
// app/components/bs-modal.js
import BSModalComponent from 'ember-bootstrap/components/bs-modal';
import ENV from 'myproject/config/environment';

export default BSModalComponent.extend({
  backdropTransitionDuration: ENV.APP.MODAL_BACKGROUND_TRANSITION_MS,
  transitionDuration: ENV.APP.MODAL_TRANSITION_MS
});
```

```js
// config/environment.js
module.exports = function(environment) {
  let ENV = {
    // ...
    APP: {
      // ...
      MODAL_BACKGROUND_TRANSITION_MS: 150,
      MODAL_TRANSITION_MS: 300
    },
    // ...
  };

  // ...
  if (environment === 'test') {
    // ...
    ENV.APP.MODAL_BACKGROUND_TRANSITION_MS = 0;
    ENV.APP.MODAL_TRANSITION_MS = 0;
  }
  // ...
};
```

**Comment by simonihmig** [comment]
You are right about this! I tried this in #604, and locally all tests were passing without any changes. So this should be safe for consuming apps as well.
