### ISSUE TITLE
Outlet from one nav.item to another

### ISSUE THREAD

**Issue by kmichek** [kaliber5/ember-bootstrap#598]
Hi,
in master-detail pattern it's normal to outlet from master's list section on the left to detail's content section on the right. But, would it be possible to use one nav.item as a master and another nav.item as the outlet detail, please? For example:
{{#bs-nav type="tabs" as |nav|}}
   {{#nav.item}}{{#nav.link-to "orders"}}Orders{{/nav.link-to}}{{/nav.item}}
   {{#nav.item}}{{#nav.link-to "order"}}Order{{/nav.link-to}}{{/nav.item}}
{{/bs-nav}}
Say, in the Orders tab I have a list of Orders. When selecting one order, I would like to swap to another tab - Order detail to display its order lines. Or, is it possible to make a tab selected programmatically, please?
Thanks. Karel

**Comment by simonihmig** [comment]
You can programmatically make nav items active, by overriding the default behavior of `active`. See https://www.ember-bootstrap.com/api/classes/Components.NavItem.html#property_active.

Hope that helps!?

**Comment by kmichek** [comment]
Thank you for your response. I'll try to override it as suggested. If I succeed I'll post the code. 
Karel
