### ISSUE TITLE
No transition for bs-collapse

### ISSUE THREAD

**Issue by drakej** [kaliber5/ember-bootstrap#629]
Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^1.2.0 -> 1.2.0
ember-cli: ~2.14.2 -> 2.14.2
bootstrap: ^4.0.0 -> 4.0.0
bootstrap-sass: n/a
ember-cli-sass: ^6.2.0 -> 6.2.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

https://www.ember-bootstrap.com/#/components/collapse

^ On this demo if you "Hide" the collapsed content it has no transition of 350 ms. It just abruptly closes.

Contrast that with Bootstrap 4's demo:

https://getbootstrap.com/docs/4.1/components/collapse/#example

Also I don't understand why there's a configurable called transitionDuration when that doesn't exist in bootstrap itself. It seems like the entire solution is a rewrite in terms of the javascript behavior and the only bootstrap aspect is the CSS itself.

**Comment by simonihmig** [comment]
> ^ On this demo if you "Hide" the collapsed content it has no transition of 350 ms. It just abruptly closes.

I cannot reproduce this, works for me. 🤔 
Which browser are you using?
Does it happen always, or is it somewhat timing related?

**Comment by scottharris86** [comment]
Hi I'd like to maybe help reproduce this issue. I have the same issue after updating from 1.0 to 2.5.
in 1.0 and on bootstrap website using the link provided above. theres a nice smooth transition where the collapse transitions down to open state. in 2.5 on your demo site and in my app. there is not a transition. it just abruptly opens.. theres no animation anymore. maybe thats the word were looking for? animation? also for full disclosure im using an accordian but the behavior should be the same for both. let me know what i can do to help. Thank you

**Comment by simonihmig** [comment]
Hm, this is weird. At the time I was trying to reproduce this, it was *definitely* working right, at least what I was seeing in my browser. But now indeed there is no transition. This might be caused or exacerbate by some recent changes!?

Will investigate...
