### ISSUE TITLE
Dropdown: no wormhole container found in test mode

### ISSUE THREAD

**Issue by bgentry** [kaliber5/ember-bootstrap#633]
Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^2.0.0 -> 2.0.0
ember-cli: ~3.3.0 -> 3.3.0
bootstrap: ^4.1.2 -> 4.1.2
bootstrap-sass: n/a
ember-cli-sass: ^7.1.7 -> 7.1.7
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
insertEmberWormholeElementToDom: false
```

I have disabled the optional `application-template-wrapper` feature like so in my `optional-features.json`:

```json
{
  "application-template-wrapper": false
}
```

When I then try to trigger an ember-bootstrap dropdown with `renderInPlace=false`, I get this error (only in test mode):

```
Uncaught Error: Assertion Failed: ember-popper with popperContainer selector "#ember-bootstrap-wormhole" found 0 possible containers when there should be exactly 1
```

The DOM is not getting the wormhole container element appended to it in tests, though everything works fine in my app in dev / production. I have to use `renderInPlace=false` because otherwise the menu is positioned incorrectly, which might be another issue (shown here https://github.com/kaliber5/ember-bootstrap/pull/570#issuecomment-407272255).

Upon further digging, I can see that the element gets added [here](https://github.com/kaliber5/ember-bootstrap/blob/master/index.js#L273) and there is explicitly an if clause to avoid inserting if we're in a test env.

I was also able to work around this by setting the config `insertEmberWormholeElementToDom` to `false`, and then adding my own wormhole element to my `application.hbs`. It's possible this merely needs documentation, or you might consider this a bug.

**Comment by simonihmig** [comment]
Hm, IIRC I added the `config.environment !== 'test'` check for ember-bootstrap's own tests, but that should better not have affected apps, it seems to be a bug then...

Are you sure this is related to `application-template-wrapper` though? I fail to see the connection there, unless I'm missing something...

**Comment by bgentry** [comment]
Alright, I managed to create [a reproduction](https://github.com/bgentry/ember-bootstrap-wormhole-bug) for this. It doesn't appear to be related to `application-template-wrapper` as I suspected. In that example app, you can see the same error message triggered by the dropdown (in tests).

I would rename this issue to something more descriptive but I'm not sure how to describe this issue atm.

**Comment by simonihmig** [comment]
#647 should fix this. I wrote a short explanation there...

Thanks for reporting!

**Comment by bgentry** [comment]
@simonihmig wow, awesome, thank you! :pray:
