### ISSUE TITLE
Build Error occurs after installing ember-bootstrap-4

### ISSUE THREAD

**Issue by prashanth-j** [kaliber5/ember-bootstrap#634]
Hi,

Recently installed the ember-bootstrap-4, encountered build error,  Not sure what exactly the reason, tried clearing cache from root node of app, again ran npm i.

File to import not found or unreadable: ember-cli-bootstrap-4/bootstrap
Parent style sheet: W:/src_veekshan/veekshan/veekshan-ui-app/tmp/sass_compiler-input_base_path-gtqX9elz.tmp/app/styles/app.scss

**Comment by simonihmig** [comment]
You are on the wrong repo here, this is the `ember-bootstrap` package, but your error comes from `ember-cli-bootstrap-4`: https://github.com/kaermorchen/ember-cli-bootstrap-4
