### ISSUE TITLE
bs-modal not working correctly in IE 11

### ISSUE THREAD

**Issue by santanapaulo** [kaliber5/ember-bootstrap#642]
bs-modal is working fine in Google Chrome (I am unit testing it). However, in Internet Explorer 11 I am getting a failure in my tests (seems like the modal are not being displayed). It occurs only in my tests, once I have tried to test manually and it works well.

Is this a bug? Does someone had already had this same issue as I?

**Comment by simonihmig** [comment]
All components of this addon are fully tested, also in IE11 (using Saucelabs). And given that you see it working correctly outside of tests, I would guess something with your tests is not working right, but hard to tell without seeing any code! 🤨

**Comment by santanapaulo** [comment]
![capturar](https://user-images.githubusercontent.com/15819810/43914301-e0ca6a22-9bdd-11e8-9fa2-ab7348626074.PNG)
The first image is how my assertion is built. In Google Chrome, when I debug I can see the value of my displayedMessage. However, in IE 11, I am getting empty value for it.

![capturar2](https://user-images.githubusercontent.com/15819810/43914321-f2ac4350-9bdd-11e8-88cf-0367dab7b8cd.PNG)
The second one shows how I implemented my modal.hbs.
I have no idea why it's working in one browser and doesn't in another one.

**Comment by simonihmig** [comment]
Sorry for keeping this around so long! But I will need a reproduction if I should dig into it. Will close this for now, as the addon is fully tested in IE11 as said before. But feel free to reopen if you have a reproduction to share!
