### ISSUE TITLE
Use bootstrap-sass & ember-cli-sass instead of bootstrap

### ISSUE THREAD

**Issue by gcusnieux** [kaliber5/ember-bootstrap#65]
In situations where you prefer to use another strategy for importing Bootstrap CSS... I

**Comment by simonihmig** [comment]
I am not sure I understand what you are suggesting?

You can prevent importing the bootstrap CSS (see http://kaliber5.github.io/ember-bootstrap/getting-started/#opting-out-of-bootstrap-css) and follow whatever other strategy you want...
