### ISSUE TITLE
[v2.x] Compatibility with tim-evans/ember-file-upload?

### ISSUE THREAD

**Issue by fran-worley** [kaliber5/ember-bootstrap#672]
Output from `ember bootstrap:info` 

```
Npm packages:
ember-bootstrap: ^1.2.2 -> 1.2.2
ember-cli: ~3.4.3 -> 3.4.3
bootstrap: ^4.1.3 -> 4.1.3
bootstrap-sass: n/a
ember-cli-sass: ^7.2.0 -> 7.2.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

I can replicate this issue in all versions > 1.2.2

I have the following component which includes a file upload dropzone & file browser button https://github.com/tim-evans/ember-file-upload 

```hbs
{{#bs-card collapsible=true collapsed=collapsed as |card|}}
  {{#file-dropzone
    name=modelName
    ondragenter=(action (mut dragActive true))
    ondragleave=(action (mut dragActive false))
  as |dropzone queue|}}
    {{#card.header}}
      {{#bs-dropdown as |dd|}}
        {{dd.button
          type="success"
          class="mr-2"
          icon="fa fa-plus"
        }}
        {{#dd.menu as |ddm|}}
          <button type="button" class="dropdown-item">
          {{#file-upload 
            name=modelName
            multiple=true
            onfileadd=(action "upload")
          }}
            <span>Upload a file</span>
          {{/file-upload}}
          </button>
          <button type="button" class="dropdown-item" {{action (mut showTemplateModal) true}}>
            Create from template
          </button>
          <a class="dropdown-item">Send an email</a>
        {{/dd.menu}}
      {{/bs-dropdown}}
      <h4>Documents</h4>
    {{/card.header}}

    {{#card.collapse}}
      <div class="card-body">
          <p class="card-text">
          {{#if dropzone.active}}
            {{#if dropzone.valid}}
              Drop to upload
            {{else}}
              Invalid
            {{/if}}
          {{else if queue.files.length}}
            Uploading {{queue.files.length}} files. ({{queue.progress}}%)
          {{else}}
            Drag and drop files onto this area to upload.
          {{/if}}
        </p>
      </div>
    {{/card.collapse}}
  {{/file-dropzone}}
{{/bs-card}}
```

My `{{file-dropzone}}` cannot connect to the`{{file-upload}}` when the upload component is inside the `{{bs-dropdown}}` component.  It doesn't detect the `multiple` setting on the file-upload component, or trigger the `onFileAdd` action. 

If I take the `{{file-upload}}` component out of the dropdown, everything works as expected.
If I revert ember-bootstrap back to v1.2.2 then everything works as expected. 

Any clues as to what's changed that could affect this?

**Comment by simonihmig** [comment]
@fran-worley to prevent misunderstandings: it stops working with any 2.x version, but works *including* 1.2.2, is that right? Because according to the changelog, 1.2.2 had some Dropdown-related changes, but none so for 2.0... 🤔

Not sure though what the root issue might be. The only thing that comes to my mind, is that the dropdown menu might be rendered in a wormhole (different place of the DOM, to prevent clipping issues) using `-in-element`, but this does not seem to be the case here, as `renderInPlace` is not set and by default `true`...

@tim-evans any idea?

**Comment by fran-worley** [comment]
@simonihmig thanks for coming back to me so quickly it all works at 1.2.2. I've tried all 2.x versions and none of them work. I'll run through the 1.2.2 - 2.0.0 diff and see if anything jumps at me!

Is there anyway to explicitly link the dropzone to the queue? I wondered if a workaround would be to create the queue in the component js with the `onFileAdd, name, multiple == true` settings and then pass that into the dropzone and file upload field?

**Comment by simonihmig** [comment]
> Is there anyway to explicitly link the dropzone to the queue? I wondered if a workaround would be to create the queue in the component js with the onFileAdd, name, multiple == true settings and then pass that into the dropzone and file upload field?

Although I did use `ember-file-upload` recently by coincidence, I am not really aware of the details to be able to answer this question.

**Comment by fran-worley** [comment]
:D My bad - I forgot which repo I was posting in!! I'll keep looking and report back if anything jumps out at me, but on the basis that I've made no changes to the app other than to bump ember-bootstrap, one of the changes to dropdowns since 1.2.2 must be causing the issue.

**Comment by fran-worley** [comment]
@simonihmig I think you've cracked it! Since 2.0.0 the dropdown component isn't rendered until it is opened (which makes sense so 👍). Due to the way that the file uploader works, all upload magic is actually carried out by the file-upload component that is inside the dropdown which now isn't being rendered!

I've proved this as if you open the dropdown and then drop files into the drop-zone the upload works as expected.

It might be worth making a note in the changelog that this affects 2.0.0 as well as 2.1.2 incase it catches anyone else out. I assume there is no way of turning off the lazy rendering for specific dropdowns?

**Comment by simonihmig** [comment]
Hm. Glad you found that out! 

Although what puzzles me, it seems this relates to this change: https://github.com/kaliber5/ember-bootstrap/pull/657, but this was introduced for 2.1.0. 2.0.0 did not have this!? 🤔

>  I assume there is no way of turning off the lazy rendering for specific dropdowns?

Out of the box, no. It certainly would be possible to implement that, but the use case here is really very specific and tbh quite unusual, so adding this here does not seem to make much sense for me. What's inside the dropdown menu should only affect the dropdown's UI, and not cause side effects like it seems to do in your case. So I would rather suggest to tackle that problem elsewhere, i.e. in `ember-file-upload`.

So gonna close this for now...

**Comment by fran-worley** [comment]
> Although what puzzles me, it seems this relates to this change: #657, but this was introduced for 2.1.0. 2.0.0 did not have this!? 🤔

I agree which is part of what's taken me so long to track down the cause! I can confirm that in 2.0.0 my file-upload component is not rendered until open either. 

Totally agree - working on a PR for ember-file-upload as we speak! thanks for your input you've saved me quite a bit of time inadvertently with your wormhole comment!
