### ISSUE TITLE
Button: support outline style

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#673]
See http://getbootstrap.com/docs/4.1/components/buttons/#outline-buttons

An `outline` property as in `{{#bs-button type="primary" outline=true}}` could generate a `btn-outline-primary` class (instead of `btn-primary`).

**Comment by nickschot** [comment]
I’ve already been using this by passing ‘type=“outline-primary”’ and the like. Do you feel the Boolean is a better alternative?

**Comment by simonihmig** [comment]
Hm, right, this way it works already. Or rather *happens* to work, although the docs don't mention this as a supported way of doing it. This would at least require some better documentation.

OTOH the boolean approach would be a bit more decoupled from the actual naming of the classes. Say for example the classes in BS5 would be renamed to `.btn-primary .btn-outline` (instead of `.btn-outline-primary`), it would be possible to adapt without changing the components interface (having some private QPs that generate the appropriate classes).

**Comment by dgavey** [comment]
I would like to create a PR for this one as well.  Will it be ok to create the outline boolean for the button?  Anything else I should be aware of for this one? Sounds like we still need to support ‘type=“outline-primary”’ at a minimum.

**Comment by simonihmig** [comment]
Closed by #687
