### ISSUE TITLE
bs-popover: [enhancement]  Support dismissable popovers

### ISSUE THREAD

**Issue by psteininger** [kaliber5/ember-bootstrap#682]
Bootstrap supports a dismiss on click popovers by using focus as trigger. 
https://getbootstrap.com/docs/4.1/components/popovers/#dismiss-on-next-click
Currently that property is not settable, and not propagated down to the element. I tried to figure out how to implement it, but I got a bit lost in the code structure. I would sincerely appreciate this addition.

---

Output from `ember bootstrap:info` (available since 1.0.0-alpha.9):
```
Npm packages:
ember-bootstrap: ^2.1.1 -> 2.1.2
ember-cli: ^3.5.0 -> 3.5.0
bootstrap: ^4.1.3 -> 4.1.3
bootstrap-sass: n/a
ember-cli-sass: ^8.0.1 -> 8.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
This is already supported using the `triggerEvents` property, see the last example on the demo page:
https://www.ember-bootstrap.com/#/components/popover

**Comment by psteininger** [comment]
Thanks @simonihmig. I missed that attribute, when digging in through the code. 

BTW. I always appreciate your fast responses :)
