### ISSUE TITLE
Modal header should yield title and close components

### ISSUE THREAD

**Issue by lougreenwood** [kaliber5/ember-bootstrap#693]
It looks like the `bs-modal/header` components don't yield out the `bs-modal/header/title` & `...close`  components.

Whilst this seems good enough, it breaks from the usual pattern of child components being yielded out (and AFAIK will also not work with MU because it requires the full path to the nested components instead of the yielded version).

https://github.com/kaliber5/ember-bootstrap/blob/master/addon/templates/components/bs4/bs-modal/header.hbs

**Comment by simonihmig** [comment]
When customizing the header myself, adding a `h4.modal-title` was simple enough, so I didn't feel a need for a yielded component. But I agree, this could be added. 

Up for a PR? 😉

**Comment by lougreenwood** [comment]
I may be able to take a look at a PR :)

**Comment by simonihmig** [comment]
Closed by #701
