### ISSUE TITLE
Difficult to override checkbox styling

### ISSUE THREAD

**Issue by lougreenwood** [kaliber5/ember-bootstrap#699]
The current `bs-form` HTML structure for form label & elements makes it difficult to override checkbox styling.

See: https://medium.com/claritydesignsystem/pure-css-accessible-checkboxes-and-radios-buttons-54063e759bb3

Currently the label element wraps the form element, instead, label & input element should be siblings (making use of the `for` attribute).

I'm happy to attempt a PR for this at some point in the near future.

**Comment by simonihmig** [comment]
You are right. I guess this originates from the old BS3 markup, where this was different by default: https://getbootstrap.com/docs/3.3/css/#forms-controls.

Should be pretty easy. The `for` attribute is already set, just needs to move the `{{yield}}` out of the label here, AFAICT:
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/templates/components/bs4/bs-form/element/layout/vertical/checkbox.hbs
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/templates/components/bs4/bs-form/element/layout/horizontal/checkbox.hbs

**Comment by lougreenwood** [comment]
Cool, that looks easier than expected, I was looking at modifying the `bs-form/element/label.hbs` component directly, but your way seems better.

I'll take a look
