### ISSUE TITLE
Feature Request: Tooltips

### ISSUE THREAD

**Issue by CamonZ** [kaliber5/ember-bootstrap#7]
Hi, what's the possibility of adding tooltips support, I can contribute a PR for it but I'm wondering what's the best approach to mach the vision you have for the addon.

I was thinking of doing something similar to what was done on the old bootstrap-for-ember code where you have an component which will render all tooltips, then a component for each tooltip and a helper which will bind an element to have tooltips enabled; the positioning for each tooltip will be calculated from the element with the binding. I'll skip the controller and outlets hackery they had if possible.  

Do you think this is a viable approach?

**Comment by simonihmig** [comment]
There is a very simple implementation in the 'tooltip' branch, that relies on the original bootstrap.js. That does not play nice especially with acceptance tests, so I probably won't ever merge that into master. 

The solution should be a native solution as you suggest. I looked into https://github.com/yapplabs/ember-wormhole as a way to push UI elements at some other place than they belong to logically (bootstrap.js renders them as childs of `<body>`). 

But besides that I have no architectural pattern layed out already...

**Comment by CamonZ** [comment]
I'm going to take a look at `ember-wormhole` and try to have a PR before the end of the week.

**Comment by lypanov** [comment]
Did you have any luck with this @CamonZ?

**Comment by ngelx** [comment]
+1 
any way i can help with this?

**Comment by PratheepV** [comment]
+1

**Comment by brmendez** [comment]
+1
Hi Simon, I am all for Bootstraps Popover component. Is this in the making or are there any plans to do this in the next release?

Thank you.

**Comment by simonihmig** [comment]
After Tabs and Navs have landed in v0.8.0 I will try to tackle this as the next major feature!

**Comment by simonihmig** [comment]
fyi, v0.11.0 finally adds support for tooltips & popovers!
