### ISSUE TITLE
Checkboxes aren't aligned correctly in horizontal form for Bootstrap 4

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#715]
If you go to https://www.ember-bootstrap.com/#/components/forms and change form layout to `horizontal` you will notice that checkboxes aren't aligned with other form elements:

![checkbox-in-form](https://user-images.githubusercontent.com/4965703/49569014-035ee880-f933-11e8-9d8b-b05cd312b4d4.png)

Please refer to bootstrap docs for correct UI: https://getbootstrap.com/docs/4.1/components/forms/#horizontal-form

![checkbox-in-form-reference](https://user-images.githubusercontent.com/4965703/49569143-66507f80-f933-11e8-9796-0083672ea13c.png)

In Bootstrap docs we see this markup:

```html
  <div class="form-group row">
    <div class="col-sm-2">Checkbox</div>
    <div class="col-sm-10">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck1">
        <label class="form-check-label" for="gridCheck1">
          Example checkbox
        </label>
      </div>
    </div>
  </div>
```

Ember Bootstrap is generating a different markup:

```html
<div class="row form-check">
  <div class="col-md-8 col-md-offset-4">
    <input id="ember104-field" class="form-check-input" type="checkbox">
    <label for="ember104-field" class="col-form-label form-check-label">
      Remember me
    </label>
  </div>
</div>
```

If I didn't missed something these changes needs to be done:
- `.col-md-offset-4` is wrong for Bootstrap 4. It should be `.offset-md-4`.
- `.form-check` needs to be changed to `.form-group` on root element.
- Content inside of column containing `<input>` and `<label>` needs to be wrapped inside a `<div class="form-check">` element.
- `.col-form-label` class might be dropped.

If I recall correctly everything was needed for Bootstrap 3. So we need to make sure that this isn't breaking Bootstrap 3 markup.

**Comment by jelhan** [comment]
Seems like the case of having a horizontal form layout was simply missed in #341.

**Comment by simonihmig** [comment]
Hm, indeed... thanks for dissecting this so well!
