### ISSUE TITLE
Disable validations on form submission

### ISSUE THREAD

**Issue by Techn1x** [kaliber5/ember-bootstrap#716]
It seems at the moment there isn't an official/public way to disable validations for a form submission.

I have a form which 99% of the time validations should be run, but in one case it should submit no matter what.

I am using ember-bootstrap-cp-validations, and with that I have 2 options;
* Use the global options hash to define a `disabled` property, which is then passed to all validators. This property will be overridden if an individual validator defines its own `disabled` property
* Define a `disabled` property on every validator (tedious for large forms..)

Ideally something like... `{{#bs-form ... disableValidations=model.dontValidate}}` would be great, especially since an approach like that would work no matter which validation library was being used!

**Comment by Techn1x** [comment]
Thanks @jelhan , I was after option 2, I didn't even realise an `onInvalid()` method existed, and that will definitely solve my problem!

**Comment by jelhan** [comment]
@Techn1x Just wondering if we should keep this open as quest issue cause even your use case is not fully supported yet.

**Comment by jelhan** [comment]
@simonihmig Any thoughts on third case?

> 3. Disable the validations at all.
>
> If we support first and second case third one would only be about performance, isn't it?

I'm tending to not add any special support cause it would add a lot of complexity. Disabling validation should be handled by validation library IMO. If you agree this issue could be closed cause last remaining task is tracked at #364.

**Comment by simonihmig** [comment]
If I understand this correctly, the third case was about disabling the validations itself, not just not-displaying them, right? For this I would definitely agree, this seems like a bad thing to do because of the far-reaching consequences (interference with application state). This library should be only concerned with the UI-part.

Closing this for now.

**Comment by Techn1x** [comment]
Thanks for the hard work everyone!
