### ISSUE TITLE
Textarea value is not bound to the model

### ISSUE THREAD

**Issue by dzbo** [kaliber5/ember-bootstrap#725]
I'm trying to use textarea control like this:

```
<BsForm
  @model={{answer}}
  @onSubmit={{action "submit"}} as |form|
>
  <form.element
    @controlType="textarea"    
    @property="comment"
  />

  ...

</BsForm>
```

But it doesn't update `comment` property on `answer` model when I type in textarea. It also doesn't work with `@value={{answer.comment}}`

**Comment by simonihmig** [comment]
I am not able to reproduce this. It's covered by tests, and it seems to be working just fine on ember-bootstrap.com:

![image](https://user-images.githubusercontent.com/1325249/50112653-0a91ca80-0240-11e9-820a-e0224a1fa8de.png)

**Comment by dzbo** [comment]
@simonihmig so my apologies. Turns out the problem was how I was `peeking` record in `setupController` and omniting model hook. That bugged the form.
