### ISSUE TITLE
Outdated `ember-concurrency`: Class constructor ComputedProperty cannot be invoked without 'new'

### ISSUE THREAD

**Issue by sumeetattree** [kaliber5/ember-bootstrap#734]
Output from `ember bootstrap:info`:

```
Npm packages:
  ember-bootstrap: ^2.4.0 -> 2.4.0
  ember-cli: ~3.6.0 -> 3.6.0
  bootstrap: ^4.2.1 -> 4.2.1
  bootstrap-sass: n/a
  ember-cli-sass: ^7.2.0 -> 7.2.0
  ember-cli-less: n/a
Bower packages:
  bootstrap: n/a
  bootstrap-sass: n/a
ember-bootstrap configuration:
  bootstrapVersion: 4
  importBootstrapFont: false
  importBootstrapCSS: false
```
Let me know if you'd like a pull request.

**Comment by simonihmig** [comment]
@sumeetattree can you add some details, when does that happen, for which component? And is this a hard error (exception), or "just" a deprecation?

> Let me know if you'd like a pull request.

That would be awesome!

**Comment by sumeetattree** [comment]
It was a hard exception. So there are two dependencies that are using `ember-concurrency`. `ember-power-select` and `ember-bootstrap`. I am unsure if one of them is causing this error or both are. For now I've resolved it using `resolutions` feature of `yarn`. In any case I think it would be a good idea to update the dependency to it's latest version.

I'll send in the pull request, but I am unsure when I'll be able to post a detailed report about it. I would really appreciate it if anyone else who comes across this issue and can provide a detailed report.
