### ISSUE TITLE
carousel onIndexChanged callback

### ISSUE THREAD

**Issue by Techn1x** [kaliber5/ember-bootstrap#760]
I've revisited my webapp's carousel implementation and one improvement that I think could be made to `bs-carousel` would be letting the parent know that the slide has changed, and what index it was changed to. Perhaps an `onIndexChanged` callback?

My use case is I have a ribbon of thumbnails of all images available in the carousel, and I would like to highlight the thumbnail that is currently shown in the carousel

Something like....

```handlebars
// templates/components/image-gallery.hbs
{{#bs-carousel
  ...
  interval=0
  wrap=true
  model=imageCaptures
  index=activeImageIndex
  onIndexChanged=(action 'slideChanged')
  as |car|}}
  {{#each imageCaptures as |slide|}}
    {{#car.slide}}
      ...
    {{/car.slide}}
  {{/each}}
{{/bs-carousel}}

<div class="image-gallery-thumbnails">
  {{#each imageCaptures as |imageCap index|}}
    <a class="thumbnail {{if (eq activeImageIndex index) 'active'}}" {{action (mut activeImageIndex) index}}>
      <img src="{{imageCap.image_url}}">
    </a>
  {{/each}}
</div>
```

```javascript
// components/image-gallery.js
...
actions: {
  slideChanged(index) {
    if(this.get('activeImageIndex') !== index) this.set('activeImageIndex',index);
  }
}
...
```

I don't think this would be too hard to add, I would probably add it to the `toSlide` action like so;
https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-carousel.js#L466-L477
```javascript
// components/base/bs-carousel.js
...
actions: {
  toSlide(toIndex) {
    if (this.get('currentIndex') === toIndex || this.get('shouldNotDoPresentation')) {
      return;
    }

    if(this.get('onIndexChanged')) {
      this.get('onIndexChanged')(toIndex);
    }

    this.assignClassNameControls(toIndex);
    this.setFollowingIndex(toIndex);
    if (this.get('shouldRunAutomatically') === false || this.get('isMouseHovering')) {
      this.get('transitioner').perform();
    } else {
      this.get('cycle').perform();
    }
  },
...
```

Also, what do you think about the name `onIndexChanged`? And what other args should be passed?

**Comment by simonihmig** [comment]
I agree this would be useful. But tbh I never have used the carousel by myself, so wasn't even aware this doesn't exist. But also not able to work on it, but if you are willing to work on a PR, that would be certainly appreciated!

**Comment by Techn1x** [comment]
Will do!

**Comment by kostimarko** [comment]
any update on this? I'd like to get a callback when the slide changes.

Use case: I'd like to animate the captions when the slide changes.

**Comment by Techn1x** [comment]
Sorry @kostimarko I now work at a different company that doesn't use ember-bootstrap so I haven't been able to sneakily schedule company time to work on PR's for this (as simple as I think this PR would be!)

That being said, I am a part of [hacktoberfest](https://hacktoberfest.digitalocean.com/) this year, so I may take this one on in my personal time :)

**Comment by kostimarko** [comment]
@Techn1x no biggie. I don't really use ember nor really understand the framework that well, react land here, other wise I'd enter a PR.
