### ISSUE TITLE
What does ownerInjection() do inside a create()?

### ISSUE THREAD

**Issue by Redsandro** [kaliber5/ember-bootstrap#761]
Given [this documentation](https://emberjs.com/api/ember/3.8/functions/@ember%2Fobject/create):

> **create(**_arguments_**)**
>
> Creates an instance of a class. Accepts either no arguments, or an object containing values to initialize the newly instantiated object with.

I don't understand the following code:

https://github.com/kaliber5/ember-bootstrap/blob/f0575fae0f5ae42330e8c3b54259dd081e92000d/tests/dummy/app/controllers/demo/forms.js#L15

```js
  login: computed(function() {
    return Login.create(
      getOwner(this).ownerInjection()
    );
  }),
```

What does this do?

**Comment by lolmaus** [comment]
Hey @Redsandro.

Ember has a dependency injection system. Instances of classes belong to an "owner" which is typically the same across all instances.

This comes in handy on the backend environment (Ember uses [FastBoot](https://ember-fastboot.com) for server-side rendering) where multiple instances of your app can be initialized at the same time in the same JS process. The process needs to distinguish which class instance operates on which app instance.

Though most users do not use server-side rendering, this system is there for everyone.

An owner of a class instance is necessary to access singletons shared across the app instance: controllers, routes, but most importantly services. Without an owner, a class instance can't access any services.

The `Login` class uses validations why rely on the injection system. Thus, each `Login` instance requires an owner.

The `getOwner(this)` function returns an owner of the current class instance. This util can be used on any instance that has an owner.

The `ownerInjection` method [returns](https://www.emberjs.com/api/ember/3.8/classes/ApplicationInstance/methods/ownerInjection?anchor=ownerInjection) an owner in a form that is accepted by `EmberObject.create()`, which is a soon-to-be-obsolete API and is gonna be replaced with native classes' `new` keyword.

An alternative way to initialize an instance of a class with an owner is to do [`getOwner(this).lookup(className)`](https://www.emberjs.com/api/ember/3.8/classes/ApplicationInstance/methods/lookup?anchor=lookup). `className` must be provided in a form `base-class:sub-class`. Depending on the configuration of the class in [`registerOptionsForType`](https://www.emberjs.com/api/ember/3.8/classes/ApplicationInstance/methods/registerOptionsForType?anchor=registerOptionsForType), `lookup()` will return either the class, or a freshly initialized class instance, or a singleton class instance.

PS The issue queue is primarily for bug reports and feature suggestions. To receive support, consider [asking a question on StackOverflow](https://stackoverflow.com/questions/ask?tags=ember-bootstrap) with the `ember-bootstrap` tag.

**Comment by lolmaus** [comment]
@simonihmig Please use the Filters feature on https://stackexchange.com to subscribe to email notifications for the `ember-bootstrap` tag.

**Comment by simonihmig** [comment]
> PS The issue queue is primarily for bug reports and feature suggestions. To receive support, consider [asking a question on StackOverflow](https://stackoverflow.com/questions/ask?tags=ember-bootstrap) with the `ember-bootstrap` tag.

I haven't actively used SO so far. While I can certainly subscribe, the primary channel for questions so far has been the `e-bootstrap` channel on Discord!

**Comment by Redsandro** [comment]
@lolmaus thank you for the detailed answer. I had no idea about the ramifications of (not) setting an owner, even though I use fastboot.

Apologies for writing a question in the issue tracker. FWIW, I was initially going to write a bug report that the example contained what I assumed was obsoleted code, since (1) it worked fine without it and (2) the documentation doesn't seem to mention this argument for `create()`. I changed my mind because prior experience taught me that I'm usually wrong, and things that seem out of place are usually undocumented Ember features - or probably documented in a place other than the first one or two places I'd look. :sweat_smile:
