### ISSUE TITLE
New Bootstrap versions

### ISSUE THREAD

**Issue by kumy** [kaliber5/ember-bootstrap#773]
New bootstrap versions were published last month. They fix between other an XSS vulnerability.
https://blog.getbootstrap.com/2019/02/13/bootstrap-4-3-1-and-3-4-1/

I'll provide PR for that.

**Comment by jelhan** [comment]
XSS vulnerability is related to Bootstrap JavaScript. Ember Bootstrap does not use any Bootstrap JavaScript.

**Comment by kumy** [comment]
Ok! It doesn't hurt to update?
