### ISSUE TITLE
[Quest] Update documentation for angle bracket invocation

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#776]
As the [Ember Guides](https://guides.emberjs.com/release/components/defining-a-component/) already have transitioned to angle bracket invocation instead of classic curlies, we should do the same here:

- [x] Update API docs (Yuidoc annotations in source files)
- [x] Update demo examples (in `dummy` app)

Help from the community would be very much appreciated here! 🙏

Comprehensive details of angle bracket invocation can be found on the [RFC](https://github.com/emberjs/rfcs/blob/master/text/0311-angle-bracket-invocation.md)

Just announce here if you want to work on something. And feel free to ask for help if things are unclear!

**Comment by betocantu93** [comment]
I got the API yuidocs #777

**Comment by rajasegar** [comment]
Can i take up the `Update demo examples` item? I think that's a huge effort, i am looking forward to the learning's, since we are also kind of building a component library for our org, this would serve as a perfect platform to start.

**Comment by simonihmig** [comment]
@rajasegar that would be awesome, much appreciated! 

Please look at #777 for how this should like, especially the (ongoing) discussion around code style details, so that we have a coherent style!

**Comment by rajasegar** [comment]
@simonihmig Sure, will take a look at that

**Comment by rajasegar** [comment]
@simonihmig I tried to write a codemod for the conversion, i was able to get it working in astexplorer, but not as a transform with jscodeshift, any help would be appreciated.
ASTExplorer:
https://astexplorer.net/#/gist/b128d5545d7ccc52400b922f3b5010b4/571266d8c29cb8eb1bd5730c0c388526081cce46

Codemod:
https://github.com/rajasegar/ember-angle-brackets-codemod
