### ISSUE TITLE
[QUEST] Road to 3.0

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#780]
This aims at collecting all the issues/Todos that would result in breaking changes, so we can aggregate all those in a single major version bump.

- [x] several smaller [breaking change issues](https://github.com/kaliber5/ember-bootstrap/issues?q=is%3Aissue+is%3Aopen+label%3Abreaking)

~- [ ] Migrate to the Octane programming model~
 ~- [ ] Refactor from Ember object model to native class + decorators. This *might*  break users `.extend`ing from e-b components for older Ember versions I believe. (codemod: https://github.com/ember-codemods/ember-es6-class-codemod)~
  ~- [ ] Use angle bracket invocation internally~
  ~- [ ] Use angle bracket invocation in tests (see #776)~

- [x] Related to angle bracket invocation, make sure that setting HTML attributes works consistently
  - ~[ ] deprecate props including documentation (form element!) whose only purpose is supporting HTML attributes~ deprecations will follow, see #826 
  - [x] make sure HTML attributes get propagated to the appropriate HTML element using `...attributes`
  - ~[ ] figure out if we should remove name clashes (attributes vs. props), e.g `type` for Buttons (see https://github.com/kaliber5/ember-bootstrap/pull/778#issuecomment-474323269)~ *no last-minute breaking changes should be introduced. Deprecations for 4.0 could be added though during 3.x*

- [x] drop node 6 support (end of life at end of April)

- [x] depending on the further outcome of #778, we might be forced to delay introducing angle bracket invocation in docs to 3.0  

### Ember support

~To be decided is the minimum Ember version to be supported starting with 3.0:~
*We will go forward support only Ember 2.18+*

* **2.12** seems to be the most conservative choice, which still enables us to move forward (as it includes Glimmer2, and is supported by `ember-angle-bracket-invocation-polyfill`
* **2.18** is the middle ground, as some users might still be stuck at that version, not able yet to upgrade to Ember 3.0 due to its breaking changes
* **3.4** is the only LTS that is still supported by Ember itself. So when introducing a breaking change anyway, do we have to support Ember versions that aren't supported by Ember itself? Or can we be that bold to require 3.4? It would allow us to not have to use `ember-angle-bracket-invocation-polyfill`, and have more predictable native class semantics (see https://github.com/pzuraq/ember-native-class-polyfill)

**Comment by jelhan** [comment]
I think we should base our decision which ember versions to support on Ember Community Survey. Results are not officially announced yet, but seem to be available [here](https://emberjs.com/ember-community-survey-2019/). Nearly one of four developers reporting to still use [Ember 2.18](https://emberjs.com/ember-community-survey-2019/#MS_Q401). Therefor I have the feeling that it's to early to drop support for it.

I agree that 2.18 is a good middle ground. While polyfillys for angle bracket invocation and [modifier manager](https://github.com/rwjblue/ember-modifier-manager-polyfill#compatibility) support Ember 2.12 many new addons doesn't, e.g. [`ember-render-modifiers`](https://github.com/emberjs/ember-render-modifiers) and [`ember-on-modifieres`](https://github.com/buschtoens/ember-on-modifier).

**Comment by simonihmig** [comment]
> Therefor I have the feeling that it's to early to drop support for it.

That was mine as well.

> I agree that 2.18 is a good middle ground.

Yes, I think we should go forward with that choice!

> many new addons doesn't, e.g. ember-render-modifiers and ember-on-modifieres.

But both addons you mentioned state that they *do* support Ember 2.18!? :wink:

**Comment by simonihmig** [comment]
FYI: created a `dev-v3` branch for ongoing development related to 3.0, before we can merge it to master. /cc @jelhan

**Comment by nickschot** [comment]
One other thing to think about is the casing semantics for yielded components. Angle bracket components are normally CamelCased whereas implementation wise it doesn't matter for Ember if the component is yielded (i.e. `<CamelCased as |cc|><cc.kebab-cased /></CamelCased>` would be fine).

I myself like to CamelCase those yielded components too for consistency. This would of course also be a breaking change...

I know of at least ember-basic-dropdown (and presumably in the future also the other -power addons) that adopted this. See: https://github.com/cibernox/ember-basic-dropdown/blob/master/CHANGELOG.md

**Comment by jelhan** [comment]
> I myself like to CamelCase those yielded components too for consistency. This would of course also be a breaking change...

This would only be a breaking change if we remove the kebab-case version wouldn't it? We could also add camelCased property on yield without removing the kebab-cased alias. This would be similar to `deprecatingAlias()` macro but I'm not sure how much work would be needed to actually throw a deprecation message if the kebab-cased alias is used.

**Comment by nickschot** [comment]
Yes, certainly possible. I’ve done this myself too for some addons. Deprecation message shouldn’t be too hard I think.

**Comment by simonihmig** [comment]
> Small helper wrapping the component in the yield maybe?

Yes, I think that should work!

**Comment by simonihmig** [comment]
> remove props including documentation (form element!) whose only purpose is supporting HTML attributes

I have been working on internally using angle brackets [here](#795), so that passing HTML attributes works as expected (using `...attributes`). Thinking about the above point, it might actually be a bit too quick to remove the existing support for "attributes as properties" (`attributeBindings`), as this change might affect a lot of users. We could instead introduce proper splattributes support and at the same time throw a deprecation warning when any of the "attributes as properties" are used. 

@jelhan @nickschot thoughts?
