### ISSUE TITLE
Error on Ember 3.5/3.6/3.7 -  Cannot set property placement of [object Object] which has only a getter

### ISSUE THREAD

**Issue by vmalloc** [kaliber5/ember-bootstrap#784]
Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^1.2.2 -> 1.2.2
ember-cli: ~3.8.1 -> 3.8.1
bootstrap: ^4.3.0 -> 4.3.1
bootstrap-sass: n/a
ember-cli-sass: ^7.1.7 -> 7.2.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

From a very preliminary investigation this seems to be stemming from ember-bootstrap's usage of ember-popper, and the attempt to assign to `placement`...

**Comment by simonihmig** [comment]
@vmalloc I must assume this is due to the quite old version of the addon you are using, and should have been fixed meanwhile, as our test suite does pass for latest Ember versions. Please try with the latest one (2.6), and feel free to reopen if the problem it still occurs!

**Comment by vmalloc** [comment]
@simonihmig That's strange, for some reason `yarn upgrade-interactice` did not suggest to upgrade ember-bootstrap :-/

Will try and report back. Thanks!

**Comment by vmalloc** [comment]
Seems to have worked. Thanks and sorry for your trouble!
