### ISSUE TITLE
Seeing [object Object] when using @icon with bs-button

### ISSUE THREAD

**Issue by skaterdav85** [kaliber5/ember-bootstrap#810]
Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: 2.7.0 -> 2.7.0
ember-cli: ~3.9.0 -> 3.9.0
bootstrap: ^4.0.0 -> 4.1.3
bootstrap-sass: n/a
ember-cli-sass: 10.0.0 -> 10.0.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapFont: false
importBootstrapCSS: false
```

When using `@icon`, it spits out `[object Object]`.

```hbs
<BsButton
    @defaultText="Download"
    @pendingText="Downloading"
    @icon="glyphicon glyphicon-download"
    @type="default"
    @onClick={{@downloadReport}} />
```

results in:

```html
<button class="btn btn-default ember-view" type="button">
    <i class="[object Object]"></i> Download
</button>
```

**Comment by simonihmig** [comment]
I was not able to reproduce this. Copied your snippet into the addon's dummy app, and it rendered just fine:

![image](https://user-images.githubusercontent.com/1325249/58386075-f1fdbb80-7ffa-11e9-9c08-dea58226b98b.png)

Eventually any kind of customizations (Extended components, overridden templates) in your app?

**Comment by skaterdav85** [comment]
@simonihmig I created a fresh app and it works fine. In my current app, I don't see any overridden templates or components called `bs-button`, so I'm not sure why this is happening. Guess I'll have to keep digging.
