### ISSUE TITLE
input-group-btn and bs-button-group

### ISSUE THREAD

**Issue by basz** [kaliber5/ember-bootstrap#82]
I'm trying to create an input field with two radio like buttons on the end. However the bs-button-component adds a group-btn class while an input-group-btn would be more appropriate. Removing that class in the inspector seems to fix it.

Is this use case supported? Should I create a subclass so I can defined the class. For now i'l use didInsertElement to remove the class, but that seems hacky...

Thanks

https://www.dropbox.com/s/1diszmfsvu3sa7f/Screenshot%202016-04-25%2015.57.08.png?dl=0

```hbs
<div class="input-group">
    {{bs-input value=selected}}

    {{#bs-button-group value=selectedFormat class="input-group-btn" type="radio"}}
        {{#each availableFormats as |item|}}
            {{#bs-button value=item}}
                {{item.label}}
            {{/bs-button}}
        {{/each}}
    {{/bs-button-group}}
</div>
```

```html
<div class="col-md-8">
    <div id="ember1100" class="ember-view">
        <div class="input-group">
            <input id="ember1101" type="text" class="ember-view ember-text-field form-control">

            <div id="ember1110" role="group" class="input-group-btn ember-view btn-group">
                <button id="ember1112" type="button" class="ember-view btn btn-default active">
                    French
                </button>
                <button id="ember1114" type="button" class="ember-view btn btn-default">
                    English
                </button>
            </div>
        </div>
    </div>
</div>
```

**Comment by simonihmig** [comment]
Indeed, this use case is not supported. Have not seen this (a radio button group inside an input group) on getbootstrap.com as well. A subclass would probably not help as the `btn-group` class of the parent class would still be added. Probably you would need to fix this with some custom CSS.
