### ISSUE TITLE
Automatically disable button while in pending state

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#822]
* add a property `disableWhilePending`, for compatibility being `false` by default
* When `true`, will disable the button while being in pending state, i.e. promise returned from action is not settled
* In v3.0.0 set `disableWhilePending` to `true` by default?

Related to #638. With a button yielded by a form, that would auto-disable the button while the form is submitting.

@jelhan thoughts?

**Comment by jelhan** [comment]
Would be a helpful addition IMO.

> In v3.0.0 set `disableWhilePending` to `true` by default?

I think an alias to `preventConcurrency` would be more helpful as for most use cases the button should be disabled if `preventConcurrency` is `true`. Maybe we want to consider toggling that default in v3.0.0?

**Comment by simonihmig** [comment]
> I think an alias to preventConcurrency would be more helpful

Yes, but this is describing the case where the button is yielded by the form, so when yielding we can override `disableWhilePending` with whatever makes sense in the context of a `<BsForm>`. For a plain `<BsButton>` the default could still be set to `true` I think? (again, in v3)

**Comment by jelhan** [comment]
> > I think an alias to preventConcurrency would be more helpful
> 
> Yes, but this is describing the case where the button is yielded by the form, so when yielding we can override `disableWhilePending` with whatever makes sense in the context of a `<BsForm>`. For a plain `<BsButton>` the default could still be set to `true` I think? (again, in v3)

Maybe I'm missing something but why shouldn't this be different for a plain `<BsButton>`? `<BsButton>` also has a [`preventConcurrency` option](https://www.ember-bootstrap.com/api/classes/Components.Button.html#property_preventConcurrency). I don't see use cases for `<BsButton @preventConcurrency={{true}} @disableWhilePending={{false}}>` or `<BsButton @preventConcurrency={{false}} @disableWhilePending={{true}}>`.

I'm especially worried about edge cases if `preventConcurrency` defaults to `false` and `disableWhilePending` defaults to `true` and the defaults are not overriden. There might be timing issues in that case which still allows `onClick` action to be fired concurrently. At least I'm worried about the `disabled` attribute of the button not being updated yet by Glimmer VM but a second click event being fire. Not sure if this is prevented by some browser internals but we wouldn't have to worry about it, if both of them are in sync as long as consumer doesn't pass in both.

So maybe `disableWhilePending` should default to `preventConcurrency` and `preventConcurrency` should default to `disableWhilePending`. If both aren't set they should default to `true`. (Talking about v3 only right now).

**Comment by simonihmig** [comment]
> `<BsButton>` also has a preventConcurrency option

Nevermind, I forgot about this! 🤦‍♂️

So yes, then this absolutely makes sense!

**Comment by jelhan** [comment]
While working on #834 I noticed that the design laid out here might be overcomplex. I'm not convinced anymore that we need a `disableWhilePending` property at all. Maybe it's enough to change `disabled` so that a button is disabled by default if the click action is pending and if the button should prevent concurrent clicks:

```patch
diff --git a/addon/components/base/bs-button.js b/addon/components/base/bs-button.js
index 54bd1545..1e9666d1 100644
--- a/addon/components/base/bs-button.js
+++ b/addon/components/base/bs-button.js
@@ -1,7 +1,7 @@
 import { scheduleOnce } from '@ember/runloop';
 import Component from '@ember/component';
 import { observer, computed } from '@ember/object';
-import { deprecatingAlias, equal, or }  from '@ember/object/computed';
+import { and, deprecatingAlias, equal, or }  from '@ember/object/computed';
 import layout from 'ember-bootstrap/templates/components/bs-button';
 import TypeClass from 'ember-bootstrap/mixins/type-class';
 import SizeClass from 'ember-bootstrap/mixins/size-class';
@@ -149,12 +149,15 @@ export default Component.extend(TypeClass, SizeClass, {
   /**
    * Property to disable the button
    *
+   * The button is disabled by default if and only if
+   * - a Promise returned by `onClick` action is pending and
+   * - `preventConcurrency` is `true`.
+   *
    * @property disabled
    * @type boolean
-   * @default false
    * @public
    */
-  disabled: false,
+  disabled: and('isPending', 'preventConcurrency'),
 
   /**
    * Set the type of the button, either 'button' or 'submit'
```

A consumer that overrides `disabled` is responsible itself for disabling the button if an action is pending. This also prevents edge cases like `<BsButton @disabled={{false}} @disableWhilePending={{true}}>`  in current design.

**Comment by simonihmig** [comment]
> Maybe it's enough to change disabled so that a button is disabled by default if the click action is pending and if the button should prevent concurrent clicks

Sounds reasonable!

> `disabled: and('isPending', 'preventConcurrency')`

I believe this will trigger a deprecation warning, as settings that prop (which we want to allow!) will override the CP, see https://deprecations.emberjs.com/v3.x#toc_computed-property-override
