### ISSUE TITLE
Example Compound bs-form-element

### ISSUE THREAD

**Issue by basz** [kaliber5/ember-bootstrap#83]
When I'm in need of a 'composed' input an input field and a dropdown that both interacts to produce one value I think I need to extend the bs-form-element. so I can take advantage of the form layout and validation feature.

However, I'm not getting very far with that,...

```
import FormElement from 'ember-bootstrap/components/bs-form-element';
export default FormElement.extend({
});

and

{{production-ui/form-element/insole-size label="Size"}}
```

will happily output.

```
<div id="ember1179" class="ember-view form-group"><!----></div>
```

Could you provide me with a quick rundown of how to do something like this. A simple NO don't do that! Also helps :-)

**Comment by simonihmig** [comment]
Have a look at the section "Custom Controls" in http://kaliber5.github.io/ember-bootstrap/api/classes/Components.FormElement.html. This should hopefully enable you to accomplish what you are looking for!

**Comment by basz** [comment]
I had, but the problem with that is that the interacting logic of the various buttons and input is then external to the element-group. that severely complicates the logic in the form controller. 

But, I now have figured out how why I didn't see any renderings (you included a dynamic partial). And now I am getting somewhere... slowly...

If I complete the thing I might post it somewhere for others to enjoy

**Comment by simonihmig** [comment]
ok, great, looking forward to your solution!
