### ISSUE TITLE
Upgrade ember-concurrency

### ISSUE THREAD

**Issue by lolmaus** [kaliber5/ember-bootstrap#835]
ember-concurrency 1.0.0 has been released. For consistency with other addons, we should keep up.

**Comment by simonihmig** [comment]
@lolmaus can you please provide a PR?

**Comment by jelhan** [comment]
#821 should do the job. One test failed with `Segmentation fault`. I don't think that's related to the upgrade. But the PR needs to be rebased. Does Greenkeeper support rebasing these days or must it done manually?
