### ISSUE TITLE
Form element w/ Angle Bracket Invocation has HTML attrs applied twice

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#844]
Applying HTML attributes to a form element V3.0.0-rc.0 applies HTML attributes to the form control (good) as well as the `.form-group` div (bad).

**Comment by jelhan** [comment]
I'm not convinced yet that attributes that on form element should be applied to control and not to wrapping `.form-group`. There are use cases in which a consumer might need to add classes to the element that wraps control, label and help texts. E.g. for a complex grid layout [Bootstrap documentation recommends](https://getbootstrap.com/docs/4.3/components/forms/#form-groups):

```html
<form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Password</label>
      <input type="password" class="form-control" id="inputPassword4" placeholder="Password">
    </div>
  </div>
</div>
```

If HTML attributes are applied to `.form-group` that should be quite easy with Ember Bootstrap:

```hbs
<BsForm as |form|>
  <div class="form-row">
    <form.element @controlType="email" @label="Email" class="col-md-6" />
    <form.element @controlType="password" @label="Password" class="col-md-6" />
</BsForm>
```

I'm not sure if this would be even possible if HTML attributes are not applied to `.form-group`.

If a user wants to set HTML attributes on form control that could be accomplished by applying it to form control:

```hbs
<BsForm as |form|>
  <form.element as |element|>
    <element.control class="form-control-lg">
  </form.element>
</BsForm>
```

**Comment by simonihmig** [comment]
Yep. You nailed it! 

I did try out my change in an app, which previously suffered from the HTML attributes being applied twice (tests failing because of having a selector match twice). With that change, a lot more tests started to fail, as the `data-test-fieldname` test selectors were not applied to the outer `.form-group` anymore.

My intention was to be able to switch from old-school properties that map to attributes (using `attributeBindings`) to real HTML attributes easily when migrating to angle bracket invocation, e.g.:

```diff
- {{form.element property="name" placeholder="Enter your name"}}
+ <form.element @property="name" placeholder="Enter your name" />
```

Previous to the changes in #845, the attrs were already passed to the control component, but applied also to the form group. Which is still not want we want I guess.

Another approach would be to not pass the attributes to the control at all. So to do that, you would have to directly pass them to the yielded control component:

 ```diff
- {{form.element property="name" placeholder="Enter your name"}}
+ <form.element @property="name" as |el|>
+   <el.control placeholder="Enter your name" />
+ </form.element>
```

As you will often have to pass at least one attribute to the control, e.g. `placeholder`, this will make creating a form somewhat more verbose. On the other hand it is clear what gets passed to what, i.e. you can pass attributes to the wrapper independently of passing others to the control.

Any alternatives we have?

/cc @lolmaus @nickschot

**Comment by jelhan** [comment]
I'm tending to keep `@placeholder` as a property on `<form.element>` and pass them to HTML attributes on `<el.control>`.

```hbs
<form.element @placeholder="Enter your name" />
```

would be a shorthand for

```hbs
<form.element as |element|>
  <element.control placeholder="Enter your name" />
</form.element>
```

> As you will often have to pass at least one attribute to the control, e.g. placeholder, this will make creating a form somewhat more verbose.

Is there any other property on `FormElement` that should be considered as an alias for an HTML attribute on form control? I was going through API docs and didn't found one. Maybe `controlType`, `invisibleLabel`, `size` and `useIcons` but they all contain more logic or affect the label which is not yielded.

**Comment by simonihmig** [comment]
> I'm tending to keep @placeholder as a property on <form.element> and pass them to HTML attributes on <el.control>.

As we haven't removed them (HTML attribute supporting props), this would continue to work. But I don't think we should encourage that pattern for new angle brackets code, see below...

> Is there any other property on FormElement that should be considered as an alias for an HTML attribute on form control?

Oh, yes. Way too many! 

* See "HTML attributes" at https://www.ember-bootstrap.com/api/classes/Components.FormElement.html
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/templates/components/common/bs-form/element.hbs#L33-L61
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/base/bs-form/element/control/input.js#L36-L53
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/mixins/control-attributes.js#L12-L20

That's why I wanted to eventually deprecate all of those in https://github.com/kaliber5/ember-bootstrap/issues/826.
