### ISSUE TITLE
Bootstrap 4 - Glyphicons migration?

### ISSUE THREAD

**Issue by absemetov** [kaliber5/ember-bootstrap#858]
'importBootstrapFont': true, dont help

**Comment by jelhan** [comment]
Ember Bootstrap does not provide a way to import Glyphicons with Bootstrap 4. There are different migration strategies. You could find an overview in [this question on StackOverflow](https://stackoverflow.com/questions/32612690/bootstrap-4-glyphicons-migration). Personally I would recommend refactoring to Fontawesome. They provide an officially support [ember addon](https://github.com/FortAwesome/ember-fontawesome). Importing Glyphicons manually as discussed in that StackOverflow question might not be to complex but you may face license issues.

**Comment by absemetov** [comment]
@jelhan Thanks!
