### ISSUE TITLE
Embroider Support

### ISSUE THREAD

**Issue by btecu** [kaliber5/ember-bootstrap#868]
I'm not sure where work has to be done, wether in Embroider or in this project, so I'm creating this issue for tracking - unless someone wants to look into the cause.

When trying to use Embroider in an application which is using `ember-bootstrap`, it errors out. The error is reported here: https://github.com/embroider-build/embroider/issues/164

**Comment by simonihmig** [comment]
Note: the fix will have to be reverted unfortunately, see #914. It should nevertheless work fine when the upstream fix in Embroider (https://github.com/embroider-build/embroider/pull/341) is released!
