### ISSUE TITLE
nav.item does not support links with nested navs

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#878]
There is a problem with the API introduced in https://github.com/kaliber5/ember-bootstrap/pull/861: the new link params added to `nav.item` will wrap the `{{yield}}` in a `<a>` link, but that turns out not so well when used together with nested navs:

```hbs
<BsNav as |nav|>
  <nav.item @route="support">
    Support
    <BSNav as |nav2|>
      <nav2.item @route="support.faq">FAQ</nav.item>
    </BsNav>
  </nav.item>
</BsNav>
```

The problem here is that the first link will wrap the nested `<ul>` with all its content, including the FAQ link. 😩

Instead of auto-wrapping we could yield the pre-configured `<LinkTo>` component, but that makes things quite verbose:

```hbs
<BsNav as |nav|>
  <nav.item @route="support" as |item|>
    <item.linkTo>Support</item.linkTo>
    <BSNav as |nav2|>
      <nav2.item @route="support.faq" as |item|><item.linkTo>FAQ</item.linkTo></nav.item>
    </BsNav>
  </nav.item>
</BsNav>
```

For context: all this trouble is needed, as BS (at least BS3) expect the `active` class on the `<li>` rathe than the `<a>` (which would just work out of the box). So we need to pass the link information to the `nav.item`, when we don't want the hacky way of doing it as it was before...

I guess this is blocking the 3.0 release until we have this figured out, which I really wanted to get out asap, in case we need to introduce another breaking change! 😖

Any thoughts? @jelhan @nickschot @lolmaus

**Comment by jelhan** [comment]
To be honest I'm tending towards a rollback to old API even so it required some hacky communication between the child and parent component:

```hbs
<BsNav as |nav|>
  <nav.item as |item|>
    <item.linkTo  @route="support">Support</item.linkTo>
    <BSNav as |nav2|>
      <nav2.item as |item|><item.linkTo @route="support.faq" >FAQ</item.linkTo></nav.item>
    </BsNav>
  </nav.item>
</BsNav>
```

The main argument I'm seeing is the long-term perspective. If I didn't missed something the routing support on `<BsNav>` is only needed for Bootstrap 3. Built-in `<LinkTo>` plays fine with Bootstrap 4, isn't it? If that's the case, we should make sure that migrating away from routing support on `<BsNav>` will be as smooth as possible at that point of time.

Having a `<item.linkTo>` component that has the same API as built-in `<LinkTo>`, would reduce the migration at that point of time to a find and replace. Having the routing API on `<nav.item>` would require more manual work (or a more complex codemod).

There are two other arguments:

- Migrating from `{{item.link-to}}` to `<item.linkTo>` makes less noise and is very similar to migration of built-in component from `{{link-to}}` to `<LinkTo>`.
- If there is a `linkTo` component, it's not that intuitive that the routing arguments needs to be present at it's wrapping `<nav.item>` component.

**Comment by simonihmig** [comment]
> To be honest I'm tending towards a rollback to old API even so it required some hacky communication between the child and parent component

To be honest as well, I was thing about the same! 🤨

> If I didn't missed something the routing support on <BsNav> is only needed for Bootstrap 3

Indeed, I didn't realize that until now! 

I guess I'll have to work on a rollback then...
