### ISSUE TITLE
Bootstrap Modal Events are not fired

### ISSUE THREAD

**Issue by petrKoukal** [kaliber5/ember-bootstrap#88]
I am using the Ember-bootstrap Modal component, however it seems the bootstrap events `show.bs.modal` and alike are not triggered. 

I have a (miserable?) fix that at least allows listening for `show.bs.modal` and `hide.bs.modal`, however I think there are better solutions:

```
// bs-modal.js

// in show() {

// old code
this.get('modalElement')
        .show()
        .scrollTop(0)

// new code
this.get('modalElement')
        .show()
        .scrollTop(0)
        .trigger("show.bs.modal", [this.get("modalId")]);


// in hideModal() {

// old line
this.get('modalElement').hide()

//new line: 
this.get('modalElement').hide().trigger("hide.bs.modal", [this.get("modalId")]);
```

this allows you to listen to those events and take action on the given modal using it's ID: 
```
Ember.$(window).on('show.bs.modal', function(event, modalId) {
```

**Comment by petrKoukal** [comment]
or, smthg that's a tad better if one doesn't want to overwrite the source code, a standalone ember component that adds the events: 

```
import BsModal from 'components/bs-modal';
import $ from 'jquery';

export default BsModal.extend({
  init() {
    this._super(...arguments);

    let modalId = this.get("modalId");

    this.set("openAction", function() {
      $("#"+modalId).trigger("show.bs.modal");
    });

    this.set("openedAction", function() {
      $("#"+modalId).trigger("shown.bs.modal");
    });

    this.set("closeAction", function() {
      $("#"+modalId).trigger("hide.bs.modal");
    });

    this.set("closedAction", function() {
      $("#"+modalId).trigger("hidden.bs.modal");
    });
  },

});

```

**Comment by simonihmig** [comment]
These events are intensionally not fired, as events are a pretty "low level" concept that are normally not used to communicate with components. That's what the actions are for, you should use those!

**Comment by petrKoukal** [comment]
thanks for the explanation and advice
