### ISSUE TITLE
Ability to specify custom LESS directory

### ISSUE THREAD

**Issue by charlesfracchia** [kaliber5/ember-bootstrap#89]
The issue is that as it stands, the addon assumes that you will have all your styles inside of `/bower_components/bootstrap/less`. This is not great if you want to have your custom less files not be rewritten when updating or deploying.

It would be *very* useful to be able to pass a path as an option like:
```
'ember-bootstrap': {
    'importBootstrapCSS': false,
    'additionalPath': '/vendor/less' 
}
```

**Comment by simonihmig** [comment]
A am not sure I understand you well.. I guess your are referring to the newly added feature #80 ?
But this only is relevant if you do want to import Bootstrap's original less files. If you do not want to import them, but use some custom files, just put them into your `app/styles` folder and import them from there. Are do I miss something?

**Comment by charlesfracchia** [comment]
So, my end goal is to import the bootstrap original less files and add my own customizations on top, imported from a folder that is not `bower_components`, because this folder will be rewritten when doing a deploy.
However, when I try to put my less files into `app/styles` I get: 
```
The Broccoli Plugin: [LessCompiler] failed with:
undefined
```
ember-cli-build.js
```js
'ember-bootstrap': {
   'importBootstrapFont': false,
   'importBootstrapCSS': false
}
```
app.less
```less
@import "ember-bootstrap/bootstrap";
@import "ember-bootstrap/theme";
@import "custom/custom.less";
```

**Comment by charlesfracchia** [comment]
Ok! I figured it out. It took me some time to parse the actual error, which was indicated just the line above  what the `The Broccoli Plugin`. Turns out I had the wrong reference inside of my imported less files, and the path was completely fine.
Sorry for the unnecessary issue, it took me a while to wrap my head around the Broccoli paths.
