### ISSUE TITLE
Modal scrollable content

### ISSUE THREAD

**Issue by juggy** [kaliber5/ember-bootstrap#904]
The scrollable content is missing for ember-bootstrap's modal (normal or simple). In fact it seems there is no way to set classes on the dialog `div` itself (where the class `modal-dialog` is applied). 

There is an option for `centered`, the same option should be available for `scrollable`.

You can use the `size` property and set it to `lg modal-dialog-scrollable` as a workaround, but that is kinda ugly.

**Comment by simonihmig** [comment]
Thanks for reporting! Seems there is a `@scrollable` property missing here. Would be not very hard to implement, basically similar to `@centered`.

Would you (or anyone else?) be interested in providing a PR? #Hacktoberfest

**Comment by rwachtler** [comment]
@simonihmig I can work on this. 🙂
