### ISSUE TITLE
Autocapitalize and autofocus not working

### ISSUE THREAD

**Issue by jathanasiou** [kaliber5/ember-bootstrap#909]
It appears that neither `autocapitalize` nor `autofocus` are working are the moment. 

Tested with:
`<project>\app\templates\signup.hbs`
```javascript
<BsForm
  @formLayout="vertical"
  @model={{this}}
  @onSubmit={{@btnAct}}
  @class="bkg-color-white shadow"
  as |form|>
    <form.element
      @controlType="textarea" @label="Postcode2" @autocapitalize={{true}} @autocomplete={{true}}
      @placeholder="AAAA BBB" @property="postcode"
      @required={{true}}
    />
</BsForm>
```

The form and control is being rendered normally but these properties don't seem to work, even though `textarea` is a valid control for them.

---

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^3.0.0 -> 3.0.0
ember-cli: 3.14.0-beta.2 -> 3.14.0-beta.2
bootstrap: ^4.3.1 -> 4.3.1
bootstrap-sass: n/a
ember-cli-sass: ^10.0.1 -> 10.0.1
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: false
```

**Comment by simonihmig** [comment]
Thanks for reporting! 

This is strange, as we have this covered in [tests](https://github.com/kaliber5/ember-bootstrap/blob/master/tests/integration/components/bs-form/element-test.js#L578-L622). I assume you are using Ember 3.14? (not sure why that info does not show up as part of the info command...)

Btw, you are referring to `autofocus`, while in your example you are not setting that, but `autocomplete` instead. But at least `autocapitalize` *should* have worked here.

**Comment by simonihmig** [comment]
I tried your snippet, and it seems to work just fine. The `<textarea>` was rendered with a `autocapitalize="true"` attribute, so the attribute assignment worked. Note that `true` is no valid value for `autocapitalize` though, see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize.
