### ISSUE TITLE
how to use help-block of bootstrap for particular input if form-group having two inputs

### ISSUE THREAD

**Issue by shafayshahid123** [kaliber5/ember-bootstrap#916]
Actually i'm using two input in form-group but when i'm going to use help-block it's working if any of two option is filled or select but i want it two working with particular input.

<div class="form-group">
    <div class="input-group">                  
        <span class="input-group-addon">
             <select class="form-control select2" name="calling_code" id="calling_code" required="">
                 <option>.....</option>
              </select>
         </span>
         <input name="mobile_number" class="form-control input-lg flat" placeholder="{{ trans('theme.placeholder.mobile_number') }}" type="text" required/>
     </div>
     <div class="help-block with-errors"></div>
</div>

**Comment by simonihmig** [comment]
I am not entirely following you... could you please post a code example?

Also this question might be more appropriate to ask for in the `e-bootstrap` Ember Discord channel, so other's can chime in!

**Comment by jelhan** [comment]
Closing due to missing feedback.
