### ISSUE TITLE
submit button positioned wrong in horizontal form

### ISSUE THREAD

**Issue by jelhan** [kaliber5/ember-bootstrap#92]
Submit button is missing `form-control` class and column definition in horizontal form.

Generated HTML (taken from dummy app):

```
<form id="ember541" role="form" class="ember-view form-horizontal">
    <button id="ember602" type="submit" class="ember-view btn btn-primary"><!---->Submit<!----> </button>
</form>
```

Should be ([bootstrap documentation](http://getbootstrap.com/css/#forms-horizontal)):

```
<form class="form-horizontal">
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>
```

A work-a-round is to wrap `bs-button` in `bs-form-element` if it's a horizontal form:

```
{{#bs-form formLayout="horizontal"}}
  {{#bs-form-element}}
    {{bs-button defaultText="Submit" type="primary" buttonType="submit"}}
  {{/bs-form-element}}
{{/bs-form}}
```

At least this should be documented.

**Comment by simonihmig** [comment]
It is neither the scope of `bs-form` nor `bs-button` to add that markup, so yes, using `bs-form-element` is probably the way to go. So it is indeed more of a documentation thing...

**Comment by jelhan** [comment]
Wrong examples in documentation are at:
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form.js#L40-L46
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form-element.js#L21-L28
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs-form-element.js#L35-L45
 
But I'm not quite sure if it should be treated as documentation issue. To fix dummy app this code would be needed:

```
{{#bs-form formLayout=formLayout model=this action="submit"}}
  {{#if (eq formLayout 'horizontal')}}
    {{#bs-form-element}}
      {{bs-button defaultText="Submit" type="primary" buttonType="submit"}}
    {{/bs-form-element}}
  {{else}}
    {{bs-button defaultText="Submit" type="primary" buttonType="submit"}}
  {{/if}}
{{/bs-form}}
```

And I guess choosing between horizontal or vertical form layout depending on window width is a common use case. Perhaps a `bs-form-submit` component is needed?

**Comment by jelhan** [comment]
The documentation defaults to Bootstrap 4. So this isn't a documentation issue anymore. I would also not expect to see improved support for positioning the button in Bootstrap 3 as that one has reached end of life. Closing the issue therefore.
