### ISSUE TITLE
Using mouse-down and mouse-up for closing the modal dialog

### ISSUE THREAD

**Issue by lucasm-iRonin** [kaliber5/ember-bootstrap#934]
I'm not sure if it's a bug but it's definitely a difference from how Bootstrap's modals are handled. Bootstrap's implementation checks whether mouse button was down and up on the same element (https://github.com/twbs/bootstrap/blob/master/js/src/modal.js#L154). This prevents closing the modal when user holds down the button on a modal, drags the cursor to the backdrop and releases the button.

It's especially annoying if you have a text area inside the modal and want to select / highlight the text quickly. If you slightly move the cursor out of the modal you will close the dialog by mistake.

Is there any specific reason for using `click`?

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^2.6.1 -> 2.6.1
ember-cli: ~3.8.3 -> 3.8.3
bootstrap: n/a
bootstrap-sass: ^3.4.0 -> 3.4.1
ember-cli-sass: ^5.3.0 -> 5.6.0
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
importBootstrapCSS: false
importBootstrapFont: true
bootstrapVersion: 3
```

**Comment by simonihmig** [comment]
> Is there any specific reason for using click?

No, probably by mistake. Thanks for raising this!

**Comment by eyupatis** [comment]
@simonihmig @lucasm-iRonin I tried to solve this problem and created a pull request for it. If you have any feedbacks on the pull request, I can continue improving it. @simonihmig Thank you for all of your hard work on this addon.
