### ISSUE TITLE
ember-language-server integration for arguments/scope values autocomplete

### ISSUE THREAD

**Issue by lifeart** [kaliber5/ember-bootstrap#935]
It will be great to have full doc-based autocomplete for all bootstrap components.

Now it's absolutely possible with https://github.com/lifeart/ember-language-server/issues/12 addon API.

examples: 

https://github.com/lifeart/els-a11y-addon/blob/master/index.js
https://github.com/lifeart/ember-cli-inline-template-only-components/blob/master/lib/langserver.js
https://github.com/crashco/ember-template-component-import/blob/97445940d5ac4be32b684b818d869c8a64bf8e76/lib/langserver.js

Possible things:

* autocomplete component arguments
* show component arguments default values
* show component arguments annotations
* autocomplete yeild'ed values

**Comment by lifeart** [comment]
possible onComplete method implementation

```js
function isComponentArgument(focusPath) {
  if (focusPath.node.type === "AttrNode") {
    return focusPath.node.name.startsWith("@");
  }
}

function getComponentName(focusPath) {
  return focusPath.parent.tag;
}

const components = {
  ButtonGroup: {
    arguments: [
      {
        name: "vertical",
        description:
          "default: false, type: boolean, Set to true for a vertically stacked button group"
      }
    ]
  }
};

module.exports.onComplete = function(_, { results, focusPath, type }) {
  if (type !== "template") {
    return results;
  }

  if (isComponentArgument(focusPath)) {
    let componentName = getComponentName(focusPath);
    if (componentName in components) {
      components[componentName].arguments.forEach(arg => {
        results.push({
          label: arg.name,
          kind: 5,
          detail: arg.description
        });
      });
    }
  }

  return results;
};
```

**Comment by jelhan** [comment]
I agree that this would be awesome. But as more as I think about it more and more questions are coming to my mind. Let me start with the more generic ones:

1. How to reuse the existing docs? They are written in YUIDoc. YUIDoc can emit the [parsed data as JSON](https://yui.github.io/yuidoc/args/index.html#working-with-yuidoc-parsed-data), which we could use then for autocompletion. I'm also not that much worried about performance. We could ship the parsed data with the npm package and even preprocess it if required. But it would still require an integration layer between YUIDoc format and format required by language server.
2. How to deal with yielded components? They would require a much more complex `getComponentName` function, wouldn't they?

Do you know if anybody already working on these questions?

Additional to that generic questions we have some Ember Bootstrap specific issues which makes it even more complex: Our API docs don't distinguish between component's arguments and properties of the component's JavaScript class. The yielded values aren't documented in a machine-readable format at all. We might solve both issues by migrating to `ember-cli-addon-docs-yuidoc` which provides `@argument` and `@yielded` types to document that ones.

So all in all a lot of work left until we get autocompletion for Ember Bootstrap.

**Comment by lifeart** [comment]
I beleve 1 completly solvable with `parsed data as JSON`, 
regarding second one - I think it can be written as 

```js
const components = {
  ButtonGroup: {
    arguments: [
      {
        name: "vertical",
        description:
          "default: false, type: boolean, Set to true for a vertically stacked button group"
      }
    ],
    yield: [
       ['button', { arguments: [ {name: "label" } ] } ]
    ]
  }
};
```

for case :

```hbs
<ButtonGroup as |context|>
   <context.?>
   <context.button @label="...">
</ButtonGroup>
```

**Comment by jelhan** [comment]
Just for reference (and before some puts time into this): Had a follow up with @lifeart on Discord. We ended up with the idea to integrate Ember Language Server with Ember CLI Addon Docs. If that works out well, autocompletion would work out of the box for all addons documented with Ember CLI Addon Docs. In that case everything needed from Ember Bootstrap would be adopting `ember-cli-addon-docs-yuidoc` and documenting the component's arguments and yielded values using `@argument` and `@yield` types.

**Comment by jelhan** [comment]
[els-addon-docs](https://github.com/lifeart/els-addon-docs) integrates Ember Language Server with Ember CLI Addon Docs. It will automatically pick up the API docs and use them for completion provider. That's the path forward in my opinion. #979
