### ISSUE TITLE
Assertion Failed: Backdrop element should be in DOM if optional feature async-observers is enabled

### ISSUE THREAD

**Issue by Subaku** [kaliber5/ember-bootstrap#939]
Getting this error in the console with no other information when attempting to open a Modal programmatically. I.e 

`<BsModal @open={{showModal}} as |Modal|>...</BsModal>`

Note that `showModal` is a computed property that starts out false but once the condition for it to turn true happens (which is does) the model fails to open and I get the mentioned error.

Also note that Modals will open fine if I don't specify anything for the `@open` attribute or I'm referencing a simple boolean attribute off my component which I can toggle from the inspector. Only when it's from a computed property do I have any issues.

Ember: 3.14.1
Ember-Bootstrap: 3.1.0

**Comment by jelhan** [comment]
Are you able to provide a reproduction? We don't have a test for programmatically showing a `<BsModal>` but it should be covered by this test for `<BsModalSimple>` implicitly: https://github.com/kaliber5/ember-bootstrap/blob/58887daf2e15e7da07423772ec55510738979a24/tests/integration/components/bs-modal-simple-test.js#L89-L101

**Comment by Subaku** [comment]
Hi @jelhan 

Here's a repo I threw up with my current project I'm working on that exhibits the problem.
https://github.com/Subaku/ember-modal-issue.git

It's bare bones atm. If you click on any of the rendered View buttons in the table you should get some "asset-locations" loaded from mirage. This in turn makes the computed `showModal` inside the `asset-location-summaries/locations` component turn true and then you should get the error in the console.

Let me know if you need anything and thanks!

**Comment by jelhan** [comment]
Seems like some of your code is manipulating the DOM. I started debuging at this warning:

> WARNING: No wormhole destination element found for component <inventory@component:bs-modal-simple::ember196>. If you have set `insertEmberWormholeElementToDom` to false, you should insert a `div#ember-bootstrap-wormhole` manually!

`<div id="ember-bootstrap-wormhole">` is in the `dist/index.html`. But if I put a debugger here it's not in the DOM: https://github.com/kaliber5/ember-bootstrap/blob/58887daf2e15e7da07423772ec55510738979a24/addon/utils/dom.js#L65

It's present in the DOM again when the page is loaded. So it might be related to your loading animation.

I think it's a similar issue with the missing backdrop element. It's also not in the DOM when I put a debugger here: https://github.com/kaliber5/ember-bootstrap/blob/58887daf2e15e7da07423772ec55510738979a24/addon/components/base/bs-modal.js#L356-L358 But it's harder to debug cause it's generated dynamically. So I would start with the first one.

To be honest I don't think it's an issue with Ember Bootstrap.

**Comment by Subaku** [comment]
Thanks for the assistance.

It's interesting that your debugging came up with that as I'm not doing anything with the DOM. Thought maybe it was some other ember addon I was using so I commented out the only other rendering component I was using and still nothing.

I did manually add a div with the id "ember-bootstrap-wormhole" and that still didn't seem to make a difference. I've even created a new bare ember app with just the ember-bootsrap installed and am able to reproduce the problem. 

> To be honest I don't think it's an issue with Ember Bootstrap.  

I'm unsure if true or this is something with Ember itself...

As it stands I'm at a loss as to  what's causing this.

**Comment by Subaku** [comment]
Okay just figured it out. There's an optional feature I had enabled for my project `

**Comment by simonihmig** [comment]
> There's an optional feature I had enabled for my project default-async-observers which was causing the issue.

Thanks for investigating this. This is an interesting finding!

Yes, we still have some observers in use. Would certainly be good to ged rid of them. I'll keep this open I think, and treat this as a bug!

**Comment by jelhan** [comment]
@Subaku Thanks a lot for tracing this one down. Hadn't expected the optional feature to cause that kind of bugs. Sorry for pushing it back to early to your code base.

I've added an additional scenario to our CI pipeline in #945 that reproduces the bug. We might need some time to remove that observer. Would appreciate a pull request if you have time.

**Comment by Alonski** [comment]
Just ran into this as well :)

**Comment by viganella** [comment]
I am getting this after ember upgrade to 3.28.
