### ISSUE TITLE
Angle bracket component is not working on Ember 2.18

### ISSUE THREAD

**Issue by lacek** [kaliber5/ember-bootstrap#941]
When angle bracket syntax is used in templates, component is not rendered properly on Ember 2.18. On the other hand, the same template works on both Ember 3.1 and 3.14. Below are steps to reproduce the problem.

### Environment

* Mac OS: 10.14.6
* node: 8.16.2
* npm: 6.4.1

### Test with Ember 2.18

1. Create test project:

    ```sh
    npm install -g ember-cli@2.18
    ember new test-ember-2-18
    cd test-ember-2-18
    ember i ember-bootstrap@3.1.0
    echo '<BsButton>Button</BsButton>' > app/templates/application.hbs
    ember s
    ```

2. Check result on http://localhost:4200/ and DOM displayed in Google Chrome inspector:

    ```html
    <div id="ember247" class="ember-view">
        <bsbutton>Button</bsbutton>
    </div>
    ```

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^3.1.0 -> 3.1.0
ember-cli: ~2.18.2 -> 2.18.2
bootstrap: ^4.4.1 -> 4.4.1
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: true
```

### Test with Ember 3.1

1. Create test project:
    ```sh
    npm install -g ember-cli@3.1
    ember new test-ember-3-1
    cd test-ember-3-1
    ember i ember-bootstrap@3.1.0
    echo '<BsButton>Button</BsButton>' > app/templates/application.hbs
    ember s
    ```

2. Check result on http://localhost:4200/ and DOM displayed in Google Chrome inspector:

    ```html
    <div class="ember-view" id="ember244">
        <button id="ember265" class="btn btn-secondary ember-view" type="button">
            <!---->
            Button
        </button>
    </div>
    ```

Output from `ember bootstrap:info`:

```
Npm packages:
ember-bootstrap: ^3.1.0 -> 3.1.0
ember-cli: ~3.1.4 -> 3.1.4
bootstrap: ^4.4.1 -> 4.4.1
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: true
```

### Test with Ember 3.14

1. Create test project:
    ```sh
    npm install -g ember-cli@3.14
    ember new test-ember-3-14
    cd test-ember-3-14
    ember i ember-bootstrap@3.1.0
    echo '<BsButton>Button</BsButton>' > app/templates/application.hbs
    ember s
    ```

2. Check result on http://localhost:4200/ and DOM displayed in Google Chrome inspector:

    ```html
    <div class="ember-view" id="ember183">
        <button id="ember184" class="btn btn-secondary ember-view" type="button">
            <!---->
            Button
        </button>
    </div>
    ```

Output from `ember bootstrap:info`:

```
ember-bootstrap: ^3.1.0 -> 3.1.0
ember-cli: ~3.14.0 -> 3.14.0
bootstrap: ^4.4.1 -> 4.4.1
bootstrap-sass: n/a
ember-cli-sass: n/a
ember-cli-less: n/a
Bower packages:
bootstrap: n/a
bootstrap-sass: n/a
ember-bootstrap configuration:
bootstrapVersion: 4
importBootstrapCSS: true
```

**Comment by simonihmig** [comment]
Not sure what's happening here. But the ability to use angle bracket invocation is not a feature of ember-bootstrap itself, but rather of Ember (starting with 3.4 IIRC) - or for lower version of https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill.

Does it make any difference if you add `ember-angle-bracket-invocation-polyfill` to your 2.18 app's dependencies explicitly?

**Comment by lacek** [comment]
@simonihmig It works after installing`ember-angle-bracket-invocation-polyfill`! Thanks for your advice.

**Comment by jelhan** [comment]
Strange. That shouldn't be a difference cause we have that polyfill in `dependencies` not in `devDependencies`. :thinking:

**Comment by lacek** [comment]
For Ember 3.1, it is not completely working. The above test case won't work if the `application.hbs` is replaced with:

```hbs
<BsButtonGroup as |bg|>
  <bg.button>1</bg.button>
  <bg.button>2</bg.button>
  <bg.button>3</bg.button>
</BsButtonGroup>
```

And just like Ember 2.18, it works if `ember-angle-bracket-invocation-polyfill` is explicitly installed.

**Comment by jelhan** [comment]
I'm wondering if this is related to an old version of `ember-angle-bracket-invocation-polyfill` being used. Does `yarn list --pattern ember-angle-bracket-invocation-polyfill` report multiple versions? If so, does it also work if you add `resolutions: { "ember-angle-bracket-invocation-polyfill": "2.0.2" }` to your `package.json` instead of installing the dependency explicitly?

**Comment by lacek** [comment]
Apparently there is only a single version of `ember-angle-bracket-invocation-polyfil` in my test case:

```
root@0b5cbf81353a:/workdir/test-ember-2-18# npm ls ember-angle-bracket-invocation-polyfill
test-ember-2-18@0.0.0 /workdir/test-ember-2-18
`-- ember-bootstrap@3.1.0
  +-- ember-angle-bracket-invocation-polyfill@2.0.2
  `-- ember-popper@0.10.3
    `-- ember-angle-bracket-invocation-polyfill@2.0.2  deduped
```

Therefore, adding `"resolutions": { "ember-angle-bracket-invocation-polyfill": "2.0.2" }` to `package.json` makes no difference.

**Comment by simonihmig** [comment]
I guess the `setupPreprocessorRegistry` hook, which is used to transform the angle bracket invocation syntax to classic curlies is only used for the addons own files, just as the version of ember-cli-babel that an addon ships as its dependency transpiles only the addon files. 

In any case, if the app uses angle bracket invocation, and requires the polyfill, it should add it, on its own. So it think this is mainly an issue of the ember docs showing ABI and not mentioning that the polyfill needs to be added on old Ember versions. So basically a documentation issue. But not sure where to best add a note? 🤔
