### ISSUE TITLE
Form inside modal: Submit action not getting called

### ISSUE THREAD

**Issue by adambedford** [kaliber5/ember-bootstrap#961]
I'm running into an issue where my modal's `onSubmit` action isn't being called from a submit button in the modal footer. The form is in the modal body.

The template is as follows:
```handlebars
<BsModal @onSubmit={{fn this.save}} @onHide={{fn this.cancel}} class="right-panel" as |modal|>
  <modal.header>
    <h4 class="modal-title">Add User</h4>
  </modal.header>

  <modal.body>
    <BsForm @model={{@model}} as |form|>
      <form.element @property="firstName" @label="First Name" />
      <form.element @property="lastName" @label="Last Name" />
      <form.element @property="email" @label="Email" @controlType="email" />
    </BsForm>
  </modal.body>

  <modal.footer>
    <BsButton @onClick={{fn modal.close}} @type="secondary">Cancel</BsButton>
    <BsButton @onClick={{fn modal.submit}} @type="primary">Save</BsButton>
  </modal.footer>
</BsModal>
```

The backing controller code:
```javascript
import Controller from '@ember/controller';
import { action } from '@ember/object';

export default class AdminAccountsAccountShowCreateUserController extends Controller {
  @action
  async save(model) {
    try {
      await model.save()
      this.cancel()
    } catch(e){
      // Notify
    }
  }

  @action
  cancel() {
    this.transitionToRoute('admin.accounts.account.show')
  }
}
```

It's worth noting that the `cancel` action is behaving as expected. We're using Ember 3.15.

Any pointers would be greatly appreciated!

**Comment by jelhan** [comment]
`<BsModal>` has a special behavior regarding `onSubmit` action if it contains a `<form>` or a `<BsForm>`:

> **`onSubmit`**
>
> The action to be sent when the modal footer's submit button (if present) is pressed. _Note that if your modal body contains a form (e.g. Components.Form) this action will not be triggered. Instead a submit event will be triggered on the form itself. See the class description for an example._

To be honest I don't like that API but that's like it is currently.
