### ISSUE TITLE
Failing tests related to `-in-element` in Ember 3.17.0-beta

### ISSUE THREAD

**Issue by simonihmig** [kaliber5/ember-bootstrap#973]
See https://github.com/emberjs/ember.js/issues/18696

**Comment by chancancode** [comment]
Is this meant to be a pull request?

**Comment by simonihmig** [comment]
> Is this meant to be a pull request?

No, this is really just an issue! 😁

Intended to track progress, and eventually inform contributors about the issue, as this is causing any PR currently to fail.

I do plan to create a PR here to update the `in-element` usage (and in `ember-popper`), as soon as https://github.com/kaliber5/ember-in-element-polyfill/pull/37 is merged and released (feel free to chime in there!). I already prepared a bit of it (using the new `insertBefore=null` API), but it is apparent that the error is unrelated to the usage here, so needs to be fixed upstream IMO.

**Comment by simonihmig** [comment]
Fixed upstream.
