### ISSUE TITLE
Possible to cancel modal closing by aborting a transition?

### ISSUE THREAD

**Issue by adambedford** [kaliber5/ember-bootstrap#978]
I have a route modal (modal that opens automatically when entering a route) that transitions to a different route on close. The route that the modal is on also has a `willTransition` hook that warns if the user is trying to leave the page with a dirty changeset. This works great with normal routes (non-modal), however, on modal routes, the transition is aborted correctly but the modal still closes.

Is there a way to somehow cancel closing the modal if the exit transition is aborted?

**Comment by jelhan** [comment]
Closing a modal could be aborted by returning `false` from [`onHide` action](https://www.ember-bootstrap.com/api/classes/Components.Modal.html#property_onHide):

> *onHide*
>
> The action to be sent when the modal is closing. This will be triggered by pressing the modal header's close button (x button) or the modal footer's close button. [...]
>
> You can return false to prevent closing the modal automatically, and do that in your action by setting open to false.

But you would need to check the abort conditions also in that action and not only in `willTransition`.

**Comment by adambedford** [comment]
Hhmmmm good point. I wonder what transitionTo returns if you abort the transition. Will look into it.

**Comment by jelhan** [comment]
> Hhmmmm good point. I wonder what transitionTo returns if you abort the transition. Will look into it.

It returns a `Transition`. Returning a `Promise` from `onHide`, which causes the closing to be paused until the promise fulfills, is not supported (yet). So I don't think that approach will work.

**Comment by adambedford** [comment]
The `Transition` has an `isAborted` property, so we're just returning `!transition.isAborted` from the modal cancel action

**Comment by jelhan** [comment]
Glad to hear it worked out for you. Have assumed that this property is set async. Feel free to reopen if you face additional issues.
