### ISSUE TITLE
How to correctly disable buttons now?

### ISSUE THREAD

**Issue by rwwagner90** [kaliber5/ember-bootstrap#994]
We have stuff like this:

```hbs
  <BsButton
    data-test-btn-open-user-modal
    disabled={{if
      this.organizationService.isOrganizationSelected
      (not this.canAddUserToCurrentOrganization)
      (not this.canAddUserToAtLeastOneOrganization)
    }}
    @defaultText="Add User"
    @type="primary"
    @icon="mdi mdi-18px mdi-plus"
    @onClick={{action "setupModal"}}
  />
```

I made sure to remove the `@` from disabled, but it still seems to throw deprecations. How are we supposed to set this?

**Comment by rwwagner90** [comment]
If anyone else is seeing deprecations and not sure why, check if you have any `dd.button` instances you need to also updated. Fixed it for me!

**Comment by jelhan** [comment]
Glad to know that someone is actually using that deprecations. :smile:
